### ISSUE TITLE
Failed to unload several kexts

### ISSUE THREAD

**Issue by stevezhengshiqi** [acidanthera/bugtracker#1018]
First of all, thank you guys for all the great kernel extensions and the bootloader.

macOS Version: Tested on 10.14.6 and 10.15.5 + OpenCore v0.5.9

My issue is that in VoodooPS2Controller v2.1.5, it seems that VoodooPS2Controller can't be unloaded successfully. These are the steps I did to unload the VoodooPS2Controller. (In PlugIns folder, I only have VoodooPS2Keyboard)
- Run `sudo kextunload -b as.acidanthera.voodoo.driver.PS2Keyboard` - Success
- Run `sudo kextunload -b as.acidanthera.voodoo.driver.PS2Controller` - Error occurs, the terminal says:
```
(kernel) Can't unload kext as.acidanthera.voodoo.driver.PS2Controller; classes have instances:
(kernel)     Kext as.acidanthera.voodoo.driver.PS2Controller class AppleACPIPS2Nub has 1 instance.
Failed to unload as.acidanthera.voodoo.driver.PS2Controller - (libkern/kext) kext is in use or retained (cannot unload).
```

We found this issue because my friend and I are handling some special function keys. In addition, we make some unload tests on other kexts, like AppleALC and SMCProcessor, but both failed. To unload AppleALC, I run `sudo kextunload -b as.vit9696.AppleALC`, and I got:
```
(kernel) Kext as.vit9696.AppleALC did not stop (return code 0x5).
(kernel) Kext as.vit9696.AppleALC can't unload - module stop returned 0xdc008017.
Failed to unload as.vit9696.AppleALC - (libkern/kext) kext (kmod) start/stop routine failed.
```
I am not sure whether this behavior is normal or not. (Maybe result in memory leak(?)) Please have a check, and thank you guys!

**Comment by 07151129** [comment]
Most Lilu plugins are not unloadable because the logic to undo the patches is rather complex, and it is not always possible to do so. There is no memory leak involved when not unloading a plugin because its memory is still in use. Of course, some kexts may really leak memory during their lifetime, but I am not aware of any.

For Voodoo kexts, you should contact the original authors.

**Comment by Goshin** [comment]
> For Voodoo kexts, you should contact the original authors.

Isn't VoodooPS2 now maintained by the Acidanthera team? 

I encounter the error same with stevezhengshiqi and kernel panic when trying to unload VoodooPS2Controller with `kextunload`.

I just find out power management initialization in `AppleACPIPS2Nub` is not paired with `PMstop()` in `::stop()`, which causes the instance leak.
https://github.com/acidanthera/VoodooPS2/blob/c43a1c7826d15be1d69e9c9bd766b846bddb891e/VoodooPS2Controller/AppleACPIPS2Nub.cpp#L67-L70
Actually PM init & reg in `AppleACPIPS2Nub` is redundant and meaningless as it doesn't override the `::setPowerState(...)` method.

And the kernel panic when unloading seems related to the `Library/LegacyIOxxx` stuff (for 10.11 compatibility?)
After removing them and compiling with the stock IOKit headers, the problem is gone.

<details>

<summary>Panic report</summary>

```
panic(cpu 0 caller 0xffffff801484aa3a): Kernel trap at 0xffffff8014e0485f, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000000020, CR3: 0x000000043dd2b09d, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff8054b49140, RCX: 0xffffff804661a680, RDX: 0xffffff8203b83980
RSP: 0xffffff8203b839a0, RBP: 0xffffff8203b83a00, RSI: 0xffffff8055146700, RDI: 0xffffff8054b49a80
R8:  0x0000000000000001, R9:  0x0000000000000001, R10: 0x00000000000000c5, R11: 0xffffff80454c8e40
R12: 0x0000000000000000, R13: 0xffffff80550f9750, R14: 0xffffff8046690870, R15: 0xffffff804661a680
RFL: 0x0000000000010202, RIP: 0xffffff8014e0485f, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000020, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff8203b83400 : 0xffffff801471f5cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff8203b83450 : 0xffffff8014858b05 mach_kernel : _kdp_i386_trap + 0x155
0xffffff8203b83490 : 0xffffff801484a68e mach_kernel : _kernel_trap + 0x4ee
0xffffff8203b834e0 : 0xffffff80146c5a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8203b83500 : 0xffffff801471ec97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff8203b83600 : 0xffffff801471f087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff8203b83650 : 0xffffff8014ec27cc mach_kernel : _panic + 0x54
0xffffff8203b836c0 : 0xffffff801484aa3a mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff8203b83840 : 0xffffff801484a738 mach_kernel : _kernel_trap + 0x598
0xffffff8203b83890 : 0xffffff80146c5a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8203b838b0 : 0xffffff8014e0485f mach_kernel : __ZN9IOService19actionWillTerminateEPS_jP7OSArraybPv + 0xcf
0xffffff8203b83a00 : 0xffffff8014e2cd9e mach_kernel : __ZN10IOWorkLoop9runActionEPFiP8OSObjectPvS2_S2_S2_ES1_S2_S2_S2_S2_ + 0x3e
0xffffff8203b83a40 : 0xffffff8014e03bbe mach_kernel : __ZN9IOService15terminateWorkerEj + 0x4de
0xffffff8203b83ac0 : 0xffffff8014e03377 mach_kernel : __ZN9IOService23scheduleTerminatePhase2Ej + 0x157
0xffffff8203b83b20 : 0xffffff8014e06e50 mach_kernel : __ZN9IOService15terminatePhase1Ej + 0xaa0
0xffffff8203b83ba0 : 0xffffff8014e266c1 mach_kernel : __ZN11IOCatalogue16terminateDriversEP12OSDictionaryPc + 0x141
0xffffff8203b83be0 : 0xffffff8014e26987 mach_kernel : __ZN11IOCatalogue25terminateDriversForModuleEP8OSStringb + 0x87
0xffffff8203b83c20 : 0xffffff8014daae91 mach_kernel : __ZN6OSKext10removeKextEPS_b + 0x1b1
0xffffff8203b83c60 : 0xffffff8014db1a7f mach_kernel : __ZN6OSKext13handleRequestEP4hostjPcjPS2_PjS3_S4_ + 0x7ff
0xffffff8203b83ce0 : 0xffffff8014dc1c38 mach_kernel : _kext_request + 0x1c8
0xffffff8203b83d60 : 0xffffff801478079b mach_kernel : _host_priv_server_routine + 0x1ecb
0xffffff8203b83db0 : 0xffffff8014725328 mach_kernel : _ipc_kobject_server + 0x238
0xffffff8203b83e10 : 0xffffff80146fbcc5 mach_kernel : _ipc_kmsg_send + 0x135
0xffffff8203b83e70 : 0xffffff8014712aa2 mach_kernel : _mach_msg_overwrite_trap + 0x2d2
0xffffff8203b83f00 : 0xffffff8014830d05 mach_kernel : _mach_call_munger64 + 0x205
0xffffff8203b83fa0 : 0xffffff80146c6226 mach_kernel : _hndl_mach_scall64 + 0x16

BSD process name corresponding to current thread: kextunload
Boot args: -igfxnohdmi debug=0x100 -alcbeta keepsyms=1 darkwake=0 -wegnoegpu ps2rst=0 igfxfw=2 igfxpavp=1 -v 

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x0000000014400000
Kernel text base: 0xffffff8014600000
__HIB  text base: 0xffffff8014500000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Panic diags file available: YES (0x0)
```

</details>

**Comment by vit9696** [comment]
Yeah, @usr-sse2 indeed tries to maintain VoodooPS2, but we do not have many devices here besides him, so it is always a difficult thing.

The lack of `PMStop()` looks like an obvious bug. I think Power Management initialisation was required for macOS to connect to these methods, so even without `setPowerState` it was resolving some issue. Maybe I am wrong, because VoodooPS2 is really the inherited legacy. Mind submitting a PR?

Kext unloading is unsupported in 11.0+, so I am unsure we should really care. But if you manage to understand the actual reason for that, could you tell us? Indeed, the older headers are used for legacy OS compatibility.

**Comment by Goshin** [comment]
@vit9696 you are right. Unloading a platform driver seems not really important for daily use. For this reason, the lack of `PMstop()` is also insignificant. I just encountered that while doing some other testing about key mapping, so I am not going to dig too much into it. Maybe these different headers cause a vtable inconsistency?

I think removing PM initialization will not break the power event link between its client and its parent device nub, as the init & reg operate recursively in the power hierarchy plane.

**Comment by vit9696** [comment]
Could try. I do not have any non-mac laptop hardware, but if that works, we can merge.
