### ISSUE TITLE
Lilu 1.4.6 RELEASE vs DEBUG: HD530 doesn't wake up from sleep in RELEASE

### ISSUE THREAD

**Issue by volopasse** [acidanthera/bugtracker#1087]
I have the following rather odd issue with Lilu (1.4.6 release, 34dd31d), on Big Sur Beta 4 (20A5343i). When display goes to sleep (e.g. with `pmset displaysleepnow`), it is able to wake up with the DEBUG build of the latest Lilu release, but not with the RELEASE build. The Lilu build seems to be the only variable, changes to Opencore/WEG don't impact the behaviour. macOS system sleep is disabled with `pmset -a disablesleep 1`, this is only about display sleep.

I think the regression occurred after d9c8228: with that commit the RELEASE version is able to wake up, but none of the later commits work (using Dortania builds)

EFI folder and OpenCore logs attached (with the RELEASE Lilu loaded), with debug parameters in config.plist as per Dortania guide
[EFI.zip](https://github.com/acidanthera/bugtracker/files/5047428/EFI.zip)
[opencore-2020-08-09-112207-Lili-release.txt](https://github.com/acidanthera/bugtracker/files/5047429/opencore-2020-08-09-112207-Lili-release.txt)

Happy to provide further info as needed. Thanks!

EDIT: this is happening with `igfxonln=1` enabled

**Comment by vit9696** [comment]
Next commit (https://github.com/acidanthera/Lilu/commit/633f948147a95eb3dc4339bb096f4c7094ddf8dc) is only relevant for the debug build when logging is on. Basically the RELEASE builds will not change anyhow at all with this. Given that it is broken for you, I think the variable here is that the hardware does not work consistently, and remembers some kind of state, so it is not really Lilu being the cause here.
