### ISSUE TITLE
Default agdpmod breaks Navi eGPU configuration

### ISSUE THREAD

**Issue by osy86** [acidanthera/bugtracker#1117]
When `agdpmod` is not set, it defaults to `agdpmod=detect`. Since `isGraphicsPolicyModRequired` returns true, the AGDP patches will be set.

When a Navi eGPU is used in a TB3 configuration, this results in a black screen on boot with no display. Debugging the issue we see in the logs

```
[190:0:0] [AGDC] AMDRadeonX6000_AmdAgdcServices::waitForAGDCReady() ??? AGDC failed to register with controller!
```

The Navi eGPU will fail to work without AGDC. The solution is to set `agdpmod=ignore`. However, it seems wrong that the default configuration would cause issues.

Reference: https://github.com/osy86/HaC-Mini/issues/312

**Comment by vit9696** [comment]
Hi, it is indeed the case that for some IGPUs you need a different agdpmod. It is not just Navi I think, though Navi is a common example. Depending on the screen count and port usage you may need a different policy even on the same GPU.

There is no golden bullet, and the point with the default one is that it is fairly consistent and works predictably. If we try to do the GPU detection by IDs it will make it more complicated and prone to errors as new GPUs appear on the market.

It is indeed the case that Navi drivers did not get the patches to run without AGDC unlike e.g. Polaris, where we do have some, but I do not own Navi at the moment and it is hard to predict the exact workaround. If you would like to contribute them, it will be great, but otherwise I am afraid this situation is be design.
