### ISSUE TITLE
OcPngLib: Error while decoding PNG image

### ISSUE THREAD

**Issue by michyprima** [acidanthera/bugtracker#1120]
Hey!
I see this error in OC's log when loading FV2. The system boots just fine, but the password screen has no background.
It happens to work from time to time, possibly one time out of ten. 
The image is definitely there though because Clover can display it every single time it boots.
Edit: Happening on both 10.14 and 10.15. 
![It looks like this](https://user-images.githubusercontent.com/4800403/91202701-79584400-e702-11ea-8f90-b4460def56f3.jpeg).

**Comment by vit9696** [comment]
You may have hit the size limit with your background. Could you attach the image and provide the debug log?

**Comment by michyprima** [comment]
Sure! I'm attaching the log. The image is the default one from Catalina, I never changed it. Furthermore, sometimes it loads, sometimes it doesn't.
If you look at my screen picture you can see the whole screen is corrupted. The password box is still there (on real macs it disappears).
[opencore-2020-08-25-170827.txt](https://github.com/acidanthera/bugtracker/files/5125320/opencore-2020-08-25-170827.txt)

**Comment by vit9696** [comment]
The password box should disappear if you set the ExitBootServicesDelay quirk. As for the png, it is not a size limitation actually, but something special within lodepng. Could you please upload the contents of your `Preboot` partition?

**Comment by michyprima** [comment]
> The password box should disappear if you set the ExitBootServicesDelay quirk.
Tried, didn't work (I set it to 1000000 which did work because it booted slower, but the corruption was still there). Could it perhaps be a video memory issue?
> As for the png, it is not a size limitation actually, but something special within lodepng. Could you please upload the contents of your `Preboot` partition?
https://drive.google.com/file/d/1MHk4-UXdz7fgsqfm46Vz47i2YYVNhPCo/view?usp=sharing

**Comment by vit9696** [comment]
I checked the background image, and it looks like Apple made it over 56 megabytes (sic!). This really is ridiculous, as there often is very small amount of in the lower 4 gigabytes at boot time (like ~300-500 megabytes), and loading 56 megabytes from the file to memory, and then decoding it will require quite a lot of free RAM. I am afraid you simply get an allocation failure.

I provided a more verbose logging in 0.6.1 c6a3e17, and will need you to confirm my theory. You could build yourself or wait till the build arrives to [Dortania Builds](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true). If it is the case, I will try to see whether I can do any improvement.

**Comment by michyprima** [comment]
Just built from HEAD:
`14:873 03:689 OCPNG: Error while decoding PNG image - 83`

Completely offtopic, ignore this if you want: how can I see the slide the system choses if boot fails? Very rarely I get the "DENIED" symbol and I believe I can fix this with the new ProvideMaxSlide parameter.

**Comment by vit9696** [comment]
Indeed, it is:

```
    case 83: return "memory allocation failed";
```

I will try to workaround it in the upcoming days.

**Comment by michyprima** [comment]
Glad to help. Let me know if I can do something, I'm pretty good with C. I don't know well the OC codebase but I would do my best.
I noticed it does show the image from time to time, does this have to do with the slide it choses?
The screen is still corrupted though:
[IMG_0142.HEIC.zip](https://github.com/acidanthera/bugtracker/files/5131051/IMG_0142.HEIC.zip)

Not to blame OC or anything but I'm curious, why does Clover not have this issues? (it loads the background and the box disappears right after the booting starts)

**Comment by vit9696** [comment]
I am actually not sure what do you mean under screen corruption, it looks ok from the screenshot. I might be missing something. Could you provide more detail?

The reason why it sometimes works indeed depends on the slide chosen and similar factors, as depending on the memory used it will have more or less free contiguous space. As for Clover, I think it uses a different library to decode png images. It might be that it has a different memory pattern, but I do not believe we can use that library for security reasons.

To be honest, I do not have much time to work on this issue, so if you want to help it will be very handy. Firstly, you could try updating lodepng[1][2] to the newest version as upon my request it gradually got better memory management. Note, that we modded ours slightly to make it compatible with UEFI that does not have realloc (but only alloc/free).

If that does not help, you could try playing a bit further with the memory allocation strategies. The limitation here is the kind of memory you could have in UEFI and the memory EfiBoot needs. Basically you have two kinds of memory: pages (can be allocated anywhere) and pool memory (controlled by the firmware). Pool memory is allocated in the lower 4 gigabytes (which we always lack), while pages can be allocated in higher memory[3].

EfiBoot interacts with OpenCore via a protocol, which can either load image to a preallocated buffer, or requires a pool buffer we need to allocate ourselves[4]. For FV2 UI it always asks us to allocate the buffer (by passing NULL to `DecodeImageData`), so regardless of how we load the picture, we will need to later return it via a pool buffer (so that EfiBoot can free it afterwards). The workaround that is somewhat undesired but will likely work is to load PNG in higher addresses (page memory) and then copy it to the pool memory after decoding. Another workaround could be specifying PNG image size as a hint to the allocator and preallocate more memory, effectively avoiding fragmentation. In fact we even have a custom allocator there, which we might of some use for that purpose[5].

[1] https://github.com/lvandeve/lodepng
[2] https://github.com/acidanthera/OpenCorePkg/tree/master/Library/OcPngLib
[3] https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcMemoryLib/MemoryAlloc.c
[4] https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcAppleImageConversionLib/OcAppleImageConversionLib.c
[5] https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcMemoryLib/UmmMalloc.c

**Comment by michyprima** [comment]
Check these videos:
[fv.zip](https://github.com/acidanthera/bugtracker/files/5131361/fv.zip)
When booting with OC there are leftover ui elements that shouldn't be there. It should look like it does in the clover video.

thank you for the resources, I'll have a look!

**Comment by vit9696** [comment]
Yeah, might be due to that allocation issue… But usually `ExitBootServicesDelay` or `TimerResolution` help. I have `3000000` and `60000` accordingly, but it really varies from platform to platform.

**Comment by michyprima** [comment]
Ok so `TimerResolution` definitely fixed the UI elements. The thing is it fixed the allocation error too. Since setting it to `520000` (low values like yours made the keyboard not register keypresses) I cannot reproduce a black background anymore. `ExitBootServicesDelay` was not needed.

**Comment by vit9696** [comment]
Hmmm, well, it will still be interesting if you could revert the values and see if you can improve the decoding issue, as I believe it will still happen, just more rarely. Also, I think you may be happy with 0 for TimerResolution. Other than that, it is about KeyForgetThreshold when to forget the keys (check the docs, it has some hints about key misses).

In any case, since a workaround is found, I will close the issue. At least until any better information or workaround appears.
