### ISSUE TITLE
After booting Windows with ASUS PRIME H370-A, when restarting, the BIOS becomes a black screen

### ISSUE THREAD

**Issue by mifjpn** [acidanthera/bugtracker#1224]
This issue is similar to the issue below, which is already closed. ”OpenCore / Bootstrap causes BIOS corruption on Gigabyte Z87 if to make reset CMOS # 1222”
So I thought the solution to this problem would fix it, but it still doesn't, so I'll report it.

I use OpenCore to boot Windows.

Then reboot.

When I hold down the DEL key and reboot, the BIOS screen does not appear.

Black screen only.

The only way to get this back back is to flash the BIOS again. (I hesitate to test it because it puts the motherboard at risk because it has to be flushed.)

This issue occurs on the ASUS PRIME H370-A (i7 8700).

I hope it works, so I would appreciate it if you could fix it.

**Comment by vit9696** [comment]
This is very unfortunate, but the issue is with your BIOS. You have to write ASUS about the issue or choose a different motherboard vendor. From what we know the issue is unique to ASUS since Skylake generation. Thx for reporting though.

**Comment by Download-Fritz** [comment]
@mifjpn I heard about such issues multiple times but I'm not sure what the exact issue could be.
1) If you disable Bootstrap, disable DisableVariableWrite, reset NVRAM and boot Windows **without** OC, what happens?
2) If you enable Bootstrap, disable DisableVariableWrite, reset NVRAM and boot Windows **with** OC, what happens?
3) If you disable Bootstrap, enable DisableVariableWrite, reset NVRAM and boot Windows **with** OC, what happens?

**Comment by mifjpn** [comment]
I took care to follow your instructions.
So the explanation is verbose, for I wanted accuracy.

1
I edited config.plist as below.
Misc-Security-BootProtect:None
Booter-Quirks-DisableVariableWrite:NO(False)

I reset my computer and pressed the F8 button (UEFI selection) to run OpenCore.
I chose OpenCore "Reset NVRAM".
It rebooted automatically.
I reset my computer and pressed the F8 button (select UEFI) to run Windows.
Then I rebooted on Windows. Then I pressed the DEL key to try to bring up the BIOS screen.
Result: The BIOS screen will appear.

2
I edited config.plist as below.
Misc-Security-BootProtect:Bootstrap
Booter-Quirks-DisableVariableWrite:NO(False)

I reset my computer and pressed the F8 button (UEFI selection) to run OpenCore.
I chose OpenCore "Reset NVRAM"
It rebooted automatically.
I reset my computer and pressed the F8 button (select UEFI) to run OpenCore.
I selected Windows,and boot Windows.
Then I rebooted on Windows. Then I pressed the DEL key to try to bring up the BIOS screen.
Result: The BIOS screen will appear. !?!!!!!!!(WoW!)
After that, I booted Catalina and Big Sur Beta 10 with Clover and OpenCore and pollute NVRAM.
I choose Windows on OpenCore. I rebooted on Windows.Then I pressed the DEL key to try to bring up the BIOS screen.
Result: The BIOS screen will appear. （WoW,I made it using Sample.plist while looking at Dortania, but it's a mystery.）

３
I edited config.plist as below.
Misc-Security-BootProtect:None
Booter-Quirks-DisableVariableWrite:Yes(True)

I reset my computer and pressed the F8 button (UEFI selection) to run OpenCore.
I chose OpenCore "Reset NVRAM".
It rebooted automatically.
I reset my computer and pressed the F8 button (select UEFI) to run Windows.
Then I rebooted on Windows. Then I pressed the DEL key to try to bring up the BIOS screen.
Result: The BIOS screen will appear.(WoW!!)

When I was having problems, I used OpenCore, which I got from the following URI.
https://github.com/williambj1/OpenCore-Factory/releases/tag/2020-10-16

After that, I recreated OpenCore in the following build and put it in EFI.
9e868c91

Thank you very much. The problem was solved.
It's thanks to you that I noticed! !!

**Comment by vit9696** [comment]
I do not believe it is solved, just hidden. There is a bug in ASUS BIOS, which corrupts boot entries under unclear circumstances often requiring you to reflash the BIOS. These circumstances usually include Windows and macOS installed together, but the exact sequence of actions necessary to trigger the issue is unknown.

ASUS BIOS can automatically add Windows boot entries, and we think that when the boot entries are empty or have something from the previous boots but not the Windows entry that is detected automatically, ASUS BIOS just dies. With Bootstrap it happened less commonly, but it all depends.

OpenCore does not let any operating system create its boot entry visible to BIOS reducing the chance of a brick. However, when you run Clover, which also adds its own entry, or Windows outside of OpenCore via F8 menu, you are at risk of them bricking your BIOS basically.

**Comment by mifjpn** [comment]
I checked again.
 If Bootstrap is disabled, no problem! !!
great! !!

**Comment by mifjpn** [comment]
I see.
I was convinced that the BIOS was unstable.
I pray to ASUS that the BIOS version will be upgraded and stable in the future.
Thank you Vit9696!

**Comment by btwise** [comment]
@mifjpn 
After reset NVRAM for the first time, it is usually possible to enter the BIOS normally. but  after starting it through OC for many times, it is not certain when the black screen will appear again. my Asus B150 motherboard is the same phenomenon，every time I want to enter the BIOS, I just run the cleanNVRAM tool

**Comment by mifjpn** [comment]
vit, Friz and others are working very hard on the development, so I don't want to say the following.
But I'm sorry I have to say.
I wonder why this problem doesn't happen with Clover.
I would like to apologize to vit, Friz and others for saying this.

**Comment by vit9696** [comment]
It does, starting with macOS Catalina. It did not happen earlier, because Clover simply does not have support for native macOS ←→ Windows switching via Boot Camp and similar software. Also Clover has serious issues with authenticated restart, and correct boot entry choice during macOS installation and upgrade. So, in general it is the lack of functionality in Clover that reduces the possibility of this situation happening. By disabling `RequestBootVarRouting` and `BootProtect` you essentially achieve Clover behaviour, but with all the downsides of broken operating system switching.

**Comment by mifjpn** [comment]
Vit9696, I seem to overstate. I understand that Clover has its drawbacks. I sincerely apologize.
It's very sad that a great OpenCore doesn't work without a reset because of all the crappy flaws in ASUS's BIOS.
That's all I want to say.

**Comment by Download-Fritz** [comment]
@mifjpn 
> vit, Friz and others are working very hard on the development, so I don't want to say the following.
> But I'm sorry I have to say.

Haha, no worries, we're not out of sugar.

> By disabling RequestBootVarRouting and BootProtect you essentially achieve Clover behaviour, but with all the downsides of broken operating system switching.

Just to be absolutely sure, maybe you can actually test this?

**Comment by mifjpn** [comment]
Thank you for your kindness, Fritz.
Actually, I have been trying "disabling RequestBootVarRouting and BootProtect" since yesterday.
It's been 6 hours since I left Windows running.
For now, the BIOS screen seems to come out properly.
Thank you very much.
