### ISSUE TITLE
[Feature Request] Ability to disable trackpad when pressing brightness keys (just like VoodooPS2)

### ISSUE THREAD

**Issue by Ab2774** [acidanthera/bugtracker#1228]
Hi
In VoodooPS2, when typing the trackpad stops (disable temporarily), but in BrightnessKeys it doesn't, can you please implement this feature to BrightnessKeys?
Regards.

**Comment by zhen-zen** [comment]
Can you verify whether it works on your laptop?

**Comment by Ab2774** [comment]
Hi, I did test it and it works!
but the only downside is that when the trackpad in VoodooPS2 is disabled longer than BrightnessKeys, is there's a way to match both of them?
If I made them match I'll submit a PR.
Thanks

**Comment by zhen-zen** [comment]
I didn't get that point. Both drivers will only send a timestamp, and touchpad drivers will use it to discard input packets for a given length of time. So there should be no differences.

**Comment by Ab2774** [comment]
Hi, I'm also very confused too, don't know what's causing to be slightly different.
Can you please test and see the differences?
Cheers

**Comment by zhen-zen** [comment]
I just moved the timestamp part before sending keystroke, and now the experience seems to be closer.

**Comment by Ab2774** [comment]
Hi, unfortunately, it does not, disabling in VoodooPS2 lasts longer than BrightnessKeys.
I'm gonna investigate it more and see what I can find.
Thanks for your patience, really appreciate it.

**Comment by vit9696** [comment]
For the time being I can merge the current PR since it improves the situation in any case and will fit in the November release.

**Comment by zhen-zen** [comment]
On BrightnessKeys' side, I suppose there could be no further improvement other than dirty hacks such as additional hardcoded delay.
Theoretically, VoodooPS2 will call `dispatchKeyboardEventX` right after sending the timestamp. While for BrightnessKeys, the keycode will go through an additional process through `dispatchMessage`. But the difference should not be that large since other kexts like VoodooInput relies on the same protocol for touch input messages.
By the way, have you tested the difference between BrightnessKeys and old SSDT approach?

**Comment by Ab2774** [comment]
Hi @zhen-zen, it appears after all that it's not BrightnessKeys issue whatsoever, I've tested it with an older VoodooPS2 and manually patched brightness keys, and the issue still exists.
I think it's an ACPI issue as native keys get disabled differently.
I do agree with @vit9696, to merge it now as it's all we can do.
Cheers
