### ISSUE TITLE
EDK Patch 0003 cannot patch using `git am` without minor change

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1232]
@Goldfish64 @vit9696

I've just downloaded the latest of everything, and was trying to apply [the EDK patches](https://github.com/acidanthera/OpenCorePkg/tree/master/Patches) to the EDK code. After playing around as normal to resolve LF/CRLF line-ending problems, the first three patches apply fine, but the final one does not:

```
UDK % git am OpenCorePkg/Patches/*
Applying: MdeModulePkg/SataControllerDxe: Add support for drives in RAID mode
Applying: ShellPkg: Add support for input with separately reported modifiers
Applying: MdeModulePkg/AtaAtapiPassThru: Add support for drives in RAID mode
Applying: MdeModulePkg/AtaAtapiPassThru: Reduce IDE drive detection timeout
fatal: empty ident name (for <>) not allowed
UDK %
```

All that seems necessary to fix this error in the final patch and let it apply fine too is to add an attribution line to the top of [the patch file](https://github.com/acidanthera/OpenCorePkg/blob/master/Patches/0003-MdeModulePkg-AtaAtapiPassThru-Reduce-timeout.patch), e.g.:

```
From: Goldfish64 <goldfishnet@aol.com>
```

More lines can be added to make the 0003 patch file even more consistent with the full `git format-patch` layout of the other three patches (e.g. adding the opening and closing `---` and `--` lines around the diff; possibly adding a `Signed-off-by:` line), but only the first change seems necessary to make the patch apply successfully with `git am`.

I hope I haven't misunderstood the purpose and use of these patches as I'm new to this project; hopefully not though, as the first three patches make sense and apply as I think they should, and the final one does too, after this change. If this does make sense and is worth changing then of course I'd be very happy to do a small PR for the change.

**Comment by vit9696** [comment]
Thx

**Comment by MikeBeaton** [comment]
The EDK2 patches are being applied in `efibuild.sh` using `git apply --ignore-whitespace`, hence patch 0003 works fine just as it was, with the `build_oc.tool` build process.

I was applying them manually with `git am`. I had worked out I could use `unix2dos` on the patches, followed by `git am --keep-cr`, at which point they work as full patch files (i.e. they make the whole commit in one go, with the original author info preserved), but it is only then that the author is required in the patch file.

So I hadn't fully understood the build process, but perhaps it remains useful to have the patches with the minor fix (thanks!), so that `git am` can also be used to apply them, if someone wants to.

**Comment by Bmju** [comment]
The EDK2 patches are being applied in `efibuild.sh` using `git apply --ignore-whitespace`, hence patch 0003 works fine just as it was, with the `build_oc.tool` build process.

I was applying them manually with `git am`. I had worked out I could use `unix2dos` on the patches, followed by `git am --keep-cr`, at which point they work as full patch files (i.e. they make the whole commit in one go, with the original author info preserved), but it is only then that the author is required in the patch file.

So I hadn't fully understood the build process, but I'm pretty sure it remains useful to have the patches with the minor fix (thanks!), so that `git am` can also be used to apply them, if someone wants to.
