### ISSUE TITLE
[OpenDuet] where is the list of included UEFI drivers?

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1268]
Recent entry in Changelog mention eviction of HiiDatabase.

**Comment by vit9696** [comment]
Current list can be found [here](https://github.com/acidanthera/OpenCorePkg/blob/master/OpenDuetPkg.fdf). We can add it to the documentation, but I really wonder how useful it is for the end user as most of the drivers are UEFI-specific and are hardly meaningful without the understanding of what EDK II or our drivers do. Why do you need this informatio?

**Comment by nms42** [comment]
I am hunting nice (hard to catch) bug with legacy stuff. Mostly dead ps2 keyboard on my notebooks. Sometimes RSOD (Read Screen Of Despair) with exception 6.

**Comment by vit9696** [comment]
Yes, got it. With PS/2 stuff we made the drivers external to Duet for easier debugging. The primary source for locating the devices is OvmfPkg/SioBusDxe/SioService.c itself, but I guess in your case the issue is likely with the driver itself.

Since README for the Legacy directory does point to fdf I would assume that as a reference to the drivers included. While it technically can be improved, I do not believe it is going to be a lot more practical to copy-paste names from fdf anywhere.
