### ISSUE TITLE
LegacyBoot: BOOT MISMATCH or not BOOT MISMATCH?

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#1269]
1) Is the OpenDuet part of core OC or Tools|Utilities?

2) OpenCorePkg/Legacy/README.md mention 0x9000 as the location for boot1, while code use 0xE000.

3) Check for BOOT1_MAGIC looks at the first bytes of boot1 memory, while the magic is the very last bytes (+254 missing?)

**Comment by vit9696** [comment]
1. OpenDuet is part of OpenCore package, but it is not part of OpenCore itself. There is no such thing as OpenCore Utilities package, but you can install OpenDuet via an utility.

2. Fixed in https://github.com/acidanthera/OpenCorePkg/commit/4f9394cabb8aa619f5eead27542e0743f2d0fd3a

3. This is handled by BOOT1_LOADER structure. It has LoaderCode and Signature fields for the front memory prior to Magic.
