### ISSUE TITLE
WhateverGreen: getFrameBufferBaseAddress methods are not available in BigSur

### ISSUE THREAD

**Issue by shantur** [acidanthera/bugtracker#1310]
While debugging GPU passthrough on ESXi on MacPro6,1 I found that the methods in https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/kern_rad.hpp#L141 are not available in BigSur and leads to 

```
2020-11-19 08:39:02.921873-0800  localhost kernel[0]: (Lilu) WhateverGreen       rad: @ (DBG) failed to find __ZN28AMDRadeonX4000_AMDVIHardware25getFrameBufferBaseAddressEv code 2
```

This might break some GPUs.

**Comment by vit9696** [comment]
I do not quite understand how did you get this log entry. Please provide a full log via liludump=60 -liludbgall (will be saved to /var/log/Lilu_x.x.x.txt 60 seconds after booting). You may increase the timeout if your machine takes longer to boot.

If you check `RAD::init` it calls `initHardwareKextMods`. This function will set `maxHardwareKexts` to `MaxRadeonHardwareCatalina`,  since Big Sur has higher kernel version than Catalina (20 vs 19), and thus `maxHardwareKexts != MaxRadeonHardware` will evaluate to `true`. This means that all the X4000 framebuffers will be nulled in the loop below (`getFrameBufferProcNames[IndexRadeonHardwareX4000][i] = nullptr`). Therefore this your code should never execute with the latest WEG on Big Sur.

**Comment by shantur** [comment]
You are correct. It was a typo at my end.
Sorry for the trouble.
