### ISSUE TITLE
OpenDuet fails on Acer Aspire 5749

### ISSUE THREAD

**Issue by anirudhb** [acidanthera/bugtracker#1338]
On acer aspire 5749 (i3-2330M) OpenDuet fails to load OpenCore. Prints `BOOT MISMATCH!` then `BOOT FAIL!` and then stalls.

USB created using createinstallmedia (Catalina) and then running `BootInstall_X64.command`. Tried both debug and release but got same error. Was also unable to chainload MBR from an existing GRUB installation.

I definitely feel like this is a Duet bug since somehow it is able to find the USB up until the BDS stage which cannot find OC, so the USB's contents are definitely accessible.

#952 maybe related.

Edit: Was successfully able to boot into OC with [this boot file](https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2673909)!!

However macOS still can't recognize the usb and it fails with the prohibited sign.

**Comment by vit9696** [comment]
Before the BDS phase OpenDuet is using BIOS I/O, thus it works. Then it uses native USB drivers, which do not work. We have a ticket for implementing BIOS I/O support in OpenDuet (https://github.com/acidanthera/bugtracker/issues/952). CC @Goldfish64 

As for `BOOT MISMATCH!`, there was a ticket which may have been related. We are currently investigating whether the issue is still here, as I actually got a report of a file system contents change causing `BOOT MISMATCH`. I wonder if it may be caused by macOS MS DOS driver issues. CC @roddy20 @Goldfish64 @nms42

**Comment by nms42** [comment]
For the record,
this particular bug is not the bug of usb drivers.

The real bug was recorded in issue #1326. The fix already in sources. All details listed in this issue are manifestation of that bug.
