### ISSUE TITLE
opencore.efi is detected as trojan:win32/Wactac.D4!ml

### ISSUE THREAD

**Issue by mr0zzzang** [acidanthera/bugtracker#1363]
window$ defender antivirus removes opencore.efi automatically.
can its action be justified or ignored?

**Comment by roddy20** [comment]
upload the file to https://www.virustotal.com/gui/ and make your own decision

**Comment by roddy20** [comment]
you can disable window$ defender antivirus, or add some folders to exclusions
btw, what version of file causes the problem? 
https://www.virustotal.com/gui/file-analysis/NWE3MTk0ZTVkYmE5ODA3NTIzN2E0MzJlYmQyZTExNmY6MTYwNzc3MDE3NA==/detection

**Comment by roddy20** [comment]
> window$ defender antivirus removes opencore.efi automatically.
> can its action be justified or ignored?

please attach your copy of the problematic file

**Comment by vit9696** [comment]
Hello,

You are not the first to report about [antivirus compatibility](https://github.com/acidanthera/bugtracker/issues/1347), and I will use this ability to reply in general. First of all, let me make it clear that neither OpenCore [source code](https://github.com/acidanthera/OpenCorePkg), nor OpenCore binaries, which you can download from the [releases page](https://github.com/acidanthera/OpenCorePkg/releases), the [artifacts in the actions](https://github.com/acidanthera/OpenCorePkg/actions), and [Dortania builds](https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true) (unofficial but still safe to use) contain no malicious software (viruses, malware, etc).

Then there are three ways for you to run into such a situation:

1. You downloaded OpenCore from an untrusted source, i.e. the one different from the ones I listed above, and the files you downloaded were actually infected. So far we got no reports about this, and believe this really is unlikely, but in theory we should be aware anyway, and always prefer trusted locations or compile on your own.

2. Your system is infected, and files you download or create become infected. To overcome this you could try checking your system from a different known-to-be-safe system with a trusted virus removing software, like [Kaspersky Virus Removal Tool](https://www.kaspersky.com/downloads/thank-you/free-virus-removal-tool). It will identify the malware on your system, remove it, and afterwards you will be able to redownload OpenCore.

3. This is just a false positive. Such things happen, and in the attempt to heuristically detect malware, antiviruses often end up flagging legit files as malicious. In this case you should simply add this file to exceptions. There are [how-to guides](https://www.howtogeek.com/671233/how-to-add-exclusions-in-windows-defender-on-windows-10/) on the network explaining how to do it for different products. You can additionally report about a false positive to the vendor to make it fix the error. Here is [an example how](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives) for Windows Defender.

How to reduce the impact:

- Download from the trusted sources mentioned above.
- Compare file hashes of the flagged files with separately downloaded files from the same location on a different system, [example guide](https://www.spaceclick.com/blog/how-to-calculate-hash-md5-sha1-sha-256-crc32-in-windows-linux-mac-and-online/).
- Enable vaulting and secure boot (refer to Configuration.pdf for more details). In this case if OpenCore becomes infected, they will protect you from loading this file.

Also, just as @roddy20 said, we need the flagged file for analysis, because currently we are unaware of any false positives with Windows Defender.

**Comment by vit9696** [comment]
Just in case, I submitted the latest `OpenCore.efi` X64 file from 0.6.4 RELEASE to M$, and they confirmed that there is no detection with the latest version of the databases. I think there was some bug on the M$ side, which should be hopefully be resolved:

<img width="1988" alt="1" src="https://user-images.githubusercontent.com/4348897/102014956-aee47400-3d69-11eb-8d6c-c6a2b14caf65.png">
