### ISSUE TITLE
Feature Request: Merge NoTouchID into RestrictEvents

### ISSUE THREAD

**Issue by stevezhengshiqi** [acidanthera/bugtracker#1404]
Thanks to all the hackintosh developers who contribute to this community.

Just a suggestion, I see RestrictEvents is able to block unwanted processes, and is it possible to add [NoTouchID](https://github.com/al3xtjames/NoTouchID) functionality? NoTouchID is used to prevent lag in authentication dialogs when the user chooses a Touch ID SMBIOS model. It's handy for 9/10th Gen laptop users. @al3xtjames

**Comment by vit9696** [comment]
I don't know if it is possible, closing as out of the scope.

**Comment by al3xtjames** [comment]
I don't think this is feasible. It's been a while since I've looked at it, but I believe the Touch ID check is handled in BiometricKit.framework. There isn't a standalone binary which handles it, unlike the memory/expansion slot warning applications. Blocking the framework path doesn't appear to work (it's probably present in the shared cache as well).

Regardless, 10.15.7 and above appear to resolve the authentication dialog hang. You shouldn't need NoTouchID on these recent versions of macOS.
