### ISSUE TITLE
Battery works fine until it gets to 100% and takes a while to stop charging

### ISSUE THREAD

**Issue by Xpl0itU** [acidanthera/bugtracker#1425]
Battery works fine, but when it gets to a 100% and you unplug it, it gets stuck at that percentage and doesn't exit charging mode, it can be fixed by putting the computer into sleep and then waking it up. Also, if it's at another percentage and you unplug it or plug it, it takes a while to recognise it's charging or not.

Everything is up-to date, always happened to me since I installed macOS, it doesn't happen in other OS's or if I use ACPIBatteryManager

**Comment by zhen-zen** [comment]
Please attach ACPI dump and the log from debug binary. The driver will stop polling battery status after charged to conserve power. So it will wait for notification of adapter disconnect and start polling again. On some models, corresponding `_Qxx` implementation might be problematic and won't trigger the notification.

**Comment by Xpl0itU** [comment]
[ACPI Dump](https://we.tl/t-FiIzV2w6hY)

**Comment by zhen-zen** [comment]
Please attach the log from debug binary since it's useless just looking into the DSDT. Also your ACPI dump is not complete, you may consider `SysReport` documented in OpenCore manual. Typically there're sound effects when the adapter is plugged in or unplugged, which could be another indicator for those `_Qxx` events.

**Comment by vit9696** [comment]
Closing since this is looks like a configuration issue in ACPI. Reopen if a bug in SMCBatteryManager is found.
