### ISSUE TITLE
Change the disklabel text color

### ISSUE THREAD

**Issue by btwise** [acidanthera/bugtracker#1442]
The new version of OpenCore supports the picker interface background image, which is very good, but if use a light background image, such as a white style, it will make the default white text of the disk label not clear. Is there any way to change the text color of the disk label?

**Comment by 1alessandro1** [comment]
@vit9696 
Maybe it could be implemented something in the `Misc` section to change text color from White to Black or assign a custom hex value to target a specific font color?

**Comment by vit9696** [comment]
Disk label text is chosen based on the luminance calculated from the `BackgroundColor` NVRAM variable. The fact that you have white text on white background means that your `BackgroundColor` is not correct, i.e. black. Detecting text colour (just) from the background image is unreliable, since it can have many colours in different places, and for this reason it is unused. CC @mhaeuser

**Comment by btwise** [comment]
> @vit9696
> Maybe it could be implemented something in the `Misc` section to change text color from White to Black or assign a custom hex value to target a specific font color?

This feature should be available, because since background images are available, the disk label color should be a custom color
