### ISSUE TITLE
[Question] Failed to open OpenCore image - Access Denied

### ISSUE THREAD

**Issue by badstorm** [acidanthera/bugtracker#1446]
Hi, I have a fully working OC 0.65 configuration on my Surface Pro 7. But with the last Surface UEFi Firmware update that introduce"_Addresses security updates and improves system stability_" I cannot load OC any more. As you can see in the screen attached, I get the error `Failed to open OpenCore image - Access Denied`

Whats dose this error means? Have any suggestion to apply to my configuration?

You can find the full configuration [here](https://github.com/badstorm/surface-pro-7-opencore)

Thanks

![104876486-c7761a00-5925-11eb-9b80-fd2b2109e0be](https://user-images.githubusercontent.com/230256/105073898-f99f8d00-5a87-11eb-8468-1f25bad21186.jpg)

**Comment by vit9696** [comment]
Incompatible booter file.

**Comment by badstorm** [comment]
Thanks for you reply. So is a problem related to the UEFI Firmware or a wrong OC configuration or corrupted file?

**Comment by vit9696** [comment]
Outdated BOOTx64.efi I believe.

**Comment by Xiashangning** [comment]
No, sir. Even if I managed to use grub to boot OC, OC did boot and I can choose to boot macOS, however, then the booting process stops at  [EB|#LOG:EXITBS:START]. It seems that OC failed to hand over the system to macOS (I have tried all the possible combinations of quirks of Boot and Kernel , and yet it refused to boot macOS. OC can boot other operating system like ubuntu and manjaro though) So that's it, don't know if this is a problem of compatibility

**Comment by vit9696** [comment]
I can investigate access denied later, will post the test builds. But Exit BS line means the kernel started and died before console. So boot failures are your configuration issues.

**Comment by vit9696** [comment]
@badstorm I checked the code, and can confirm that there is nothing wrong in OC on the first screenshot. The path looks confusing, but this is because the actual path used for OC loading is not printed. I fixed that in https://github.com/acidanthera/OpenCorePkg/commit/68de5dbd705ff24b3c43320cd91785da952bceaf.

The error says that your UEFI firmware refuses to load OpenCore.efi image for whatever reason. This might be enforced by some sort of UEFI Secure Boot policy. Probably unrelated, but I have just added page protection compatibility to OC (https://github.com/acidanthera/OpenCorePkg/commit/171bb05e08d149c7e67fc5aa3ed0017c7c39434c) in case the firmware supports it. I would not have many hopes, but there still is a small chance that your new firmware no longer supports binaries with low alignment. For this reason it may be worth trying the new build.

**Comment by badstorm** [comment]
Thanks @vit9696 for your support. We try to investigate if there is a workaround.

**Comment by Rahanur105** [comment]
![47486A4B-E407-4E3B-AC1D-2884D5B52138](https://user-images.githubusercontent.com/67011679/178156767-258e8392-3aa5-4817-9d72-f3dfe8cfb9c6.jpeg) please help me

**Comment by mikebeaton** [comment]
@Rahanur105 - This doesn't seem to be connected to the original issue? In which case it would be a new issue. But is also looks like a configuration issue, not any kind of bug in OpenCore or ancillary tools, therefore please use [forums](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/FORUMS.md) for support.

**Comment by linhuizhang** [comment]
![IMG_1222](https://user-images.githubusercontent.com/124411983/221952330-c330f34e-6db3-4666-b8bf-f3e35c81888d.jpg)
[error.txt](https://github.com/acidanthera/bugtracker/files/10853865/error.txt)
[normal.txt](https://github.com/acidanthera/bugtracker/files/10853866/normal.txt)

Any version has been tested, and you must shut down and restart several times or once after being stuck in the error code to enter the boot interface

**Comment by toxicxfate** [comment]
Why am I getting this critical error? 

12:785 00:012 OC: Starting OpenCore...
12:798 00:012 OC: Found previous image, aborting
12:811 00:012 OCM: Failed to start image - Already started
12:823 00:012 BS: Failed to start OpenCore image - Already started
