### ISSUE TITLE
Docs: Improve wording for 'Optional:'?

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1459]
On p.57 of the current `Configuration.pdf` we see four sections described as either "Optional: When Automatic is true" or "Optional: When CustomMemory is false".

I found this wording quite misleading, since I would have strongly expected the wording after "Optional:", as currently written, to be describing when the sections _would_ be used, but in fact it describes when they would not be used.

Perhaps the wording could be changed to something like "Optional: Ignored when Automatic is true", etc., so that it is unambiguous?

If you agree, I would be happy to make a quick PR for this change.

**Comment by vit9696** [comment]
It is a second time these lines are found confusing, although I hardly find them to be. It reads "<this entry is> optional: when Automatic is true". Still, I do not see much point to stick with the original version. Replaced optional with ignored, I guess it makes things clear.

**Comment by Bmju** [comment]
While fixing my config based on your [comments elsewhere](https://github.com/dortania/Opencore-Legacy-Patcher/issues/51), I realised that the presence of these four optional/conditionally ignored sections is not required by `ocvalidate` at all - which surprised me!

If these entire sections are optional in this stronger sense, 'do not have to be present at all in circumstance x', then the new updated wording does not reflect this - apologies! (I can indeed see how the original wording was designed to reflect exactly this, but it was/is genuinely a reading of those words which still does not come at all easily to a native English speaker!)

Perhaps the wording could/should be: "Optional: Not processed and need not be present when `Automatic` is true", etc.

I believe fuller wording is required to get the full sense across.

Separately - if I'm not misunderstanding, shouldn't `ocvalidate` be enforcing the presence of these sections, at least when required? Currently, their presence is not required by `ocvalidate` _at all_, which is what made me realise the stronger sense in which they are optional. Perhaps `ocvalidate` should also enforce their absence when not required (in which case "need" in the above text should be replaced by "should", instead).

(Again, and as ever, I am happy to contribute on any of this work (ocvalidate, or the .tex and build) if it is considered worth doing, and (only) if it would be quicker than yourself doing it. 🙂 🙏 )

**Comment by vit9696** [comment]
I changed the docs to be more clear once again, although I am getting rather unhappy of this, as it was fairly clear previously if read properly. Anyway, let's assume it is better now. Regarding your points:

* `Generic` must always be present.
* When Automatic is enabled, `PlatformNVRAM`, `SMBIOS`, and others can be removed.
* All sections, when present, must have all the entries.
* ocvalidate has some design limitations due to underlying parsing logic. It cannot check these sections reliably, and making it do this will likely overcomplicate and/or slowdown primary config parsing code.
* Expecting ocvalidate to find all the mistakes is a bad idea, although it is really nice thx to @PMheart.

**Comment by Bmju** [comment]
Many, many thanks, this is perfect!
