### ISSUE TITLE
Issue Generating Valid MacPro7,1 SMBIOS Serials With macserial

### ISSUE THREAD

**Issue by EightBitBoot** [acidanthera/bugtracker#1466]
I'm not sure the exact right place to post this bug, but macserial was incoperated to the main OpenCore project, and this seemed like the closest type of issue.

I have tested over 50 MacPro7,1 serials with Apple's coverage checker and have not come up with a single one that is valid (claimed or unclaimed).  This was done using the [GenSMBIOS ](https://github.com/corpnewt/GenSMBIOS) batching tool.  I believe there is a bug with the serial generation for this particular SMBIOS, especially since the same serial was generated twice in a batch of 20.

When using macserial directly, "Warning: arc4random is not available!" is printed before the serials are printed.  Checking the code at macserial.c:135, this means that a limited random algorithm must be used.  I'm not sure if this is the issue, or the problem lies with a lack of wiggle room between serials of the same device.  Year and week seem to vary appropriately, but manufacturing location never seems to, which may have moved since the program was updated.  Another thing I'm curious about is if there is a difference in the product code sections between different configurations of the MacPro.  I don't have access to any authentic MacPros so I don't know enough about what their valid serial numbers look like or where they're manufactured.

**Comment by vit9696** [comment]
I believe the fact you got the same serial twice is inside GenSMBIOS, as it actually calls macserial multiple times instead of specifying the count, causing worse randomness. As for failing to generate a serial, specifying a week and a year usually helps. The thing is not meant to be easy even with macserial, but for the good you do not strictly need to set a valid serial.
