### ISSUE TITLE
Clarity Needed on Failsafe Values

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#1473]
Many items in the docs such as `DevicePathsSupported` have the indicated failsafe as being "Not Installed". This doesn't give useful information to someone trying to find out what value to use for that key. 

What exactly does "Not Installed" mean and how do you set the key to that status? Seems to suggest you should omit that key but OcValidate moans at you if you do. Since that example takes integers, then the documented failsafe should be something like "0 (Not Installed)" or whatever is applicable.

Same applies to items such as `BoardType` indicated as `OEM specified`. "0 (OEM specified)" perhaps?

**Comment by vit9696** [comment]
Hello,

I partly disagree with the claim. For example, with `DevicePathsSupported` the spec explains more or less clearly what the value means:

```TeX
  Must be set to \texttt{1} for AppleACPIPlatform.kext to append SATA device paths to
  \texttt{Boot\#\#\#\#} and \texttt{efi-boot-device-data} variables.
```

- If you need to use SATA device paths (and quite certainly do), the value must be set to `1`.
- Not installed means that the property is not installed, i.e. its value is not written to DataHub. Zero (`0`) here actually means not installed as well since macOS only cares for non-0 options.
- If there is an OEM-specified value, then it will be used unless the whole protocol is reinstalled.

Really the same thing applies for `BoardType`, but in this case it cannot really be "not specified", since SMBIOS has a fixed binary structure that always includes this value (no matter what it is).

I do not mind a PR making it clearer by using `0 (Not Installed)` and `0 (OEM specified)`.
