### ISSUE TITLE
OpenCanopy: Does not support one APFS .VolumeIcon.icns path supported by Apple boot picker

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1493]
This relates to #1270 - if I understand correctly that was resolved by adding a useful, non-Apple feature; this is to point out that a comparable Apple feature exists which OpenCanopy does not support.

Speaking in terms of mounted paths within Big Sur, three paths are relevant.

1. `/System/Volumes/Preboot/`
2. `/System/Volumes/Preboot/--GUID--/`
3. `/System/Volumes/Data/`

- `.VolumeIcon.icns` in 1 is seen by the Apple bootpicker and by OC
- `.VolumeIcon.icns` in 2 is seen by OC only (and when present overrides 1, which seems sensible)
- `.VolumeIcon.icns` in 3 is seen by Apple bootpicker only (but is overridden by any icon in 1, which seems less sensible, but is how it is)

3 seems to be the new Apple supported way, noting particularly that a symlink is provided by default at `/.VolumeIcon.icns -> System/Volumes/Data/.VolumeIcon.icns` (see e.g. this [link](https://bombich.com/kb/ccc5/macos-big-sur-known-issues#finder_custom_vol_icons)); also that 3 can be more easily modified, using `sudo` only, whereas 1 & 2 also require `csrutil disable`.

Since there never seems to be any particular opportunity to say so, by the way, many thanks for all your incredible work on OpenCore!

**Comment by vit9696** [comment]
This looks like trash, because Data volume is inaccessible before it is decrypted when FV2 is enabled. The picker can only access the Preboot volume at that time, thus the "new" supported way is plain broken. The icon must be on Preboot, where it should be copied to from any supported location. Perhaps automatically with some tool.

Since our opinion is that everyone should use FV2 by default, I cannot imagine us adding support for this feature. It simply is impractical to implement one wrongdoing to then reimplement it with another. The bug mentioned over your link also makes me think the feature is rather borked.

In my opinion, check whether a new PATH appears when FV2 is on, and if it does not (which I am quite sure how it behaves), file a bug report at Apple, explaining the issue and suggesting our way.

**Comment by Bmju** [comment]
I don't use FileVault (yes if someone nicks my computer they can read my files); you are 100% right that this Apple supported way doesn't work well - on Apple's own Preferences/Startup Disk it only shows the OS icon installed in this way for the current Apple OS, even if that and the other Apple OS both have unencrypted data volumes. )I don't have a picture to show as I don't have two macOS's at the moment.) (FWIW, I've just double-checked this, and even when it does show an image, that Apple Preferences/Startup Disk tool also only shows the image from method 3, not even method 1 - possibly slightly interesting, but also very unimportant, I genuinely agree!)

So, I agree. I understand that and why this Apple feature cannot be implemented in OC also that and why your feature is better, both in being properly detectable and in having the override the way round you would want it!

AFAIK this issue is the only place that this documented, though. Would it be okay if I make a PR adding one line, briefly saying that and why this Apple method is not supported (i.e. copying and editing down just a few of your words from your comment above) at the relevant place in Configuration.pdf?

**Comment by vit9696** [comment]
Sure, makes sense to me.

**Comment by Bmju** [comment]
FYI I just did the last remaining obvious test and turned on FileVault 2 on my machine - and of course Apple's own boot picker cannot and does not show the icon from their new 'recommended' location once FV2 is turned on either. (Though still as predicted showing it, for the current OS only, in the Startup Disk tool, once inside the OS.) Jesus! Shambles! I will do the PR.
