### ISSUE TITLE
Use OEM values as failsafes for Apple-specific SMBIOS properties

### ISSUE THREAD

**Issue by cdf** [acidanthera/bugtracker#1506]
I've been following the recent developments regarding OEM values in automatic mode and I thought I'd raise an issue for manual mode.

On Apple hardware, manual mode is useful for doing minor SMBIOS adjustments. However, any such adjustments require specifying all Apple-specific properties: `PlatformFeature`, `SmcVersion`, `FirmwareFeatures`, `FirmwareFeaturesMask`, and `ProcessorType`. The reason is that these properties do not currently use OEM values as failsafes. Although `PlatformFeature` and `SmcVersion` may be absent on Apple hardware and `ProcessorType` may be detected with the `0` setting, `FirmwareFeatures` and `FirmwareFeaturesMask` must be specified, even if appropriate values are present in the original SMBIOS.

The decision not to use OEM values as failsafes for Apple-specific SMBIOS properties makes sense in general ([c6e637d](https://github.com/acidanthera/OpenCorePkg/commit/c6e637da83aae62b76772e0ee80d0449eb9a4e26)). But on compatible hardware, it might be worth having the option to extract and use the original values.

**Comment by vit9696** [comment]
The issue with these properties is that they are indeed Apple-specific and thus do not have Apple-reserved IDs. We cannot just take a random SMBIOS table and reuse the Apple-specific tables. They may easily have random data on hackintosh. Doesn't `Automatic` work for you? There were many improvements in this regard not so long ago.

**Comment by cdf** [comment]
I certainly understand that there is an incompatibility with non-Apple hardware.

Regarding `Automatic`: On the Mac Pro 5,1 we use manual mode to change only the `BoardProduct` SMBIOS property. This minor change is sufficient for installing macOS and (as of Big Sur) performing over-the-air updates. With the help of  WhateverGreen, it also enables hardware acceleration. Moreover, it keeps the machine identified as a Mac Pro in Apple Services, a detail that many users appreciate. This minimal configuration has been a winning formula. In fact, other legacy-Mac users have started adopting it. On the other hand, automatic mode does not, to my knowledge, allow for such fine-tuning: `SystemProductName` changes not only the board ID but other identifiers as well (bios version, product name, chassis version, etc., as specified in the model database).

Of course, specifying Apple-specific properties in manual mode is no big deal. An OEM option would just make the minimal configuration that more accessible to other legacy-Mac users.

**Comment by Bmju** [comment]
I am hesitating to come in on @cdf's issue, especially as I have been in a sense arguing 'against' him, only on the details of exactly how best to achieve a clean, lightly spoofed config on a legacy Mac (an overarching goal which I believe we both agree on). So don't take what I say as at all representative of what @cdf might argue.

However, I am coming round somewhat to @cdf's point of view. I perhaps had not appreciated (or had chosen not to look into, since I'd seen the tables in the code!) quite how much is automatically set from the `SystemProductName` if using the `Generic` section.

Just as a for instance, the firmware features settings are - indeed - being set based on the model specified in the `Generic` spec. This is completely correct accoding to current spec, I agree. But obviously it means that if you use that feature to 'lightly' spoof a legacy Mac, your *actual* firmware features are being misreported. (Which I guess may or may not matter, based not so much on what your original firmware can really do, but on what your original firmware with OC on top of it can really do.)

The issue everyone is suddenly wrestling with, is how to fake _enough_ on a genuine hardware legacy Mac to run an unsupported OS - but no more. One approach might be to continue to add yet more features to the Generic section - maybe to acknowledge that there are two reasons for setting BoardProductName, and in one special case, you don't want everything to follow, but maybe just the board id, with the rest being from existing legacy SMBIOS settings (which must, therefore, exist).

Another approach may be to complete what seems to be nearly done already (on re-reading the SMBIOS section docs) and make _every_ setting in `SMBIOS` able to autodetect - at least on legacy Macs; possibly by adding new "OEM" special values (which might look up, e.g., in NVRAM) for those few SMBIOS section values which don't already have a sensible way to get "OEM" values (and which again, of course, would only be valid selections with predicatable behaviour on legacy Macs).

Which would mean far from removing the "misleading" info mentioned in my other [issue](https://github.com/acidanthera/bugtracker/issues/1508), the correct upshot would be to upgrade the wording to unambiguously confirm that this *is* safe, after all (i.e. as it then would be, if the suggested changes were made):

```
  It is strongly discouraged set this option to \texttt{false} when intending to
  update platform information. The only exception is when doing minor updates
  to the SMBIOS section only, which is also intended to be safe. In all other cases
  not using \texttt{Automatic} may lead to hard to debug errors.
```

**Comment by vit9696** [comment]
Basically the correct way to address this is to check if the vendor of the OEM firmware contains Apple, and in this case use the Apple-specific SMBIOS tables (for SMC, for FirmwareFeatures), similarly to how we do with all the non-Apple tables. It may be discussible with the CPU as Apple firmware may not be always able to detect the installed CPU correctly, but for all other cases it should be correct and consistent.

I do not think I can promise to get here reasonably soon, so it is a matter of anybody willing to contribute such a change. Technically speaking, it is a rather simple change, that can easily be crafted based on the existing SMBIOS code, so I do not see much of a problem here.
