### ISSUE TITLE
AppleHDAHDMI_DPDriver loading only after unplug/plug DP cable

### ISSUE THREAD

**Issue by giacomoleopardo** [acidanthera/bugtracker#1509]
- macOS Big Sur 11.2.1
- Asus Prime Z490-P
- Intel i9 10900K
- iGPU enabled with AppleCinemaDisplay (DisplayPort)
- iMac20,2 (waiting for an MSI RX 5700XT which has not arrived yet)

Audio HDMI works only if I unplug then plug back the DisplayPort cable.
Attachments:

- EFI folder
- IOReg (version 3.0.2) with AppleHDAHDMI_DPDriver not loaded (before unplug/plug DisplayPort)
- IOReg with AppleHDAHDMI_DPDriver loaded (after unplug/plug DisplayPort)
- BIOS 1602 settings

[EFI Partition.zip](https://github.com/acidanthera/bugtracker/files/5999396/EFI.Partition.zip)
[IORegs.zip](https://github.com/acidanthera/bugtracker/files/5999400/IORegs.zip)
[bios_setting.txt.zip](https://github.com/acidanthera/bugtracker/files/5999446/bios_setting.txt.zip)

**Comment by vit9696** [comment]
Well, this is likely something in your firmware, but I am afraid we will not investigate it as it is not a direct issue in any of our drivers or anything.

**Comment by LiuLiujie** [comment]
Nearly same problem. I open my hac (H470M-itx i9-10900 iMac20,2 iGPU) with DP connected but there is no AppleHDAHDMI_DPDriver loaded.  Only if I unplug/plug the HDMI to the motherboard and the same monitor, then this Driver loaded.
I try to compile the AppleALC.kext myself and custom the FrameBuffer in config but the problem is still there.
Do you have any solution?
