### ISSUE TITLE
OC boot: 583e56 preventing OpenCanopy entering graphics mode in DEBUG build

### ISSUE THREAD

**Issue by Bmju** [acidanthera/bugtracker#1512]
https://github.com/acidanthera/OpenCorePkg/commit/583e563955b1b2cf494eb72c9ac134bd49c7729c is preventing OpenCanopy from entering graphics mode in DEBUG build.

![2eb81443-7915-4253-993a-bb6ef20f6afd](https://user-images.githubusercontent.com/25643187/108343583-0670e700-71d4-11eb-8c32-9997a2360ada.jpeg)

The actual boot picker is working fine, you can enter and exit tools and select and start an OS, if you know the keys to press. Switching to `Builtin` text mode boot picker, it displays and runs fine.

Simply manually reversing out the changes made to `OpenCorePkg.dsc` in https://github.com/acidanthera/OpenCorePkg/commit/583e563955b1b2cf494eb72c9ac134bd49c7729c rebuilding OC and reinstalling, restores normal behaviour.

MacBookPro10,2 (upgraded Wi-Fi)
[opencore-2021-02-18-101729.txt](https://github.com/acidanthera/bugtracker/files/6002092/opencore-2021-02-18-101729.txt)
[config.plist](https://github.com/acidanthera/bugtracker/files/6002098/config.plist.txt)

**Comment by vit9696** [comment]
I fixed that, actually the problem was somewhat deeper as OpenCore is supposed to start in any console mode and it is expected to work fine regardless of that nuance. For example, if you start `RELEASE` OpenCore from UEFI Shell (which runs in text mode) it should still show OpenCanopy without issues. That was broken even before https://github.com/acidanthera/OpenCorePkg/commit/583e563955b1b2cf494eb72c9ac134bd49c7729c, but should now be fixed.

**Comment by Bmju** [comment]
I had indeed noticed that that didn't work before, but assumed it was an edge case. Many thanks. (Are the methods in the new fix meant to say `Meny` not `Menu`?)
