### ISSUE TITLE
XhciPortLimit broken in macOS 11.3 Beta 2(20E5186d)

### ISSUE THREAD

**Issue by khronokernel** [acidanthera/bugtracker#1514]
When updating to macOS 11.3 Beta 2(20E5186d), the machine will boot loop due to issues with the USB drivers. Below log includes multiple boot loops:

* [CoolTerm Capture 2021-02-18 12-20-31.txt](https://github.com/acidanthera/bugtracker/files/6005395/CoolTerm.Capture.2021-02-18.12-20-31.txt)

```
17:126 00:040 OCAK: Patching invalid size 8F000 with F80000 for com.apple.iokit.IOUSBHostFamily
17:135 00:008 OCAK: 64-bit RemoveUsbLimitIoP1 replace count - 1
17:141 00:005 OCAK: Patch success port com.apple.iokit.IOUSBHostFamily
17:150 00:009 OCAK: Patching invalid size 4D000 with DEA000 for com.apple.driver.usb.AppleUSBXHCI
17:159 00:008 OCAK: 64-bit RemoveUsbLimitV2 replace count - 1
17:165 00:006 OCAK: Patch success com.apple.driver.usb.AppleUSBXHCI
17:174 00:009 OCAK: Patching invalid size 29000 with D94000 for com.apple.driver.usb.AppleUSBXHCIPCI
17:183 00:008 OCAK: Skipping legacy port patch AppleUSBXHCIPCI on 200400
```

Additional files:

* macOS 11.3 Beta 1(20E5172i):
  * [AppleUSBXHCI-20E5172i(11.3B1).zip](https://github.com/acidanthera/bugtracker/files/6005526/AppleUSBXHCI-20E5172i.11.3B1.zip)
  * [AppleUSBXHCIPCI-20E5172i(11.3B1).zip](https://github.com/acidanthera/bugtracker/files/6005528/AppleUSBXHCIPCI-20E5172i.11.3B1.zip)

* macOS 11.3 Beta 2(20E5186d):
  * [AppleUSBXHCI-20E5186d(11.3B2).zip](https://github.com/acidanthera/bugtracker/files/6005440/AppleUSBXHCI-20E5186d.11.3B2.zip)
  * [AppleUSBXHCIPCI-20E5186d(11.3B2).zip](https://github.com/acidanthera/bugtracker/files/6005441/AppleUSBXHCIPCI-20E5186d.11.3B2.zip)

**Comment by ghorwith** [comment]
Had same issue. Found 2 ports that worked with hardwired KB and Mouse, but otherwise ports are borked

**Comment by vit9696** [comment]
Checked the patches. The code changes apply fine and the patched code did not change. It is macOS itself that got changed (somewhere, perhaps even outside the driver) resulting in the patches no longer functioning correctly. This may well be because of the incorrect location ids.

Given the overall discourage of the approach to patch USB ports, I think it is about the time to abandon these patches. At least by the core team, until anybody provides a better set.

@khronokernel please upload a complete IOUSBHostFamily.kext or maybe even the whole `Extensions` set from b1/b2 in case anybody wants to debug this some day.
