### ISSUE TITLE
BootPicker: Keyboard loop design makes certain picker features difficult/impossible

### ISSUE THREAD

**Issue by ghost** [acidanthera/bugtracker#1526]
Am I correct in understanding, mainly from how it behaves, that the current keyboard part of the bootpicker keyboard and animation loop:

 - Pauses everything until a key (or the last key of a chord) is released
 - This includes control keys

Side effects:

 - ESC to enter OpenCanopy GUI pauses at apparently blank screen (actually, very first frame of GUI fade in) until ESC is released
 - When selecting an OS with CTRL+Enter, there is no way (because no animation frames are happening) to change the select arrow to a round arrow while CTRL is pressed (as in Apple bootpicker)
 - Also when selecting an OS with CTRL+Enter, nothing happens after Enter is released, but only after CTRL is also released (which, while not obvious until you use it, is not normal/standard keyboard behaviour, which would be to take the action as soon as the Enter key is released)

An ideal keyboard loop, I suppose, would:

 - Detect all control keys separately, e.g. as (semi-?) global flags, very roughly something like `mIsShiftDepressed`, `mIsCmdDepressed`, etc. (therefore never waiting for these to be released)
 - Still only report the result of a key-press (or key-chord) after the last key is released
 - Not pause while waiting for keys to be released (just immediately return each time called, if no key action is ready yet)

I am not specifically aware of the issues in attempting to do something like this in a way which would work in all EFI BIOSes. It seems it must be possible at least in newer, Apple BIOSes, since the Apple bootpicker itself must be doing something like this. But agreed that wide - essentially global - compatibility would be required.

Would it be agreed that the issue I'm mentioning is real, and that something roughly along the lines of the solution mentioned is needed, to 'fix' it - though purely in order to get nicer animation, etc. in bootpicker?

If so, I would be interested in looking at it - if that would be of any interest, and esp. obviously, if no one else already is. If that would be welcome, I'd be glad, but it would be, probably (and depending on your feedback), more in an 'in due course' manner rather than in a 'PR within the next few days' manner!

**Comment by vit9696** [comment]
You are right, currently OpenCanopy gets less attention than desired. Can you write us in matrix? Use https://element.io to join. My nickname is @vit9696:matrix.ispras.ru and @mhaeuser's is @download-fritz:matrix.ispras.ru. Since OpenCanopy is mostly his toy, you would need him more.

**Comment by mhaeuser** [comment]
To be perfectly honest, OpenCanopy is kind of an unloved child right now. I wrote the current loop completely without events in mind (it worked solely based on the UEFI protocols), and it worked very much fine for me and my testers. @vit9696 discovered some issues with this approach on other machines, and because we both were on heavy time constraints, he just implemented event-based I/O into the existing design. Truth is, none of us really know how it should work right now. :)

There is an entire stack of questions to be answered for this. The first one probably is, whether or not we should stick to events in the first place, as done now (pros: works like FV2 and friends, less internal code, ...; cons: events may be broken, we have to deal with control flow interruptions, ...). If we don't, there will need to be code for things like pointer acceleration based on the GUI loop timer ticks (should still be using TSC now). If we do, there might be code needed to better integrate the events into the control flow, as it was never really intended for this. And so on...

As @vit9696 said, I would prefer some direct conversation over GitHub text walls. Results can be shared afterwards of course.

**Comment by MikeBeaton** [comment]
Closed by https://github.com/acidanthera/OpenCorePkg/pull/238
