### ISSUE TITLE
cannot boot with OpenCanopy

### ISSUE THREAD

**Issue by btwise** [acidanthera/bugtracker#1546]
With the latest 0.6.8 version of OpenCanopy, the system cannot be booted. black screen is stuck, but use `builtin` text mode can be used to boot normally

**Comment by btwise** [comment]
When the GUI menu appears, select any startup item, and the screen is black because the enter is blocked, so the startup cannot be started, but everything is fine with 0.6.7 OpenCanopy
Use the DEBUG version to get the boot log!
[opencore-2021-03-04-050254.txt](https://github.com/acidanthera/bugtracker/files/6081736/opencore-2021-03-04-050254.txt)
CPU:I5-6400
ASUS B150-PLUS
AMD RX470
KINGSTONE A2000 HD

**Comment by vit9696** [comment]
Provide commit it happened.

**Comment by vit9696** [comment]
Also attach the EFI directory.

**Comment by btwise** [comment]
> Also attach the EFI directory.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/6082749/EFI.zip)

**Comment by vit9696** [comment]
Right. When can you provide the commit hash that actually causes the regression on your side? The issue is not reproducible here so far.

**Comment by btwise** [comment]
> Right. When can you provide the commit hash that actually causes the regression on your side? The issue is not reproducible here so far.

I don't understand what information you need, but I only need to replace the OpenConopy.efi file of 0.5.7 and it can boot normally!

**Comment by vit9696** [comment]
Next time instead of silently ignoring stuff please make sure to ask questions. It will save both your and our time.

The basics is that there is no such thing as 0.6.8 yet, therefore there only are beta builds made on per-commit basis. I.e. when something breaks we need to know which exact change broke it. That is done by testing older builds one by one and then finding the change that resulted in the failure for you.

If you cannot build older OpenCore 0.6.8 versions by yourself you can use Dortania's third-party build server: https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true. What we need from you is to determine the last (top-most) version that worked for you and the first broken version (usually right above the last working one).

Unfortunately currently it does not list all the builds from 0.6.8 branch due to a minor issue on Dortania's side. Once this is addressed the builds will appear on the list and you can then do the tests. @dhinakg will reply to this issue to inform you about it.

**Comment by btwise** [comment]
The problem does not occur after the boot, but after the GUI selector determines that the next action cannot be taken, whereas the text mode menu can be booted normally

**Comment by vit9696** [comment]
This is not very helpful information, as it is contained in the first post. We understood you and explain the further actions in https://github.com/acidanthera/bugtracker/issues/1546#issuecomment-790604604.

In case you want to be helpful before Dortania build server is confirmed fixed, please make sure that you are using DEBUG OpenCanopy.efi. I believe the log you provided is incomplete due to non-DEBUG OpenCanopy.efi. For this reason I request you to generate a new log with a definitely DEBUG version of OpenCanopy. The scenario for the log should be as follows:

1. seeing OpenCanopy
2. pressing enter to boot some option
3. seeing blackscreen
4. waiting for 1 minute
5. rebooting

**Comment by btwise** [comment]
> 这不是很有帮助的信息，因为它包含在第一篇文章中。我们了解您，并在[＃1546（注释）中](https://github.com/acidanthera/bugtracker/issues/1546#issuecomment-790604604)说明了进一步的操作。
> 
> 如果您希望在确认Dortania构建服务器之前有所帮助，请确保您使用的是DEBUG OpenCanopy.efi。由于非DEBUG OpenCanopy.efi，我认为您提供的日志不完整。因此，我要求您使用绝对调试版本的OpenCanopy生成新日志。该日志的方案应如下所示：
> 
> 1. 看到OpenCanopy
> 2. 按Enter键启动某些选项
> 3. 看到黑屏
> 4. 等待1分钟
> 5. 重新启动



> This is not very helpful information, as it is contained in the first post. We understood you and explain the further actions in [#1546 (comment)](https://github.com/acidanthera/bugtracker/issues/1546#issuecomment-790604604).
> 
> In case you want to be helpful before Dortania build server is confirmed fixed, please make sure that you are using DEBUG OpenCanopy.efi. I believe the log you provided is incomplete due to non-DEBUG OpenCanopy.efi. For this reason I request you to generate a new log with a definitely DEBUG version of OpenCanopy. The scenario for the log should be as follows:
> 
> 1. seeing OpenCanopy
> 2. pressing enter to boot some option
> 3. seeing blackscreen
> 4. waiting for 1 minute
> 5. rebooting

Yes, I neglected to use the debug version of OpenCanopy, I will continue testing today

**Comment by btwise** [comment]
After recompiling, the fault disappeared. Please close this issues!

**Comment by miuirussia** [comment]
Downloaded artifact from: https://github.com/acidanthera/OpenCorePkg/actions/runs/622185565 and have same issue, will test later

**Comment by mhaeuser** [comment]
Potentially related to https://github.com/acidanthera/OpenCorePkg/commit/626bb17d6590e48a48d5af584fbdb6bff182ebe6

**Comment by Sher1ocks** [comment]
> Potentially related to [acidanthera/OpenCorePkg@626bb17](https://github.com/acidanthera/OpenCorePkg/commit/626bb17d6590e48a48d5af584fbdb6bff182ebe6)

finally, i can boot. thanks alot:)

**Comment by MikeBeaton** [comment]
@miuirussia Can confirm that the issue was valid and replicated on some machines here. And should be resolved as above.
