### ISSUE TITLE
[HP EliteBook 840 G4] Trackpoint and upper touchpad buttons not working properly

### ISSUE THREAD

**Issue by XXCoreRangerX** [acidanthera/bugtracker#1584]
Hello, I'm using the latest version of `VoodooRMI` and `VoodooPS2` for fixing the touchpad and the trackpoint on my HP EliteBook 840 G4.

This is how I use the kexts:
| Device | Communication | Kext | Does it work |
| ------------- | ------------- | ------------- | ------------- |
| **Touchpad and bottom buttons** | SMBus | `VoodooRMI, RMISMBus, VoodooSMBus` | Yes |
| **Trackpoint and upper buttons** | PS2 | `VoodooPS2Controller, VoodooPS2Mouse` | No - fixes the trackpoint and upper buttons, but breaks SMBus connection |
| Keyboard | PS2 | `VoodooPS2Controller, VoodooPS2Keyboard` | Yes |
| Touchscreen | I2C | `VoodooI2C, VoodooI2CHID` | Yes |

VoodooRMI fixes the touchpad and 2 bottom buttons, but not the trackpoint.

It appears that the trackpoint and upper touchpad buttons are connected via **MUX** (tested on Linux). I [talked to the developer of VoodooRMI](https://github.com/VoodooSMBus/VoodooSMBus/issues/66), and apparently this requires work on the PS2 side. I think it only requires adding **MUX** support to `VoodooPS2Controller`.

**Comment by vit9696** [comment]
Right, the description makes more or less sense to us. On a high level, we need to initialise the MUX device in the PS2 controller driver in a way that SMBus can still interact with the device to enable touchpad support, correct? I guess this is a genuine issue, but I do not think we will take it due to the lack of hardware and developer resources. Feel free to contribute a patch.

**Comment by 1Revenger1** [comment]
From what I understand, the trackpoint and touchpad are two seperate devices. We need to be able to communicate with both devices initially during startup, but then shut down the touchpad to use it over SMBus while still leaving the trackpoint working over PS2. Unlike other laptops which take advantage of PS2 passthrough in the trackpad (so the devices are chained like this: Trackpoint => Touchpad => 8042 Controller), this doesn't. I'm not sure how it currently works using just VoodooPS2 tbh, as I'd think there would be some conflicts or other weird behavior.

I may take a stab at this sometime in the next few days.

**Comment by 1Revenger1** [comment]
I've got a rough draft here https://github.com/1Revenger1/VoodooPS2/tree/mux
I do want to PR it into VoodooPS2 here once it's been tested.
Currently it does detect the two devices, though the one person I've had test it has two trackpads appear rather than a generic PS2 mouse (trackpoint) and trackpad. Few quinks to still be worked out. Trackpad works with this, not the trackpoint though.
![image](https://user-images.githubusercontent.com/13190749/129460269-805be30f-0cc2-4994-b22e-a0d79a8df915.png)
