### ISSUE TITLE
[WhateverGreen] BusID Patching clarifications

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1611]
Hi,
sorry in advance if this isn't the right place where to ask. The reason why I opened an issue there is that is related to WhateverGreen (so acidanthera's team work).
The way to map an Intel mobo video outputs, is using WhateverGreen BusID patching.
With this procedure, you can easily map each connector (change BusID and connector type). For a more detailed procedure, check [dortania's guide](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html).

My question is: given that we wanna disable a connector, what's the safest way to do it? Should we set the connector's BusID to `00` or set `framebuffer-conX-enable` to `DATA` `00000000` and perhaps remove `framebuffer-conX-alldata`?

Thank you so much and have a nice day

**Comment by Andrey1970AppleLife** [comment]
Look here as disable connector 2.
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/AzulPatcher4600_equivalent.plist#L21-L24

**Comment by dreamwhite** [comment]
> Look here as disable connector 2.
> https://github.com/acidanthera/WhateverGreen/blob/master/Manual/AzulPatcher4600_equivalent.plist#L21-L24

Alright, then from what I read the way to to disable a connector, should be:

- `framebuffer conX port number` set to `FF`
- `framebuffer conX busid` to `00`
-  `framebuffer-conX-enable` to `01000000`

Right?

**Comment by 1alessandro1** [comment]
> Look here as disable connector 2.
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/AzulPatcher4600_equivalent.plist#L21-L24

Hi, since I only have I integrated display (eDP/LVDS) and 1 HDMI port, I've tried to disable the additional default port which is the following from the WeG docs:


```
ID: 3EA50009, STOLEN: 57 MB, FBMEM: 0 bytes, VRAM: 1536 MB, Flags: 0x00830B0A
TOTAL STOLEN: 58 MB, TOTAL CURSOR: 1 MB (1572864 bytes), MAX STOLEN: 172 MB, MAX OVERALL: 173 MB (181940224 bytes)
Model name: Intel HD Graphics CFL CRB
Camellia: CamelliaV3 (3), Freq: 0 Hz, FreqMax: 0 Hz
Mobile: 1, PipeCount: 3, PortCount: 3, FBMemoryCount: 3
[0] busId: 0x00, pipe: 8, type: 0x00000002, flags: 0x00000098 - ConnectorLVDS
[1] busId: 0x05, pipe: 9, type: 0x00000400, flags: 0x000001C7 - ConnectorDP
[2] busId: 0x04, pipe: 10, type: 0x00000400, flags: 0x000001C7 - ConnectorDP
00000800 02000000 98000000
01050900 00040000 C7010000
02040A00 00040000 C7010000
```

Taking this values into account:


```
00000800 02000000 98000000
01050900 00040000 C7010000
02040A00 00040000 C7010000
```

I've replaced the BusID for port 1 for HDMI (00080000) to work to "01":

-con0 (default): 00000800 02000000 98000000
-con1 (edited): 01**01**0900 000**8**0000 C7010000
-con2 (default): 02040A00 00040000 C7010000

Now to disable port 02, I've tested two configurations expecting the port to disappear from ioreg:

# First configuration:
-con0 (default): 00000800 02000000 98000000
-con1 (edited): 01**01**0900 000**8**0000 C7010000
-con2 (edited): **FF**040A00 00040000 C7010000

And the port is still present in ioreg:

![image](https://user-images.githubusercontent.com/46293832/114928860-60d49f80-9e33-11eb-9051-c68fa2c07b96.png)


# Second configuration:
For port 2, I've replaced completely the lines you mentioned:

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/AzulPatcher4600_equivalent.plist#L21-L24

This is the config.plist:

![image](https://user-images.githubusercontent.com/46293832/114928998-8feb1100-9e33-11eb-87aa-d86a0d9fde82.png)


However the port is still present in IORegistry:

![image](https://user-images.githubusercontent.com/46293832/114929106-aabd8580-9e33-11eb-8943-b7bffccbd49f.png)


Is there a way to remove it or is that out of spec? Does macOS expect 3 framebuffers and cannot accept 2?

**Comment by Andrey1970AppleLife** [comment]
> 
> ![image](https://user-images.githubusercontent.com/46293832/114928998-8feb1100-9e33-11eb-87aa-d86a0d9fde82.png)
> 

Add framebuffer-portcount 02000000

**Comment by 1alessandro1** [comment]
> Add framebuffer-portcount 02000000

Thanks, it worked for my configuration, since I have con0 and con1, and they're coherent with portcount = 2 since they're two ports.

I think that WeG with this parameter counts from 1 (enabling con0 and con1), but a case where this fails could be (I'm asking if this is possible or not) where on some firmware port 1 (con1) may not correspond to a real usable connector while port 2 (con2) exists with the corresponding busid.

If that's the case, when a user specify portcount = 2 and does not have the HDMI output on con1 but on con2, then HDMI won't work since it has been blocked by the progressive counting. Are there any measures against this?
