### ISSUE TITLE
Framebuffer and displays problems

### ISSUE THREAD

**Issue by Dr-Itachi** [acidanthera/bugtracker#1656]
Hi all. I have a serious problem with my displays, ok my main internal display is broken so for the moment I am using my PC externally (HDMI).
1 - when I start my hack I press Fn+F8 (Dell PC) to transfer the video output to HDMI, it works and MacOS starts from my external monitor from Opencore's picker until it is fully loaded I use it without any worries. I'm not sure if it's a good idea to use the same software as the one I'm using on my hp laptop, but once I unplug the HDMI cable and plug it back in, there's no output signal. My internal and external displays are both black, but on my hp it's not.
2-When I boot without switching the output to HDMI, I can't see what is displayed because the internal screen is damaged, but the backlight at least works and the default boot disk is MacOS, so I know that it launches MacOS, but after long minutes of waiting I connect the HDMI cable but no signal is transmitted (on Windows after loading the graphics driver, the monitor automatically receives the signal). I can see on ioreg that the connector is set to HDMI (00080000) I don't know what to do.
Dell Inspiron 5558
i5 5200U
8GB RAM
Intel HD 55OO/Nvidia Geforce 920M
![Capture d’écran 2021-05-29 à 18 06 38](https://user-images.githubusercontent.com/65020150/120079350-4a189e00-c0ab-11eb-8452-3c566c7a5247.png)
![Capture d’écran 2021-05-29 à 18 06 26](https://user-images.githubusercontent.com/65020150/120079351-4d138e80-c0ab-11eb-9102-0757a2c308f4.png)
[MacBook Pro12,1_ioreg.zip](https://github.com/acidanthera/bugtracker/files/6565081/MacBook.Pro12.1_ioreg.zip)

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/6565084/config.plist.zip)

**Comment by vit9696** [comment]
I would say you can try experimenting with the connectors, but you are likely out of luck, sorry.

**Comment by Dr-Itachi** [comment]
> I would say you can try experimenting with the connectors, but you are likely out of luck, sorry.

so there's nothing to do ? i dint think others people around the net with the same Laptop have the same issue. dont know what's wrong

**Comment by MikeBeaton** [comment]
User support not provided in these issue pages - due to constraints of time, resources and correct focus: these issues are for raising and discussing code-level issues, not user config-level issues.

Basically OC is working but something in your config isn't, and no one here is immediately spotting exactly what (though see suggestions for the correct general area from @vit9696 above) - so unfortunately you need to go to Google, Reddit, forums, [Dortania GPU guides](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/#intel-igpu-patching), etc. to clarify exactly what to try next.
