### ISSUE TITLE
Lilu panic: matchSharedCachePath commit evoked panic on 11.2.3 install (via OLCP 0.1.7's included LILU kext)

### ISSUE THREAD

**Issue by ylluminate** [acidanthera/bugtracker#1691]
As explained by @khronokernel the following commit broke support for macOS 11.2.3 installation (and apparently other things): https://github.com/acidanthera/Lilu/commit/1e944292e99817c485e846ab73275521dcbc1ee3

This was experienced with OCLP 0.1.7 and reported here: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/300

**Comment by vit9696** [comment]
This is the incorrect commit that introduced the issue I believe. The real one should be https://github.com/acidanthera/Lilu/commit/c3719856ee6deb195b596d7eb529befc8734931e. You mistook it due to trying incompatible (newer) plugins with older Lilu.

Precondition: test with DEBUG versions of all the plugins from the **release** page, using plugins from master will give you wrong results.

1. Test with Lilu https://github.com/acidanthera/Lilu/commit/c3719856ee6deb195b596d7eb529befc8734931e
2. Test with Lilu https://github.com/acidanthera/Lilu/commit/f159bde09d88692fd8f9d01b80176d5235f20880
3. Test with Lilu https://github.com/acidanthera/Lilu/commit/0fd1b2985f6a2a934c928b4594ba5179e202b31f

1 should panic, 2 and 3 should work fine. I want you to attach the panic log for 1. If 3 is fine, update all your plugin versions to master, and confirm it is still ok.

**Comment by ylluminate** [comment]
Confirmed #3 `0fd1b29` resolves.
