### ISSUE TITLE
[DisableIoMapper] Clarifications

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1738]
Hi there,
I was digging inside my BIOS when I found out that VT-d was disabled. I turned it on and did a quick test without `DisableIoMapper` kernel quirk enabled. The system successfully booted BUT I noticed on IORegistryExplorer that a new entry called `AppleVTD` appeared.
I did some quick research first on Configuration.pdf, then on Google and found out that VT-d can actually be left enabled without having to keep `DisableIoMapper` kernel quirk enabled.

I know that this forum isn't definitely your best buddy, but apparently many people confirmed a working WiFi/Ethernet adapter, as well as with some TB3 peripherals. I'll leave the link of [moneygrabberx86](https://www.tonymacx86.com/threads/gigabyte-z490-vision-d-thunderbolt-3-i5-10400-amd-rx-580.298642/post-2262127) for more infos.
What he/she actually did is removing `Reserved Memory Regions`, and replace the existing DMAR table.

Is this thing useful or can be safely ignored as it may lead to unwanted consequences (like breaking some other system functionalities 😅)?
Please let me know your thoughts on that and eventually if DisableIoMapper kernel quirk can be adapted.
Regards
dreamwhite

**Comment by vit9696** [comment]
Well, DMAR table should protect you from malicious devices doing DMA attacks. In real world examples only Apple sets it up correctly, because their hardware configuration is more or less static. Other vendors pretty much allow any access, making the effects of DMAR not so useful.

AppleVTD aka IOMapper is what is responsible of enforcing DMAR table restrictions. In theory fixing up the DMAR table is better than completely disabling the protection, but the exact modifications need to be observed. Since the original table is almost always trash, and since making something compatible does not equal to making something secure, I would say that it may not be worth the effort.
