### ISSUE TITLE
Buffer early logs to store them in the file and other OcLog targets

### ISSUE THREAD

**Issue by perez987** [acidanthera/bugtracker#1760]
This isn't a real bug and it happens since ever.
OC schema error warnings at boot are displayed for a time too short to be read.
These warnings can be reproduced with the ocvalidate tool on macOS so it is not a major problem.
I know it's always recommended to validate config.plist before restart.
Do you think that can be helpful to display these messages for a longer time or add a message like "Press a key to continue"?
Either way, thank you very much for your work.

**Comment by Andrey1970AppleLife** [comment]
DisplayDelay

**Comment by vit9696** [comment]
`DisplayDelay` will not actually work, since it is applied after the config is read. The text printed by OpenCore regarding the schema is not meant to be read at the time it is printed, it is rather an unavoidable side-effect on some platforms.

However, it should really go to the buffer, and then be copied to the OpenCore log once it is initialised. I thought there was an issue for that, but looks like not. Reopening and using this one. It will not be soon this gets implemented though.

**Comment by perez987** [comment]
Thank you for your comment.

**Comment by PMheart** [comment]
Hello! Sorry for the late response. I believe that this is implemented in https://github.com/acidanthera/OpenCorePkg/pull/327. Please give it a try and reopen the issue if it does not solve the problem.
