### ISSUE TITLE
Opencore hangs with a blank screen, if OpenLinuxBoot.efi is enabled.

### ISSUE THREAD

**Issue by naveenkrdy** [acidanthera/bugtracker#1822]
After POST, the Opencore menu doesn't show up if OpenLinuxBoot.efi is enabled, and I am stuck with a blank screen.

Linux : Manjaro GNOME 21.1.5 (Ext4)
macOS : Big Sur 11.6
Device : Dell XPS 7590
Opencore : 0.7.5 https://github.com/acidanthera/OpenCorePkg/commit/ecceb47e79c55779d95b75c5a244f915c5a03e6e

[opencore-2021-10-15-070821.txt](https://github.com/acidanthera/bugtracker/files/7351603/opencore-2021-10-15-070821.txt)

Thanks.

**Comment by mikebeaton** [comment]
Use `flags=0x678f` to get rid of `LINUX_BOOT_ADD_DEBUG_INFO` option (see docs).

'Windows' and 'EFI2' are each on (different) ESP partitions on the same drive. That's not really a correct layout. I think you don't have any option except to move/rename the BOOTX64.EFI of your Linux distro (which by the look if it should be in /boot/efi/EFI/BOOT of your started distro), or change the type of your second ESP to Microsoft Basic Data (EBD0A0A2-B9E5-4433-87C0-68B6B72699C7) (which you would then allow OC to see or not with OC_SCAN_ALLOW_FS_NTFS).

**Comment by naveenkrdy** [comment]
I got rid of the EFI2 entry by renaming BOOTX64.EFI
BTW so was it the flag that I needed to fix opencore blank screen hang, when using OpenLinuxBoot.efi, or you're still working on it ?

Thanks !

**Comment by mikebeaton** [comment]
The flag adds debug output which was meant to help identify [the](https://github.com/acidanthera/bugtracker/issues/1791) [hang](https://github.com/acidanthera/bugtracker/issues/1778), but is making it go away. I'm still working on it!

**Comment by mikebeaton** [comment]
@naveenkrdy - Thank you.

If you are able to try this build https://github.com/acidanthera/OpenCorePkg/suites/4067647287/artifacts/103390088 and if it hangs, with no flags specified in driver arguments, then the debug log may shed more light on this and it would be useful to see it.

**Comment by mikebeaton** [comment]
@naveenkrdy - Thank you for that, that does add more information.

Here is another one: https://github.com/acidanthera/OpenCorePkg/suites/4068428524/artifacts/103421525 . If this one also hangs, rather than making the crash go away, then it will be very helpful to see the debug log results of this one too.

**Comment by naveenkrdy** [comment]
@mikebeaton here is the new log
[opencore-2021-10-16-060119.txt](https://github.com/acidanthera/bugtracker/files/7357055/opencore-2021-10-16-060119.txt)

**Comment by mikebeaton** [comment]
Many thanks for taking those debug logs @naveenkrdy - you should find the hang is fixed by https://github.com/acidanthera/OpenCorePkg/commit/15bc4003b2ff0e9393b0899724711160b39a659a , if you can please re-test using empty `Arguments` (no `flags=...`) for `OpenLinuxBoot.efi` driver it should now enter OC picker menu and boot Linux correctly.
