### ISSUE TITLE
Battery Not Charging

### ISSUE THREAD

**Issue by eslamo** [acidanthera/bugtracker#1842]
Hi..

I spent a lot of time trying to figure a solution for my problem.

The problem is battery NOT CHARGING

Details:
- After Disassemble battery and Remove CMOS battery to hard clear CMOS and for first boot battery works great and charge and works fine.
- After battery reach more than 89% and do a restart I get Battery not charging.
- If I disconnect both batteries from laptop to reset CMOS it works again until restart.
- do reset default from bios menu not working** I must disconnect the batteries from motherboard
- do nvram reset not working**

After some diagnostics The battery is 5150mAH and what is in System Information is 4064mAH

Also I tried to boot windows and status stick to not charging and HP Support Utility shows Battery as Unknown.

But after disconnect batteries as i mentioned above HP tools shows that battery is normal and charging

Can anyone help me to find a solution for this problem that is very annoying and I really can't figure how to deal with it.

![IMG_6057](https://user-images.githubusercontent.com/2030376/140029485-6fc8be02-71e6-45ae-ae7f-379bcf5535e8.jpg)

![Screen Shot 2021-11-02 at 9 29 28 PM](https://user-images.githubusercontent.com/2030376/140029506-c74424b6-9d8c-4aca-b15b-c30d9e4c14d9.png)

[EFI.zip](https://github.com/acidanthera/bugtracker/files/7466217/EFI.zip)
[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/7466221/DSDT.aml.zip)
[IORegExplorerDump.zip](https://github.com/acidanthera/bugtracker/files/7466222/IORegExplorerDump.zip)

**Comment by vit9696** [comment]
Yes, I am afraid, if Windows also shows issues, you are best to investigate what hardware or firmware issue it is, but it is definitely not a macOS-specific issue. Try upgrading your BIOS and check your BIOS settings for battery-specific stuff. I heard that it helps sometimes.

**Comment by luisbocanegra** [comment]
Excuse me for reopening this...
I have the same problem, with an **Omen 15-dc1004la** battery percentage reflects the real one at first, but stays stuck after booting the hackintosh, so either with charging or discharging (it detects that is connected to charger) the percentage remains the same.

BUT If I remove and reinsert the battery while the laptop is on (charging) and running Monterey, the problem disappears and starts to update normally, both for charging and discharging. (same applies on windows, granted that I've booted the hackintosh before so the problem its indeed caused by something that happens in the hackintosh itself).

After some investigation, and a post on other forum about this problem I've found that there is a register (using [ec-probe](https://github.com/hirschmann/nbfc/wiki/Probe-the-EC%27s-registers) from [NoteBook FanControl](https://github.com/hirschmann/nbfc) on Linux) specifically **0x69**, it gets set to **0x00** after booting macOS and its when this problem appears,  after rebooting to Linux, with the same tool I can write **0x70** to the same register and this immediately solves the problem, not reboot needed at all. Also the message of a non-hp battery on boot disappears.
[DSDT-omen15-dc1004la-original.dsl.zip](https://github.com/acidanthera/bugtracker/files/7696742/DSDT-omen15-dc1004la-original.dsl.zip)
[patched-battery-patch-HP-G6-2221ss-osfix.zip](https://github.com/acidanthera/bugtracker/files/7696750/patched-battery-patch-HP-G6-2221ss-osfix.zip)
[Luis’s MacBook Pro.ioreg.zip](https://github.com/acidanthera/bugtracker/files/7696751/Luis.s.MacBook.Pro.ioreg.zip)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/7696761/EFI.zip)

![mac_os_battery_information](https://user-images.githubusercontent.com/15076387/145672077-68ebe2b9-2584-48fa-8e9e-dde6ef58bedd.png)
![linux_battery_information](https://user-images.githubusercontent.com/15076387/145672092-08f6211e-5e52-49b4-b95e-410c0ce02839.png)
