### ISSUE TITLE
Macbook Pro 14,1, MacOS 12.0.1 not boot with lilu.kext

### ISSUE THREAD

**Issue by bttd** [acidanthera/bugtracker#1877]
Hi.

I need some help according to my laptop. 

HW: Macbook Pro mid-2017 13" non touchbar version (14,1)
OS: macOS 12.0.1
lilu.kext: 1.5.7, 1.5.6, 1.5.4

I upgrade my laptop storage with an NVME adapter and a larger NVME.
Now there is a few compatibility issue wich is require NVMEfix.kext and SsdPMenabler.kext to solve. 

The SsdPMenabler load without problem, but if I try to load lilu.kext my laptop won't boot.
Is there any info on how to properly install it on macOS 12.0.1?

My method was:

disable SIP in recovery
copy lilu.kext and nvmefix.kext to /Library/Extension
enable the extensions in system settings / security
reboot

I can see the Apple logo and the progress bar at boot, but it only loads 1/3 of the progress bar then I get the kernel panic screen and reboot.
I already tried to load the kexts one by one, and the problem always appears if I try to boot with lilu.kext loaded. 

I find out there is a debug version, but I don't know how can I boot my laptop with boot arguments without opencore. 

Regards

**Comment by TheHackGuy** [comment]
You should never install any kext to s/l/e or /l/e/

Inject them with a bootloader.

**Comment by khronokernel** [comment]
So the issue is 2 parts:

* macOS Big Sur and newer requires either the `DisableLinkeditJettison` patch to be applied via OpenCore or `keepsyms=1` in boot-args 
* Adding kexts into `/Library/Extensions` will not add Lilu to either the Boot or System KC, but instead the Auxiliary KC making Lilu load far too late in the majority of scenarios. (applicable for Big Sur and newer)

Thus you'll be required to use OpenCore to inject Lilu and NVMeFix.kext. You can either do this via following the [manual](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) or using 3rd party tools like [OpenCore Legacy Patcher](https://github.com/dortania/OpenCore-Legacy-Patcher) designed around Mac support.

* OpenCore Legacy Patcher supports building and usage on native machines via the TUI variant and going into `Patcher Settings` -> `Allow OpenCore on native Models`

**Comment by artful88533** [comment]
Hi @bttd!
I have the same situation with the same MacBook model.
Did you install lilu.kext and NVMEfix.kext? If yes, how did you do this?
Did you use any bootloaders?

Thanks in advance!

**Comment by cmaliwat** [comment]
Having issues with MacBookPro14,1 and NVMeFix.
Get "folder with ?" while attempting to boot. Removing kext restores ability to boot into macOS.
Need to use NVMeFix on 14,1 to deal with power problems with non-Apple NVMe SSD.
