### ISSUE TITLE
Tools: ocvalidate

### ISSUE THREAD

**Issue by roddy20** [acidanthera/bugtracker#1917]
SecureBoot=default 
LoadDMG=Any
ocvalidate shows "no issues found"
OpenCore halts on critical error

**Comment by mikebeaton** [comment]
cc @vit9696 - I think it is correct that if `SecureBootModel` has any value other than `Disabled` (including empty value), then the value `Any` is illegal for `DmgLoading` (i.e. will cause this critical error) (but all other values, including empty value, are okay). Is that the right check?

https://github.com/acidanthera/OpenCorePkg/blob/ab4513fdb323be886b5967599900e5944a389ad2/Library/OcMainLib/OpenCoreUefi.c#L486

**Comment by vit9696** [comment]
@mikebeaton `Disabled` and `Signed` are both ok. Currently these are all the allowed values with the empty value being implicitly equal to `Signed` value. I am not sure whether the check is best to be written the other way around: Compare against ``, `Disabled`, and `Signed`, cause fatal error on any other value, but it is logically correct.

ocvalidate and OpenCoreUefi.c should have the same checks as mentioned in the issue. This is a bug indeed.

**Comment by mikebeaton** [comment]
I guess I was thinking we're not in general banning empty values in ocvalidate, so if an empty `DmgLoading` (meaning `Signed`) is okay normally, I guess it should still be okay along with non-disabled SecureBootModel?

Also, I think OpenCoreUefi.c (as linked above) is correct already? (Were you implying it maybe wasn't? Not sure... sorry!)

So I was thinking (I could) just add the test I mentioned to ocvalidate?

(Also just to clarify but - as I think everybody who has already been involved in this issue already appreciates perfectly well - the critical error is meant to be there, as it is a critical error - respecting those settings rather than stopping would be unacceptably unsafe!)
