### ISSUE TITLE
Audio not working after Windows Realtek driver (was: alctsel not working)

### ISSUE THREAD

**Issue by narcyzzo** [acidanthera/bugtracker#1934]
Hello. My machine when rebooting directly from Windows to MacOS doesn't have sound. I find its known issue on same/possible other hardware. Firstly found alctsel option, which is not working in any way, injected via device propeteries to audio device, or via boot- arg. Only solution to have sound when rebooting from Windows i found is to remove dedicated Realtek driver and keep Microsoft default one, which is pretty bad solution. I tried provide logs from Apple ALC and lilu, but from i know DebugEnhancer is broken on monterey. sudo dmesg showing nothing related to Apple Alc or lilu from what i see and also log seems to be cutted. *log show --predicate 'process == "kernel" AND (eventMessage CONTAINS "AppleALC" OR eventMessage CONTAINS "Lilu")' --style syslog --source* also shows nothing, only Timestamp. I have everything latest-commit compiled inluding kexts and Open Core builds. Runing 12.2 RC
My Specs: 
CPU [I7-9700K 5GHZ OC]
MOBO [Z390 AORUS MASTER]
RAM [HYPER X 32GB 3800MHZ CL 17]
GPU [SAPPHIRE RADEON RX 5500 XT NITRO+ 8GB]
Audio codec [ALC1220-VB]
Ethernet [INTEL I219V7]
Wifi/BT [Fenvi T919]

**Comment by legouju** [comment]
can vouch, have the same issue on my hardware

Specs: MSI GF63
i5-10300H (Intel UHD 630)
32 GB ddr4 2666 sodim
GTX 1660 Max Q 4 gb vram
256 gb m.2 ssd
240 gb sata ssd (macOS)

Using Opencore 0.7.6

**Comment by khronokernel** [comment]
The property in AppleALC's source is `alctcsel` (not `alctsel`):
* https://github.com/acidanthera/AppleALC/blob/e0cdf39aa45e64c6f205b114edad65712dbc0f1a/AppleALC/kern_alc.cpp#L120-L123

Looks to be a simple typo in the [Changelog.md](https://github.com/acidanthera/AppleALC/blob/c3bc2fa4641b2bd4296f5af38a09363a5a77f72e/Changelog.md), fixed in master

**Comment by narcyzzo** [comment]
beside typo fix, nothing more changed, still no sound after reboot unfortunately

**Comment by TheHackGuy** [comment]
@narcyzzo try getting some logs. I just took a look at AppleAMC code and it has logging of TCSEL. 

Use both debug versions of Lilu and  ApplaALC with bootargs -liludbgall and liludump=60 (note that 60 is seconds, so you may need to wait a bit before the log appears)

Logs will be located in /var/log. You can go to there with finder > go > go to folder, or just terminal.

**Comment by narcyzzo** [comment]
ok, nice i got log, but from what i see, debug shows that AppleALC aplying this patch, but something seems to be broken since i dont have sound still. 
[Lilu_1.5.9_21.3.txt](https://github.com/acidanthera/bugtracker/files/7926329/Lilu_1.5.9_21.3.txt)

**Comment by mikebeaton** [comment]
Might be worth adding a log to compare this one too, e.g. after rebooting from macOS - so still after a reboot, but with working sound.

When you have no sound, is there no (working) volume slider as when sound card is not present/not correctly configured, or is it there a volume slider, and it looks like it's working, but just no sound?

Also - just wondering - if you add AudioDxe and set it up to play a chime, is that also broken after rebooting from Windows, or alternatively does it have any effect at all on this problem?

**Comment by mikebeaton** [comment]
After _reboot_ from macOS to macOS (never using Windows) does sound in macOS work?

If you manage to install AudioDxe driver and get it working on a clean boot (i.e. playing a chime - on latest version 0.7.7 or current master, this may work with `AudioDevice` empty and `AudioOutMask` = `-1`, otherwise you will at least have to set your device path in `AudioDevice`, and may also have to play with `AudioOutMask`; set `PlayChime` = `true` and `AudioSupport` = `true`) then does this chime fail or work after Windows? And does it make any difference to sound in macOS after Windows.

**Comment by narcyzzo** [comment]
> After _reboot_ from macOS to macOS (never using Windows) does sound in macOS work? (I expect so, but just to be sure!)
> its not

**Comment by narcyzzo** [comment]
> After _reboot_ from macOS to macOS (never using Windows) does sound in macOS work? (I expect so, but just to be sure!)
When i never booted Windows, and reboot from MacOS to MacOS sound works thats true. When i boot to Windows, reboot to MacOS it will stop working, then rebooting from MacOS to MacOS again, still no sound. To get it back i must cold boot so power off machine and boot to MacOS- Sound working. (For Clarify). Also what is important this hapenning with dedicated Realtek Driver on Windows, keeping Microsoft default sound driver keeps audio working beetwen reboots from Windows to MacOS- that is strange.(I found this workaround online). Give me a second about Chime, i have it working with 0.7.7 but i dont test if chime is playing after reboot from Windows. Thanks for interest

**Comment by narcyzzo** [comment]
Ok. I got back Play Chime working, and i think as expected, when rebooting from Windows Chime is not Playing. Tried ResetTrafficClass quirk but this also changed nothing.

**Comment by mikebeaton** [comment]
>  i think as expected, when rebooting from Windows Chime is not Playing

I actually wasn't entirely sure about that, as they are different sound drivers - interesting info.

**Comment by mikebeaton** [comment]
This is also a shot in the dark, but try adding `--gpio-setup` in the driver `Arguments` section of AudioDxe.

**Comment by narcyzzo** [comment]
> This is also a shot in the dark, but try adding `--gpio-setup` in the `Drivers` `Arguments` section for AudioDxe (when it is configured and in use for chime).
>
ok, tried but nothing changed 
<img width="585" alt="Zrzut ekranu 2022-01-24 o 17 35 22" src="https://user-images.githubusercontent.com/54555731/150825683-291f1c24-b31b-4516-9db7-b6e884f989a5.png">

**Comment by mikebeaton** [comment]
There is also `DisconnectHda` in Audio section arguments you might just about try, but I am afraid that is unlikely to help.

A lot of what I did in AudioDxe recently was to agressively enable everything, which boot chime (and audio assist sound) working on more machines - hence I thought it might possibly work (esp. with `--gpio-setup`). But apparently the Realtek driver is leaving something strange set in the controller or codec, which neither macOS nor AudioDxe sound drivers know about, or know how to reset. But I'm not sure what.

With AudioDxe, in order to get sound from cold boot on more machines, I had to deal with the same issues Linux sound drivers deal with.... which makes me think - do you have Linux installed, and does _that_ manage to produce sound after Windows? If so, there is something to go on. (You could just boot a Linux live/install USB from a warm boot after Windows, it would not have to be installed on your hard drive, unless you have it or want to. Obviously needs to be a version which produces sound on cold boot!)

**Comment by narcyzzo** [comment]
Sure, i go and make Live usb with Ubuntu now and go test it.

**Comment by narcyzzo** [comment]
Ok, i dont know what i should think about this but, linux also doesnt have sound when rebooted from windows (working when cold booted). Same behavior as Mac
OS, everything is detected. 
![Screenshot from 2022-01-24 17-43-56](https://user-images.githubusercontent.com/54555731/150839440-39666f62-2a4b-41a1-a87e-d15a6d7547f0.jpeg)

**Comment by narcyzzo** [comment]
> linux >
booted via Open Core Picker, without `OpenLinuxBoot.efi` if its important

**Comment by narcyzzo** [comment]
Also, i think this should be reopened since more people can contribute

**Comment by narcyzzo** [comment]
> Well the final test is to boot into Windows _not_ via OpenCore, but via your BIOS boot menu. Then to reboot into Unix (e.g. live USB) _not_ via OpenCore but via your BIOS again.
>
Done this, no sound aswell

**Comment by narcyzzo** [comment]
I also have laptop, Asus UX534FAC `ALC294` sound card and behave strange also. Only mic is working in MacOS, tested all layouts, even create my own layout id for this codec-same only mic is working(no sound from internal speakers). Tested now Play Chime also dont work- on cold boot. I remember i tested on Linux sound works perfect- same on Windows. Thinking of if this can also be related to issue here.

**Comment by mikebeaton** [comment]
> I also have laptop, Asus UX534FAC `ALC294` sound card and behave strange also. Only mic is working in MacOS, tested all layouts, even create my own layout id for this codec-same only mic is working(no sound from internal speakers). Tested now Play Chime also dont work- on cold boot. I remember i tested on Linux sound works perfect- same on Windows. Thinking of if this can also be related to issue here.

This is separate, and probably more for forums. (Just from my own experience of sound being funny, do you have SSDT-HPET set up? But after that, try forums, I'd say.)

**Comment by narcyzzo** [comment]
From what i remember yes i tried that but im not sure which option i pick and which i should?  Also then which forum can u recommend? 
<img width="739" alt="Zrzut ekranu 2022-01-24 o 21 47 12" src="https://user-images.githubusercontent.com/54555731/150862107-22563848-8a6f-45b5-baec-a967a84d3e5f.png">
?

**Comment by TheHackGuy** [comment]
> I also have laptop, Asus UX534FAC `ALC294` sound card and behave strange also. Only mic is working in MacOS, tested all layouts, even create my own layout id for this codec-same only mic is working(no sound from internal speakers). Tested now Play Chime also dont work- on cold boot. I remember i tested on Linux sound works perfect- same on Windows. Thinking of if this can also be related to issue here.

It's a known thing with alc294 and asus. Send custom verb commands with appplealc (with alc-verbs enabled)

Those 2 commands are needed:
COEF_INDEX
PROC_COEF

**Comment by narcyzzo** [comment]
> It's a known thing with alc294 and asus. Send custom verb commands with appplealc (with alc-verbs enabled)
> 
> Those 2 commands are needed: COEF_INDEX PROC_COEF
> 
can u provide me little more? Which values for this commands and where to put?

**Comment by TheHackGuy** [comment]
> > It's a known thing with alc294 and asus. Send custom verb commands with appplealc (with alc-verbs enabled)
> > 
> > Those 2 commands are needed: COEF_INDEX PROC_COEF
> > 
> can u provide me little more? Which values for this commands and where to put?
> 
> 

Just activate alc verbs support with applealc. Then run alc-verbs tool in terminal. The values that need to be set for for these commands are supposed to be in the Linux codec dump.

**Comment by narcyzzo** [comment]
[DUMP.txt](https://github.com/acidanthera/bugtracker/files/7928840/DUMP.txt)
Here it is, if u want i can send u also my whole ZIP of what and how i do my own layout-id

**Comment by narcyzzo** [comment]
@mikebeaton  see this https://github.com/acidanthera/bugtracker/issues/547

**Comment by mikebeaton** [comment]
> > Well the final test is to boot into Windows _not_ via OpenCore, but via your BIOS boot menu. Then to reboot into Unix (e.g. live USB) _not_ via OpenCore but via your BIOS again.
> 
> Done this, no sound aswell

Hi. So this makes it look like a Realtek driver bug, not an OpenCore or AppleALC bug, right?

If it worked in Linux after Windows, I'd be happy to spend some time looking for a fix for AudioDxe (which might fix it for macOS afterwards). Since it doesn't, there aren't going to be any clues in the Linux drivers...

I'll cc @vit9696 (who is probably/almost certainly reading this anyway), but I suspect AppleALC will be in the same situation. There isn't much we can do without either reverse engineering the Realtek driver, or some fairly serious research on a machine using the actual driver and card to try to find out what's special about the state the driver leaves it in.

That may not happen any time soon unless you or someone who actually has the card has time to work on it

**Comment by mikebeaton** [comment]
> @mikebeaton see this #547

It sounds the same, but the news not in there, that we've just found, is that the same Windows driver breaks Linux sound as well, with no OC or AppleALC involved. :-(

**Comment by narcyzzo** [comment]
I got this, but what u think about https://github.com/acidanthera/bugtracker/issues/547#issuecomment-568301847, setting those commands cant solve this? If i have knowledge how to do reverse, sure. If i can help in any other way, told me how. Thanks

**Comment by mikebeaton** [comment]
I don't know my way around setting verbs in AppleALC, maybe someone else can chime in.

I can say that, to my understandinginh at least, setting those verbs is something different from what `alctcsel` or `Audio/ResetTrafficClass` do - which I believe do the same as each other.

**Comment by narcyzzo** [comment]
https://wiki.archlinux.org/title/ASUS_Zenbook_UX534#Power_saving_and_performance here is provided possible bug fix provided for same laptop but for linux, can someone more experienced see this? @TheHackGuy

**Comment by narcyzzo** [comment]
should i apply this via alc-verb? tried but nothing changed, i dont know exactly if i do this correctly. 
![Uploading Zrzut ekranu 2022-01-25 o 00.47.28.png…]()

**Comment by mikebeaton** [comment]
Try installing hda-verb on Linux and see if the above fix works on your system.

**Comment by mikebeaton** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1850439/comments/172

**Comment by TheHackGuy** [comment]
> [DUMP.txt](https://github.com/acidanthera/bugtracker/files/7928840/DUMP.txt) Here it is, if u want i can send u also my whole ZIP of what and how i do my own layout-id

sorry for late reply, was sleeping. 
I see the internal speaker is node 0x17 (23 in dec). 

Add the bootarg that activates alc-verb support. Then go to terminal and run alc-verb tool. 
Then try these commands: 
./alc-verb 0x17 SET_COEF_INDEX 0x40
./alc-verb 0x17 SET_PROC_COEF 0x40

The issues you guys shared about linux are using node 0x20 (14 in dec) but that's usually the headphone. If the above commands don't work then try inspecting some linux code. The internal speaker works on linux so there must be a fix somewhere there.

**Comment by narcyzzo** [comment]
>
./alc-verb 0x17 SET_COEF_INDEX 0x40 ./alc-verb 0x17 SET_PROC_COEF 0x40
> 
ok so i tried all possible configurations of verbs, nothing works, so im not sure if mayby alc-verb is setting those correctly? I know also `CodecCommander` exits and `ALCPlugFix-Swift` so mayby we should try with those? also @mikebeaton i dont apply commands with -d parameter? it is necessary for work? since im not sure what value to put here, my audio device is PciRoot(0x0)/Pci(0x1F,0x3). I also provide my zip of work with layout id if someone is interested. Here is path maps, verbs, nodes correction etc. Mayby this can be helpfull. Also @TheHackGuy mayby we can pm somewhere to not spam here since this is not directly related to Windows Realtek issue.
[ALC294.zip](https://github.com/acidanthera/bugtracker/files/7933724/ALC294.zip)

**Comment by mikebeaton** [comment]
Are you both on element.io or able to go on it? I'd be happy to be involved in PM! :-/ I am `@mikebeaton:matrix.ispras.ru`. You can sign up with default provider `matrix.org` and ping me. I am thinking that a fix sounds possible via AudioDxe; e.g. adding a `--hda-verb` flag, to allow sending custom verbs at init for situations like this - could potentially fix sound in macOS, Linux and AudioDxe itself.

**Comment by narcyzzo** [comment]
Im on it!

**Comment by narcyzzo** [comment]
its paid?

**Comment by narcyzzo** [comment]
> @mikebeaton:matrix.ispras.ru
> 
Done

**Comment by mikebeaton** [comment]
If `alc-verb` works (finds required service) then `alc-verb -l` lists available devices you can use for `-d` command. To get it working, I ended up adding `alcverbs=1` boot arg and `alc-verbs` = anything non-zero in device properties (not sure if both are needed). If none of the potential fixes (there were quite a few to try) works, on none of the devices, then we're a bit stuck again. You should be able to try them with `hda-verb` on Linux (again you'll have to figure out which device to use, or try all available, list all with`ls /dev/snd`) or with `alc-verb` on macOS. I'd be interested to know your Linux kernel version (`uname -r`), and maybe you should list (here on on Element) all the verb commands which you've tried that don't work, to confirm we're on the same page.

**Comment by mikebeaton** [comment]
Also, if I've understood correctly, you can decode the base64 ConfigData value for the codec and layout you are using, add required verbs (packed into 4 bytes) to the value, re-encode it and put it right into Info.plist inside your live AppleALC.kext which you are booting from, without having to recompile anything. So you can try the values @roddy20 suggested in other other thread directly in there. (Or you can decode them into separate node id's, verbs and values and try them with `hda-verb` or `alc-verb` in Linux or macOS.)

**Comment by mikebeaton** [comment]
Turns out there are two cards and two machines mentioned above. The ALC294 card (which the dump is from) is in a machine with no sound using AppleALC, but yes sound in Windows and Linux. The machine mentioned in the OP with no sound after Windows (in any of macOS, Linux or AudioDxe - and regardless of whether OpenCore is involved) has an ALC1220.

Currently, we have found no system (e.g. Linux) which fixes sound after Windows for the ALC1220. These are links to promisingly similar fixes in Linux for sound after Windows for the ALC294, but the verbs as given do not fix the ALC1220 (even though both cards do indeed have a similar looking, vendor specific, processing capable widget at 0x20):
 - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1850439/comments/172
 - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1850439
 
Since traffic on closed issues is monitored here, and since this clearly isn't an issue with AppleALC, I'm closing this again. If anyone finds any info on how to enable sound after Windows on the ALC1220 (or even wants to try passing through their ALC1220 card to Windows on a VM, and then using iommu to monitor the traffic to it), please feel free to post here or in the still open #547.

**Comment by mikebeaton** [comment]
Issue [was resolved here](https://github.com/acidanthera/bugtracker/issues/547#issuecomment-1059924209).
