### ISSUE TITLE
OpenLinuxBoot ASSERT 

### ISSUE THREAD

**Issue by Zormeister616** [acidanthera/bugtracker#1938]
Trying to boot with OpenLinuxBoot + ext4_64.efi yields this coming from OC
ASSERT [OpenLinuxBoot] UefiSortLib.c(61): BufferToSort !=((void *) 0)
[opencore-2022-01-31-043449.txt](https://github.com/acidanthera/bugtracker/files/7968292/opencore-2022-01-31-043449.txt)
If needed, the drives in my system are a Toshiba MQ01ABF050, a Seagate ST1000DM003 and a Seagate ST500LT012
as of yet i am unsure if btrfs_64.efi is affected as well

**Comment by mikebeaton** [comment]
Thank you for the bug report. If you have the latest build (pre-release 0.7.8), please can you re-run the debug log with `flags+=0x4000`; or if you have 0.7.7 please can you re-run the debug log with `flags=0xffff` - in either case this value goes in as is into the `Arguments` value of the `OpenLinuxBoot.efi` entry in `Drivers`.

**Comment by Zormeister616** [comment]
Here’s the log file generated, im running OC 0.7.
[opencore-2022-01-31-095326.txt](https://github.com/acidanthera/bugtracker/files/7969783/opencore-2022-01-31-095326.txt)
7

**Comment by Zormeister616** [comment]
[opencore-2022-01-31-233330.txt](https://github.com/acidanthera/bugtracker/files/7974916/opencore-2022-01-31-233330.txt)

**Comment by mikebeaton** [comment]
> [opencore-2022-01-31-233330.txt](https://github.com/acidanthera/bugtracker/files/7974916/opencore-2022-01-31-233330.txt)
> 
> EDIT: does OC only look in one specific area for a linux kernel? For some reason it cant find my generated one at /

Yes, OpenLinuxBoot makes various assumptions about the normal/standard layout of a distro, since we certainly can't just look everywhere (e.g. we do not want to generate boot entries for backups of the kernel stored wherever).

If I understand, you may have /boot as mounted in the distro as a separate partition (so your files are not at / in the mounted filesystem layout, but are at / of the /boot partition)? If so, we have known problems with that layout, with some additional work ongoing: https://github.com/acidanthera/bugtracker/issues/1776
