### ISSUE TITLE
[bluetoothd] Cannot unlock system with Apple Watch SE 2021

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1943]
Hi there,
I know probably that this isn't the best place to ask but I'm having issue with Apple Watch unlocking on macOS Monterey 12.2 (21D49).
I have an iPhone 12 mini + Apple Watch SE 2021 that correctly work together, but whenever I try to enable "Unlock with Apple Watch" option on macOS in Security & Privacy, it keeps saying that the Mac couldn't connect to Apple Watch.
I have a fully compatible DW1830 chip and Bluetooth devices can be successfully paired and used with the Mac (I use BrcmPatchRAM + BluetoolFixup).

I tried deleting Keychain Access keys for `Auto unlock` and `AutoUnlock` but the system keeps failing pairing to the watch.
Do you have any ideas on what could be?
Eventually what kind of system logs do you need?
Many thanks and have a great day
dreamwhite

Update

despite the option is ticked and the Mac says that it sent a notification to the watch, the watch doesn't receive anything.
![image](https://user-images.githubusercontent.com/17933708/152433134-ba8fa966-3f5f-4374-b07a-cd3444601a6c.png)

**Comment by antoniomcr96** [comment]
It is common on all non-native network cards (e.g.: BCM94352Z, BCM943602 that should be yours, BCM94350ZAE...). There isn't anything to do except purchase a native network card such as BCM94360NG. The BRCMPatchRam and Bluetoolfixup patches are not inteded to fix these kinds of problems

**Comment by abenraj** [comment]
@dreamwhite Bluetooth compatibilities broke with macOS 12 beta 5+ especially for non-native chipsets including Broadcom variants like the DW1830, this is a known issue #1821 . At this point, the most practical next-step would be to switch to original Apple Airport cards like the BCM943602CS etc.

**Comment by dreamwhite** [comment]
> @dreamwhite Bluetooth compatibilities broke with macOS 12 beta 5+ especially for non-native chipsets including Broadcom variants like the DW1830, this is a known issue #1821 . At this point, the most practical next-step would be to switch to original Apple Airport cards like the BCM94360CS2 etc.

what about a BCM94360NG?

**Comment by mikebeaton** [comment]
https://dortania.github.io/Wireless-Buyers-Guide/

**Comment by abenraj** [comment]
> what about a BCM94360NG?

Should potentially work as long as you're able to source the OG card manufactured by Fenvi coz there are BCM94360NG cards sold across e-comms _nowadays_ that are basically rebranded **DW1560** modules(depending on location and luck). Only Fenvi made modules are known to operate natively with macOS, even then, there have been issues reported with the Fenvi's stability and performances hence the suggestion to opt for genuine Apple Airport cards coz they just simply work as intended natively (and look way cooler too).

If you're someone who dual boots and works with Linux environment as well then you should probably opt for the BCM94360NG itself for Linux compatibility otherwise the more reliable Apple BCM94360CS2 for eg, is about the same price as the dual-antenna BCM94360NG/DW1560(at least where I reside) so why not just choose Apple. There's probably good reason the Dortania WiFi buyers guide implies using Airport Adapters as the preferred choice for most; even on laptops(thanks to FPC cables).
