### ISSUE TITLE
[Feature Request] Add option to store SMBIOS values on separate files.

### ISSUE THREAD

**Issue by phu54321** [acidanthera/bugtracker#1955]
[Disclaimer] I'll just assume that sharing EFI is a good thing. Note that I don't advocate plainly using other's EFI as-is. I don't support Multibeast or distros. Since dortania's guide is quite versatile and battle-tested, we can hackin-boot any supported laptop fairly easily.

Prebuilt EFI's are a great resource to learn how to configure each computer's configuration. If we have access to other's EFI for same laptop/PC.

- I could just copy `alcid` from other one's EFI without experiment.
- I could infer what ethernet kext I would need.
- There could be Kexts I didn't knew existed. (Ex: TB3-enabler.kext, IOElectrify) I learned them from [this efi](https://github.com/zhujinle/MSI-GS66-Stealth-OC-Hackintosh/) while hackintoshing my GS66.

----

Before sharing EFI we need to remove SMBIOS from config.plist. If one's version controlling OC build we cannot `.gitignore` that SMBIOS info since it's embedded in `config.plist`. So to distribute my EFI I should repackage them from scratch, and this loses my track of trial and error. With git, I can track down exactly what commit fixed what issues. (ex: Some commit fixes sleep issue, Some commit fixes wifi issue, Some commit enables 240Hz internal display) This information may help others referencing my EFI.

Solution: Add option to use `SMBIOS.plist`. A single file can be ignored from version control fairly easily.

Thanks.

**Comment by Rastafabisch** [comment]
While I very much like this concept, I‘d suggest a slightly different approach. I think for most people it would be better still having only one file. For those having issues with the current approach I‘d think that the basic Mac model should still be included (like `iMac14,2` or `MacBookPro11,3`) in the `config.plist` file. So if it’s shared people would still know to what kind of machine it refers to, as some patches are quiet dependent on this. Additionally, instead of the suggested `SMBIOS.plist` file there could be a machine specific plist file (like `iMac14,2.plist` or `iMac14_2.plist`). This way it would even be possible to have different SMBIOSes easily swappable with minor edits for testing purposes. That said a master `SMBIOS.plist` could still be an option anyhow.

**Comment by Andrey1970AppleLife** [comment]
https://github.com/acidanthera/bugtracker/issues/522
