### ISSUE TITLE
When BitLocker Windows is encrypted using BitLocker autounlock via TPM, it can't boot

### ISSUE THREAD

**Issue by HoshiYamazaki** [acidanthera/bugtracker#1958]
Hey,
So I got latest config of OpenCore and kexts (0.7.8).
I have tripleboot, and one of the OS'es is Windows 10 encrypted with BitLocker, without password unlock, but by using unlock via TPM keys. It has TPM 1.2.

And, if I'm booting Windows via OpenCore, it don't unlock it automatically, but rather wants me to provide recovery key. The same bug occurs in GRUB.
Can we do something about it?

**Comment by mikebeaton** [comment]
This is a feature, not a bug. You have asked BitLocker to only automatically unseal your drive if a fixed, measured boot sequence occurs. That fixed, measured boot sequence did not include OpenCore (or Grub) so TPM correctly won't unseal the key for BitLocker if you boot that way.

If you prefer to boot mainly via OpenCore, you can change it so that the drive is sealed for booting that way. This will mean that you need to update the seal each time that you update OpenCore (what is booting has changed, so TPM should and will refuse to automatically unseal again). And depending on how much security you want, you might want to look into OpenCore vaulting as well.

**Comment by junzhli** [comment]
hi @mikebeaton, thanks for the info as provided the above
i am wondering if that boot process through opencore will trigger the tpm reseal function so that no recovery key needs afterwards?

**Comment by mikebeaton** [comment]
@junzhli This isn't really OpenCore specific, it depends on what the firmware measures, which includes everything loaded as a UEFI driver or bootloader. So yes, if you change to including OpenCore in your boot process, then you will need the recovery key to validate that new setup. You should look at combining this with OpenCore vaulting, so that all settings and options of OpenCore are locked to a specific version too.

**Comment by junzhli** [comment]
> @junzhli This isn't really OpenCore specific, it depends on what the firmware measures, which includes everything loaded as a UEFI driver or bootloader. So yes, if you change to including OpenCore in your boot process, then you will need the recovery key to reseal to that new setup (or you can suspend BitLocker before making changes then resume afterwards to reseal, without needing recovery key, as per MS documentation). You should look at combining this with OpenCore vaulting, so that all settings and options of OpenCore are locked down too.

Got it! Thanks for that information 🙂 @mikebeaton  I think my config is good to go, I already enabled secure boot on bios and signed opencore efi with vault enabled to have dual boot (win10 + macos) through opencore bootloader.
Just make sure there's no need to input recovery code on each boot to win10 through opencore if I enabled bitlocker except that I update opencore related stuff

**Comment by mikebeaton** [comment]
Correct
