### ISSUE TITLE
[bluetoothd] macOS Monterey 12.2.1 issues

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#1959]
Hi there,
despite the issue was apparently fixed in issue #1821, thanks to BluetoolFixup, I'm still having issues with Bluetooth connection (I tested multiple devices such as my Apple Watch SE, iPhone 12 mini, multiple bluetooth keyboards and so on), and apparently it seems that the bluetooth is still broken.
My WiFi/BT card is DW1830 and I'm using the following kexts to make BT work:

- BlueToolFixup.kext
- BrcmFirmwareData.kext
- BrcmPatchRAM3.kext

It tries to connect but then bluetoothd seems to be crashing.

![image](https://user-images.githubusercontent.com/17933708/155214961-c70bf597-6acd-4b2a-a186-7046adc1ada7.png)

Is there anything you're aware of that can cause this issue? As far as I can remember, before upgrading to macOS Monterey 12.2.1, bluetooth stack was working fine (at least with my main bluetooth keyboard and Airpods 3).
Eventually can you guide me sending logs of BrcmPatchRAM and BluetoolFixup?
Many thanks

# Update

It seems like that rebooting my computer fixed the issue but I still don't get why it keeped crashing for no reason...

**Comment by khoa-nv** [comment]
I got the same problem with my DW1560 card and lasted Monterey (12.2.1). The airdrop is only worked one way, I can send anything from iPhone to my laptop but the other is not. The Bluetooth said that my Hackintosh is not supported.

**Comment by JayMonkey** [comment]
Hi,

I too am facing issues BT issues with Monterey 12.2.1 on my HP Laptop which has a  DW1830 combo card installed
VID = 0x14E4, PID = 0x43BA

Running the following kexts from BrcmPatchRAM release 2.6.1
   - BrcmPatchRAM3.kext
   - BrcmFirmwareData.kext
   - BlueToolFixup.kext

Previously the BT worked perfectly when booting BigSur (using BrcmBluetoothInjector.kext)

The Symptom in Monterey is that the BT will not turn on

<img width="625" alt="Menu-BT" src="https://user-images.githubusercontent.com/5662056/155765538-52344114-c34c-47eb-81be-3d2161662baf.png">

<img width="780" alt="Sys-Prefs-BT" src="https://user-images.githubusercontent.com/5662056/155765589-c94a958f-ac75-4269-902d-54512524b9ba.png">

Sys Info shows invalid data (Address = NULL)

<img width="1015" alt="Sys-Info-BT" src="https://user-images.githubusercontent.com/5662056/155765707-037259c5-9de4-477e-85d2-42ac6c95a191.png">

<img width="951" alt="Hackintool-Peripherals" src="https://user-images.githubusercontent.com/5662056/155766040-1b3c04e8-cdfa-4bf2-b032-7f8e858446bd.png">

<img width="1307" alt="IOREG-1" src="https://user-images.githubusercontent.com/5662056/155766061-267e1b7d-f2f2-4417-8141-44d9a2da01e0.png">

<img width="1307" alt="IOREG-2" src="https://user-images.githubusercontent.com/5662056/155766087-91f989eb-c7a1-4d55-bb73-b3fc3a9b5c84.png">

Despite Hackintool saying otherwise i'm not connived the FW has been loaded correctly ?

Happy to provide further debug info, but also appreciate that there have been major changes in the BT Stack in Monterey and many people reporting issues so maybe just a case of wait for the next release of BrcmPatchRAM ?

Appreciate all the hard work you guys do.

Cheers
Jay

**Comment by jbji** [comment]
It seems that I have got the same issue with my device(Mac OS Monterey 12.2.1).  Process bluetoothd keeps crashing, disabling Bluetooth in BIOS and enabling it again may help for a while, but it can't be long.
I have used IntelBluetoothFirmware + BluetoolFixup, and bluetooth works fine when using the same EFI on another laptop (same model, Monterey 12.1).

**Comment by mikebeaton** [comment]
Sorry, this is a side-issue I guess, but since you've made that specific recommendation, BCM94360NG seems to have serious issues with available Windows drivers - so possibly not that one (at least, not unless you have no interest in Windows, in which case it is 100% fine). Your general suggestion, apart from that, seems sound to me.

**Comment by dreamwhite** [comment]
> Sorry, this is a side-issue I guess, but since you've made that specific recommendation, BCM94360NG seems to have serious issues with available Windows drivers - so possibly not that one (at least, not unless you have no interest in Windows, in which case it is 100% fine). Your general suggestion, apart from that, seems sound to me.

Yes, I heard issues with Windows but since I'm not caring about it at all (I'm a Linux/Mac user) I decided to ignoring it at all.
Can I close the issue so?

**Comment by mikebeaton** [comment]
Hmm - I was literally just adding that comment, to avoid anyone who does want to use Windows having to buy another card when that one unfortunately kills that OS! Apart from that, apologies, but I am not an expert as to whether people are still actively working on this issue, for non-native cards. Someone else?

**Comment by alessiomatricardi** [comment]
@dreamwhite it's OT but what about #1532 ? Have you experienced capped NSS with this card? Very sad that BCM94360NG is native but so limited, maybe a fix via kext can be applied..

**Comment by M4cAbe** [comment]
> I don't know if it's actually worth it leaving that issue opened. I switched to a Fenvi BCM94360NG (native WiFi/BT card) and I'm not experiencing that problems anymore. I can use my Apple Watch to unlock my HackBook and authenticate using a custom sudo pam module.
> 
> My advice, if it can actually help is: switch as soon as possible to a native Broadcom module, such as the one I'm using

I have the same issue with Bluetoothd on original BCM943602CS Card from a MacBookAir.

I use the card in a Lenovo notebook and I have this problem that after sleep there is no Bluetooth and the CPU is loaded, in iOReg. shows that the problem is to do with Bluetoothd.
![Bildschirmfoto 2022-03-07 um 08 28 30](https://user-images.githubusercontent.com/90497389/156988874-6d43f562-2390-4b1e-8389-8cefe5c820e2.png)
![Bildschirmfoto 2022-03-07 um 08 32 11](https://user-images.githubusercontent.com/90497389/156988895-1899265f-d215-4bc9-b158-4d24d9580e7d.png)

I included the kext "BlueToolFixup.kext" in OpenCore but that doesn't change, any idea how I can solve the problem?

SMBios: MacBookPro15,4
OpenCore version 0.7.8
macOS Monterey 12.2.1

**Comment by vit9696** [comment]
I think it is best to discuss it within https://github.com/acidanthera/bugtracker/issues/1821.
