### ISSUE TITLE
kernel panic 12.3 --> 12.3.1 vm on last stage, host reboot fixes

### ISSUE THREAD

**Issue by 82ghost82** [acidanthera/bugtracker#1982]
Hi,
just to report I got a kernel panic during the last stage update from 12.3 to 12.3.1.
Running latest opencore/kexts in a qemu vm, cpu passthrough, 2x e5-2687w, third party kext for third party sata controller (reporting this since I'm reading something related to sata).
Host reboot fixes.
I was never able to read any kernel panic, sorry if it has nothing to do with opencore.
Kernel panic attached.
[panic.txt](https://github.com/acidanthera/bugtracker/files/8395738/panic.txt)

**Comment by khronokernel** [comment]
Kernel Panic looks to be a stall with the AHCI controller (as you noted the 3rd Party SATA controller). None of the Storage or AHCI kexts seemed to have been updated at all between 12.3 and 12.3.1. I believe this issue is simply your SATA controller stalling/entering a bad state. 
> Host reboot fixes.

This comment does seem to confirm my suspicion. I'd recommend verifying whether this issue is replicable with the 12.3.1 InstallAssistant as it should have the same RAM disk as the delta:

* [InstallAssistant.pkg: 12.3.1 21E258](https://swcdn.apple.com/content/downloads/49/07/002-79225-A_68Z2X28AVV/jfmg28xxxarr9av7ry0iefvst7cyl0qdhb/InstallAssistant.pkg)

Otherwise, I don't see how this issue relates directly to any of Acidanthera's projects at this moment. This looks to be just misbehaving hardware. I would recommend troubleshooting on forums further
