### ISSUE TITLE
Is it possible to emulate T2 chip?

### ISSUE THREAD

**Issue by wqhqq1** [acidanthera/bugtracker#2004]
I mean if we could emulate T2 chip so that we could use apple pay or touchID magic keyboard with hackintosh.

**Comment by mikebeaton** [comment]
T2 is basically an iPhone ARM processor, so a full co-processor. The features you're talking about use software actually running on this processor. (Apple obviously could have written the same software to run on the main CPU, but by writing it for the T2 they limit certain non-essential but desirable features to their newer systems. Of course, arguably, they have done this for functions that logically fit well on that co-processor, and reduce load on the main CPU, allowing for a fast system.)

Without fully emulating this (non-standard) ARM processor, and also emulating the way it talks to the main x64 CPU, and receives software updates, etc., etc., this is not possible. This is very unlikely to happen - one of the main driving forces behind the hackintosh community is that, with more or less small patching to the environment which the OS sees, macOS can run on standard x64 hardware (or on a standard, emulated x64 system). T2 emulation could at best work on a (very non-standard) emulator set up, not on real hardware - unless someone writes a T2 emulator as an EFI runtime service!!

There may also be private key signing issues (in receiving updates? in communication between the two processors?) which would render the whole task not just difficult, but illegal in many countries, due to infringing Apple's intellectual property. :-(

**Comment by mikebeaton** [comment]
@mhaeuser just pointed out to me, you could just emulate the required protocols for each specific feature which you want back (i.e. rewrite the software and the protocol it exposes, rather than have the original software running on an emulated T2) - but all this is still very unlikely to happen, basically for reasons already stated - massive effort, small gain. Unless you want to start working on it... :-)
