### ISSUE TITLE
[SSDT-PLUG] Is it still needed on macOS Monterey?

### ISSUE THREAD

**Issue by dreamwhite** [acidanthera/bugtracker#2013]
I'd like to continue the discussion that already took place on InsanelyMac about SSDT-PLUG on macOS Monterey ([thread link](https://www.insanelymac.com/forum/topic/351675-macos-12-monterey-x86platformplugin-without-plugin-type1)).

Is SSDT-PLUG still needed?

I tried booting without it on macOS Monterey 12.3.1 and X86PlatformPlugin loads without having the need of injecting `plugin-type one`.

![image](https://user-images.githubusercontent.com/17933708/168177619-34a5a1d5-2687-4434-8167-4e3bc0c68323.png)

Is this a "bug" or whatever? If not, shouldn't SSDT-PLUG be dropped for versions earlier than Monterey?

Eventually, can a MinKernel/MaxKernel criteria be added to ACPI injection mechanism as already done with kexts?

**Comment by khronokernel** [comment]
This is a "bug" on Apple part, more so an oversight with their power management stack and breaking linking with the legacy ACPI_SMC_PlatformPlugin.kext. This was introduced in 12.3 Beta 1, and I had to resolve it by outmatching ACPI_SMC_PlatformPlugin.kext against X86PlatformPlugin.kext:
* [OpenCore Legacy Patcher's build.py](https://github.com/dortania/OpenCore-Legacy-Patcher/blob/8e9571097587ecf788437309203229ae162bfe7a/resources/build.py#L177-L184)

```py
# With macOS 12.3 Beta 1, Apple dropped the 'plugin-type' check within X86PlatformPlugin
# Because of this, X86PP will match onto the CPU instead of ACPI_SMC_PlatformPlugin
# This causes power management to break on pre-Ivy Bridge CPUs as they don't have correct
# power management tables provided.
# This patch will simply increase ASPP's 'IOProbeScore' to outmatch X86PP
```

However as all Intel Macs that support XCPM will still expose `plugin-type` in their ACPI tables, there would be little logic to have this version dependant on the OS at least on the basis of `platform-plugin`. There is no harm keeping the variable in your ACPI tables regardless of OS so long as the hardware supports XCPM.

* You could manually omit it in 12.3 and newer yourself, but this is on the basis that Apple may not re-introduce the `plugin-type` check

With regards to the Min/Max, Vitaly and others have stated they will not do OS versioning for ACPI tables. This is under the same logic as OS checks for ACPI injection (ie. only injecting in macOS)

**Comment by abenraj** [comment]
> This is a "bug" on Apple's part, more so an oversight with their power management stack and broke linking with the legacy ACPI_SMC_PlatformPlugin.kext. This was introduced in 12.3 Beta 1, and I had to resolve it by outmatching ACPI_SMC_PlatformPlugin.kext against X86PlatformPlugin.kext

Okay, I totally get that this change broke one of the patches deployed within OpenCore Legacy Patcher; which I believe would otherwise allow non-supported legacy CPUS's like Ivy-Bridge and earlier to run on macOS 12. Of course credit where its due so thank you for your work on creating such a tool for legacy-based purposes.

However, what many of us fail to comprehend is: How exactly is Apple at fault here or what conditions apply here in order to classify this as a "bug" from Apple's end with respect to this apparent "breaking" of ACPI_SMC_PlatformPlugin.kext. Help us understand coz your logic here would seem to insinuate that Apple actually supports hackintoshes or a hacking solution like OpenCore Legacy Patcher that would otherwise allow legacy CPU's like Ivy-Bridge to continue receive native support on macOS 12.

It would only make more sense that this change by Apple was intentional since macOS 12 was surely not designed with the intention to provide native power management support for Ivy-Bridge and earlier and hence the breakage of legacy ACPI_SMC_PlatformPlugin.kext. I certainly see no reason why this legacy plugin shouldn't be deprecated already. 

I'll just safely assume that you meant to call this a "bug" from the project's point of view.
