### ISSUE TITLE
UnfairGVA, DRM, Sidecar, FeatureUnlock with AMD GPU >=Big Sur

### ISSUE THREAD

**Issue by rafale77** [acidanthera/bugtracker#2018]
I have posted this in the InsanelyMac forum but got no feedback.

I am essentially attempting to enable the AppleTV DRM without sacrificing the SideCar reliability as I think it was possible with Shiki before Big Sur. I eventually got to a viable solution but have been puzzled as to why some functionalities (some intended, some likely not) were not documented which would have saved me a lot of time. For details see [here](https://www.insanelymac.com/forum/topic/351752-amd-gpu-unfairgva-drm-sidecar-featureunlock-and-gb5-compute-help/).

1. I had to dig into the unfairgva code in WEG to understand its arguments. Only "1" is documented in the DRM readme.2.
2. Shikigva is completely disabled after Big Sur. I wish this was documented with more clarity so I would not have wasted my time testing.
3. FeatureUnlock does more than what is documented: On a iMac20,x with iGPU and dGPU enabled, it forces SideCar to run on the iGPU, making it much more reliable as the AMD encoding appears to not quite work. I stumbled upon it by chance.
4. Widespread reports of very large AMD GPU GB5 Compute scores differences (30-40% drop) when using one of the two dGPU only SMBIOS (iMacPro1,1 and MacPro7,1). I don't know whether this affects real life use cases but have been able to reproduce it even on an iMac20,2 SMBIOS after forcing the use of the AMD video encoder/decoder. Once in that state, it appears that only a reboot or sleep+wake cycle resets the driver and recovers the GPU performance. I was in essence able to narrow down the problem starting from SMBIOS to Board ID and finally down to the action of running the AMD video decoder/encoder.

Would pull requests into the readme documentation be desired? I would not mind contributing. I am in particular wondering why the unfairgva options were not documented.

**Comment by khronokernel** [comment]
Will comment on a couple points, others can fill in the rest:
> Shikigva is completely disabled after Big Sur. I wish this was documented with more clarity so I would not have wasted my time testing.

Discussed here (`WhateverGreen Shiki functionality is not planned for inclusion for macOS 11`):
* https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md

However you can expand the mention to `FAQ.Shiki.md`, as I noticed it's not mentioned in that area of the documentation.

> FeatureUnlock does more than what is documented: On a iMac20,x with iGPU and dGPU enabled, it forces SideCar to run on the iGPU, making it much more reliable as the AMD encoding appears to not quite work. I stumbled upon it by chance.

FeatureUnlock only patches SMBIOS models out of blacklists enforced by Apple. I cannot see how any of our patches would affect the functionality of a unit naively supported. If you know where this functionality is triggered, I would be interested to look into it more:
* https://github.com/acidanthera/FeatureUnlock/blob/master/FeatureUnlock/kern_start.cpp

I assume you toggled the `gvaForceAMDKE` default key mentioned in the README.md, as otherwise I cannot think off the top of my head any code in FeatureUnlock I wrote that would affect this.

**Comment by Core-i99** [comment]
Kak

**Comment by vit9696** [comment]
Sorry for you suffers. Yes, PRs to improve documentation would be very welcome.

**Comment by rafale77** [comment]
Thanks guys. I will submit some doc update pull requests
