### ISSUE TITLE
RestrictEvents shouldn't enable the memory or PCI UI patches by default on Apple hardware

### ISSUE THREAD

**Issue by OnesuchDev** [acidanthera/bugtracker#2046]
It is not necessary, makes the user experience differ from stock, and for some users any type of userspace patching creates instability and Hash Mismatch alerts.

**Comment by PMheart** [comment]
Hello! I made some tests on https://github.com/acidanthera/RestrictEvents/pull/8. You can try it and report here. Make sure you use the latest Lilu on master branch and RestrictEvents on my PR branch. You can grab them from GitHub Actions.

**Comment by khronokernel** [comment]
With regards to this userspace "corruption" on genuine Macs with RestrictEvents, this actually nothing to do with Macs specifically and simply due to slower/older hardware. The function we hook to patch in userspace is `_cs_validate_page`, and is called *heavily*. On capable hardware, generally newer desktops and laptops, there is zero noticeable issues with hooking this function.

However as you noticed, slower/more constrained hardware will hold up `_cs_validate_page` as we try to examine the pathing, match the bytes, patch, etc. And since the dyld shared cache is about 3GB~, this has to be split into each page ([4096 bytes](https://github.com/acidanthera/MacKernelSDK/blob/master/Headers/mach/i386/vm_param.h#L98)) and `_cs_validate_page` has to go through each and every single page until we find the section we want to patch.

PMHeart's PR will simply set the `auto` definition accordingly, however there's little that can be done outside of researching other ways to patch userspace in-memory without the reliance of `_cs_validate_page`
