### ISSUE TITLE
Feature suggestion: Override Apple "Startup Disk" boot model based on presence of certain file

### ISSUE THREAD

**Issue by justinkb** [acidanthera/bugtracker#2060]
I use OpenCore to boot macOS, Windows and Linux. I can change, from within both Windows (via "Boot Camp" utility) and macOS (via Startup Disk system preference), the startup disk to either the macOS drive or the Windows drive, which is nice.

My proposal is to make it possible to specify via config.plist that you want the contents (or perhaps just the presence) of a certain file in a boot entry's boot directory to make it so that OpenCore defaults to this boot entry instead. This way one would be able to reboot to Linux from Linux, while leaving the physical machine unattended during the reboot (sometimes one could be rebooting remotely, for example, but it would be useful even when not booting remotely). 

I want to know whether this feature would be upstreamable. If so, I think I would be able to implement it myself.

**Comment by vit9696** [comment]
Hi, why not to use efibootmgr or other tools available on Linux? They allow one to control the options.

**Comment by justinkb** [comment]
I actually use opencore to patch my DMAR table to work around an issue with
my motherboard bios acpi tables, so I want opencore to boot Linux via
openlinuxboot driver. But even if I didn't, it would be a nice feature to
have. It is low priority for me now, since I set up LUKS encryption anyway
on my current machine, so I cannot boot Linux noninteractively anyway. Feel
free to close if there is no interest in this feature

**Comment by mikebeaton** [comment]
Probably obvious, but if you are using OpenLinuxBoot then CTRL+Enter will work for a Linux distro, to set the current and upcoming default boot entry. (Less likely to work as wanted if using GRUB2, since GRUB2 tries to take over control of this after OC has set it, but you're not.) I appreciate that won't work if you're not at the machine and haven't already done it, but that point yes, I'd fall back to the suggestion of using efibootmgr.

**Comment by justinkb** [comment]
Thanks for the Ctrl+enter suggestion. I didn't know that
