### ISSUE TITLE
Can't boot OC on MacBookPro15,1

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#2145]
I Get this message:
![image](https://user-images.githubusercontent.com/7897244/198897556-a85735e5-5d81-48f9-9e2b-7f4f52a3b126.png)
```System Version:	macOS 12.6.1 (21G217)
  Kernel Version:	Darwin 21.6.0
```
```
System Firmware Version:	1916.40.8.0.0 (iBridge: 20.16.2032.5.3,0)
  OS Loader Version:	540.120.3~22
```
OpenCore version:
https://github.com/acidanthera/OpenCorePkg/actions/runs/3315447367

Secure boot is set to no security.

For the record I successfully used older OC version on this MacBookPro with older firmware in the past.

**Comment by vit9696** [comment]
I suggest you to use Apple BootPicker and just run ctrl+enter. If that does not help, I think you are best to ping @khronokernel & co about this, as I do not have T2 machines myself to help with this.

**Comment by startergo** [comment]
I tried booting rEFInd and got the same error. I found out that the security was set to medium security. As soon as I disabled it I was able to boot rEFInd and chain load OC. (I can swear I tried disabled security with previous firmware. Firmware got updated with latest Monterey update).
Reading in this section
https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#special-notes-with-securebootmodel
It implies that medium security model should boot? @khronokernel ?

**Comment by khronokernel** [comment]
Regarding the reference to the guide, it implies hardware lacking a genuine T2 chip (ie. pre-T2 Mac, PC) so some of the logic mention would either be different or non-applicable to genuine T2-based Macs. 

For your genuine T2 Mac, it requires Secure Boot to be completely disabled to allow unauthorized bootloaders/operating systems to load:
* [Apple Secure Boot Configuration](https://support.apple.com/en-us/HT208198)
* [T2 Linux Pre-Install Notes](https://wiki.t2linux.org/guides/preinstall/)

Since OpenCore is not trusted by Apple's firmware (and trust cannot be supplemented manually unfortunately), you will need to keep Secure Boot disabled.



-----------

If there's more that needs to be researched, I can examine more closely with a genuine Macmini8,1 next week.
