### ISSUE TITLE
[Request] Additional Optional LogoutHook Install Script Parameter

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#2156]
Requesting an additional optional `target` parameter for LogoutHook's launchd.command script that will allow specifying a volume name for the hook to be installed on. This will typically be the name of a volume that is not the volume the script is being run on. If the parameter is absent, the script should behave as it currently; that is, install the daemon/agent on the current volume.

The planned use case is to be able to install Logouthook (which really needs a new name as it is no longer just a logouthook and the name was too generic to start with) on other volumes separate from that hosting the script

**Comment by dakanji** [comment]
Indeed but that assumes everybody is using the OCLP which is not the case and this functionality seems to be valid enough to stand on its own as an enhancement to the script ... or am I missing something obvious?

**Comment by mikebeaton** [comment]
No - not at all, I actually specifically thought that for your RefindPlus project people were more likely to be using OCLP?

I would say, I am less worried about there being a manual post-install step for people who are using OC directly, in a more close-to-the-metal kind of way.

**Comment by dakanji** [comment]
I think you may mean `MyBootMgr` which configures RefindPlus and OpenCoreto work together. If so, then while they can manually incoporate it if they wish, users are not likely to be using the OCLP ... I don't to start with.

So, is providing this option something that can be looked into?

**Comment by dakanji** [comment]
Seems I misjudged the triviality and desirability of this.
Will get to the desired end by other means.

**Comment by mikebeaton** [comment]
Okay. Just to clarify at least one reservation I have: if someone is running multiple macOS installs (which is clearly who this must be aimed at), then it is quite likely they will add or fully reinstall one. So any step which gives the impression of doing a one-off install of emulated NVRAM for all macOS could be quite misleading, since it will need redoing per-OS anyway, after adding a new or fully reinstalled one. (I guess the daemon files should survive a non-clean reinstall, fwiw.)

The change is relatively trivial - obviously you won't want to try to start the daemon if it has been installed onto another volume, and it would be nice to have some sanity check for the presence of some reasonably identifying file or directory, to ensure it is being put into a macOS volume. Also, as I think we mentioned by PM, it should actually ideally look for a file which lets it determine the version of macOS it is being installed onto, to ensure it is Yosemite or upwards (as it works in a way which won't work below that; and so should be installed as a logout hook instead, which can't be done just by a file copy).

My second paragraph immediately above is what needs doing - _if_ it makes sense to do it, given the reservations of the first paragraph. Which perhaps does leave us at the status you summarise in your previous comment...

**Comment by dakanji** [comment]
Thanks. However, speaking plainly, I think the Paragraph 1 is distracted by how a third party tool **may** misuse the requested feature rather on how the feature stands on its own merit.

The feature being requested, I feel, should be assessed on whether it is **positive and worthwhile** that a user, having run the script to activate the daemon on the volume the script is hosted on, can have an option to directly rerun the script to do the same on anoother qualifying Mac OS volume present by simply passing a parameter to the script in place instead of having to save the script somewhere and reboot into each such volume to run the script.

How some third party tool, MyBootMgr or any other, chooses to use or misuse this in its `post-install` steps should not be a factor here at the project level. Actually quite surprised at how much third party tool considerations seem to be driving things.

Anyway, knowing that the position is unlikely to shift and I am already well gone into setting things up as setting daemons up is not rocket science so the speak. Only reason I brought it up here was because I thought the use scenario I outlined might be useful to others.
