### ISSUE TITLE
AirPlay to Mac is broken with macOS Ventura and FeatureUnlock 1.1.1

### ISSUE THREAD

**Issue by bootlegseahorse** [acidanthera/bugtracker#2181]
I've tested on my 2012 MacBook 9.2, 2015 iMac 17.1 and 2017 Hackintosh disguised as MacBook 14.1, but none of them have AirPlay to Mac feature functional with macOS Ventura 13.1 (22C65) and FeatureUnlock.kext 1.1.1 or 1.1.0, while AirPlay was fully functional on these devices with macOS Monterey 12.6.1 and earlier and FeatureUnlock.kext 1.1.0. 

While the "AirPlay to this Mac" option is already enabled in System Settings, the devices cannot recognize each other, nor could my iPhone or iPad recognize the Macs.

Any idea how this could be fixed in future releases?

**Comment by khronokernel** [comment]
If Systems Settings is showing the option, this means FeatureUnlock is correctly patching the blacklists. Are you certain this issue isn't with your iCloud or other local variables?

I verified with another user, AirPlay to Mac is functional for themselves on a MacBookPro9,2. Have you done any debugging to determine where the issue might lie? Logs and such are always appreciated.

Also if you believe the issue is FeatureUnlock, does using a newer Mac SMBIOS model resolve the issue?

**Comment by khronokernel** [comment]
Remoted into a dev machine, believe I do see a possible issue:
<img width="1668" alt="Screenshot 2022-12-16 at 8 57 03 AM" src="https://user-images.githubusercontent.com/48863253/208138320-0ba4de29-ef3f-4de5-9c4b-23e46e2fa804.png">

Will investigate further, however more research will be needed.
<img width="1624" alt="Screenshot 2022-12-16 at 9 00 37 AM" src="https://user-images.githubusercontent.com/48863253/208138771-bfd75b6a-5f8d-4b02-8c6a-d624c7475c3d.png">

**Comment by khronokernel** [comment]
Should be functional now as off commit https://github.com/acidanthera/FeatureUnlock/commit/94e29ce135001ad07cf456e594f5989a80c39146, also had a tester validate between iPhone and Mac
<img width="1668" alt="Screenshot 2022-12-16 at 9 18 55 AM" src="https://user-images.githubusercontent.com/48863253/208142413-b5c18c75-74fd-4419-85d4-4d248f250d47.png">

**Comment by bootlegseahorse** [comment]
Amazing! Thank you for the super fast fix.
