### ISSUE TITLE
OpenCore Logs stop printing to the screen but only to the USB log file

### ISSUE THREAD

**Issue by Sam1540** [acidanthera/bugtracker#2245]
I have reached out to several support forums (reddit & discord) and everyone is stumped by this issue and hence reporting here.

OpenCore-0.8.9-DEBUG

OpenCore stops displaying any logs to screen after a while and follow on logs are only written to USB storage.

User Impact: Since there is no more display in the screen, I am unable to select boot options

![imageedit_2_5449644675](https://user-images.githubusercontent.com/90673249/224873714-c2a7a83a-5eff-4fed-82e2-3dc1d5a5ab49.png)

[opencore-2023-03-13-175941.txt](https://github.com/acidanthera/bugtracker/files/10963497/opencore-2023-03-13-175941.txt)

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/10963504/config.zip)

- CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz

- dGPU: Nvidia GeoForce GTC 850M (Disabled using -wegnoegpu)

- RAM: 2 x 8GB Samsung 1600MHz

- Motherboard/Laptop model: HP ENVY 17 Notebook PC (228E made by Hewlett-Packard)

- Audio Codec: ALC290

- Ethernet Card: Realtek PCIe Ethernet Controller RTL8168/8111

- Wifi/BT Card: Intel AC7260

**Comment by Sam1540** [comment]
Resolved by setting in config.plist UEFI-> Output->TextRenderer to SystemText

**Comment by Sam1540** [comment]
Resolved by setting in config.plist UEFI-> Output->TextRenderer to SystemText

**Comment by mikebeaton** [comment]
Since this commit https://github.com/acidanthera/OpenCorePkg/commit/b07843fe1d47454747ae4eda9ea0189aa9fb8c03 OpenCore has been more strict (also more correct, according to [the pre-existing spec](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) for the relevant settings) about whether it starts in text or graphics mode. Thus depending on your existing setup, you may need to modify your settings slightly (either changing `TextRenderer` to one of the `...Text` options, or setting `IgnoreTextInGraphics` to `false`) in order to get back on-screen logging after the point where OpenCore takes over console output.

cc @MagistraNocte who spotted the same thing here https://github.com/acidanthera/bugtracker/issues/2073#issuecomment-1473138687
