### ISSUE TITLE
Caret symbol (^, SHIFT+6) does not work in the FileVault 2 login screen with the internal PS/2 keyboard

### ISSUE THREAD

**Issue by hacker1024** [acidanthera/bugtracker#2303]
My FileVault 2 password has a caret symbol (^) in it.
This character cannot be entered when using my Dell Inspiron 7586's PS/2 keyboard. A regular 6 is inputted instead.

Could this be due to a bug in the way OpenCore handles the keyboard?

Here are some notable details:

- Other symbols on the number row work fine.
- This issue does not occur in the UEFI shell.
- This issue does not occur when using an external USB keyboard.
- This issue does not occur on real Macs.
- I have observed this behavior on Catalina, Big Sur, Monterey, Ventura and Sonoma DP1. I have never seen it working.

My ESP files can be found here: https://github.com/hacker1024/Dell-Inspiron-7586-Hackintosh

**Comment by Andrey1970AppleLife** [comment]
It is a known problem with PS2 and SHIFT. Don't use similar characters in the password.

**Comment by mikebeaton** [comment]
Just wondering, was it UEFI Shell started from OC (so, presumably, using the same PS/2 driver as FV2) which works to produce '^', even though FV2 does not? (Or UEFI Shell started independently of OC, in which case less suprising.)

**Comment by mikebeaton** [comment]
UPDATE: Quick conversation with Vit he has kindly clarified why it is expected that this might not work in FV2 even if it works in UEFI Shell started from OC - because UEFI Shell uses EFI protocols directly, which contain ~ ascii key stroke values for typing characters (e.g. ^, 6), whereas OC has to try convert from these characters - with no direct SHIFT information - to an Apple-specific format that FV2 can understand. (And then with further limitation that not all firmware even do the EFI protocol the same, or as expected.)

However, it still seems strange that your system would work for most SHIFT+numeric, but not for SHIFT+6 - can you definitely confirm that the other SHIFT+number row keys produce the expected shifted characters, and that these other shifted characters (except for SHIFT+6 ?= ^) can definitely be used successfully in FV2 passwords?

**Comment by hacker1024** [comment]
> can you definitely confirm that the other SHIFT+number row keys produce the expected shifted characters, and that these other shifted characters (except for SHIFT+6 ?= ^) can definitely be used successfully in FV2 passwords?

Yep - I set my password to `!@#$%&*()` and was able to boot successfully.

**Comment by mikebeaton** [comment]
> > can you definitely confirm that the other SHIFT+number row keys produce the expected shifted characters, and that these other shifted characters (except for SHIFT+6 ?= ^) can definitely be used successfully in FV2 passwords?
> 
> @mikebeaton Yep - I set my password to `!@#$%&*()` and was able to boot successfully.

And `!@#$%6&*()` password validates whether you try to type `!@#$%^&*()` or try to type `!@#$%6&*()`, I guess?

**Comment by hacker1024** [comment]
I did not try that specifically, but I can see a 6 in the recovery key text box when I press SHIFT+6.
