### ISSUE TITLE
FeatureUnlock: Continuity Camera Unlock broken with Sonoma 14.0 on non-HEVC GPU

### ISSUE THREAD

**Issue by JDDPro** [acidanthera/bugtracker#2331]
FeatureUnlock.kext worked flawless on Ventura in unlocking Continuity Camera up to 13.6, but I just found that the unlock is now broken with Sonoma. If Continuity Camera is used on Sonoma, even with the newest FeatureUnlock.kext installed, the camera will return a black screen:

![Screenshot (2023-9-16 12 01 34 PM)](https://github.com/acidanthera/bugtracker/assets/144741013/701b7cd1-3b68-42da-af9a-89613d68ca3e)

**Mac Model**: MacBook Pro 9.2 (13-inch, mid 2012)
**CPU**: Intel Core i5-3210M @ 2.50GHz
**GPU**: Intel HD Graphics 4000 - 1536 MB
**macOS Version**: Sonoma 14.0 stable (23A339)
**iPhone Model**: iPhone 13
**iOS Version**: iOS 16.6.1 stable (20G81)
**OpenCore Version**: 0.9.5 release
**FeatureUnlock Version**: 1.1.5/1.1.6

Hopefully this could be fixed. 

I observe no issue in unlocking other features on Sonoma 14.0. Especially AirPlay to Mac works flawlessly.

Gratitudes xx

**Comment by khronokernel** [comment]
At least for macOS Sonoma RC 1, the function's init has not changed inside of `AVConference.framework [VCHardwareSettingsMac canDoHEVC]`. So our masking should still be effective:

* https://github.com/acidanthera/FeatureUnlock/blob/8a6bbec4a512e61219d461b1c8f3630e3ad4e26b/FeatureUnlock/kern_dyld_patch.hpp#L435-L449


<img width="1624" alt="Screenshot 2023-09-16 at 7 58 08 PM" src="https://github.com/acidanthera/bugtracker/assets/48863253/ac7fc1bc-410d-40e8-b131-d65b70414977">

Could you please provide a debug log of FeatureUnlock?

**Comment by khronokernel** [comment]
It seems this issue was resolved with macOS 14.1 Beta 1. We're still unsure why the patch failed, was able to replicate the issue locally on the release version of Sonoma (14.0 23A339) with a MacBookPro11,4. However on update, Continuity Camera functioned as expected.

Assuming the issue doesn't re-appear in later betas, I'll pass this as an odd one-time bug

**Comment by JDDPro** [comment]
Thank you!! Just updated to 14.1 beta (23B5046f) and can confirm that the Continuity Camera is working flawlessly now. Hopefully it doesn't happen again in the future.

<img width="1063" alt="2023-10-03 13 45 21" src="https://github.com/acidanthera/bugtracker/assets/144741013/fa7348de-b5d9-4ffe-b736-567566bc2ff8">

**Comment by khronokernel** [comment]
Got confirmation with macOS 14.1 Beta 2 (23B5056e) that Continuity Camera is still functional. Closing as one-off bug (will re-open if we find this issue pop up again)

**Comment by mhkanon** [comment]
Hi, Sorry for tell me issue here. I have a Notebook i5 Intel HD 4400. I use Montery with no issue. Recently I install Sonoma 14.0 all are working only the GPU 4MB. When the machine start the Login page Graphics is working. but after desktop come the blank white page come. The wallpaper is gone. And I check the 'About this mac' the graphics is only 4MB. How can I fix it? or you can share your EFI here. thank you.

**Comment by JDDPro** [comment]
> Hi, Sorry for tell me issue here. I have a Notebook i5 Intel HD 4400. I use Montery with no issue. Recently I install Sonoma 14.0 all are working only the GPU 4MB. When the machine start the Login page Graphics is working. but after desktop come the blank white page come. The wallpaper is gone. And I check the 'About this mac' the graphics is only 4MB. How can I fix it? or you can share your EFI here. thank you.

This is off topic, but your HD4400 GPU doesn't support Sonoma, so you'd have to set your SIP to 03080000 and manually install the GPU driver via root patching using the latest version of OpenCore Legacy Patcher. 

See: https://github.com/dortania/OpenCore-Legacy-Patcher/pull/1077#issuecomment-1646934494

**Comment by herminio18** [comment]
Hello i'm just a normal user, how can i enable continuity camera on my MacBook Air 2014 Sonoma, using Hacking tool,

**Comment by fabiosun** [comment]
Problem (in a not supported system) appears again in 14.2 beta 1 (with the same EFI 14.1 is perfet)

**Comment by Stealerwolf** [comment]
14.2.1 here, continuity camera doesnt work, cant try with a cable because I dont have any around

**Comment by ColossusStudios** [comment]
> 14.2.1 here, continuity camera doesn't work, I cant try with a cable because I don't have any around

*****
Confirmed! I also have macOS Sonoma 14.2.1, continuity Camera just returns a black screen, I am using lightning cable to the iphone 11 pro. I added access in privacy settings for the camera and microphone using tccplus, but still does not work.
Please help!

**Comment by wolffcatskyy** [comment]
Adding hard evidence that this came back after 14.1, per the reports above from @fabiosun (14.2 b1), @DaviMuza and @ColossusStudios (14.2.1). It is not a one-off, and I don't think it is the `canDoHEVC` mask failing — the mask does its job, but on a GPU with no HEVC decoder it unlocks a feature the machine then cannot decode.

**Setup:** MacPro6,1 via OCLP 2.4.1, macOS Sequoia 15.7.9 (also reproduced on 15.8.1), 2x AMD FirePro D700 (GCN 1.0), Xeon E5 so no Quick Sync.

```
VTIsHardwareDecodeSupported('hvc1') -> False
VTIsHardwareDecodeSupported('avc1') -> True
```

Note FeatureUnlock is **not** loaded on this machine and Continuity Camera is offered anyway, so what follows sits downstream of the unlock.

The session pairs and establishes fine over Rapport/AWDL, then dies in `VideoProcessing`:

```
VCPDec (640x480, HEVC): Detected unknown system for decoding
VCPDec (640x480, HEVC): Creating HW decoder only; FLS = ""
VCPDec (640x480, HEVC): Creating HW decoder was unsuccesful
VCPDec (640x480, HEVC): Failed to create video decoder, err = -12906
```

`-12906` is `kVTCouldNotFindVideoDecoderErr`. It then loops indefinitely requesting keyframes it can never decode (`_VideoReceiver_SendFIR` / `_VideoReceiver_CreateSampleBufferForDecode failed!`, 1,021 occurrences in 12 hours). That loop is the black screen this thread keeps describing.

**The decision that actually matters.** `VideoProcessing` classifies the machine into exactly one of:

```
Detected Intel-Mac capable of HW iGPU decoding
Detected Intel-Mac with AMD-GPU capable of HW dGPU decoding
Detected Intel-Mac with AMD-GPU capable of HW dGPU decoding but disabled due to negotiation string
Detected AS-Mac capable of HW AVD decoding
Detected embedded system capable of HW AVD decoding
Detected unknown system for decoding
```

and from that selects one of:

```
HW or fallback SW decoder
SW decoder only
HW decoder only
no decoder
```

Machines that fall through to `unknown` get `HW decoder only`, which by definition has nowhere to fall back to. A software HEVC decoder is present in the very same binary and is never reached:

```
HEVC: start sw video decoder session: dimension = %d x %d, usage = %d
```

**Controlled test.** Spoofing SMBIOS to MacPro7,1 via OCLP makes Continuity Camera work on this machine. Same GPU, same absent HEVC hardware, same codec, same hardware failure:

```
VCPDec (1280x720, HEVC): Detected Intel-Mac with AMD-GPU capable of HW dGPU decoding
VCPDec (1280x720, HEVC): Creating HW or fallback SW decoder
VCPDec (1280x720, HEVC): Creating HW decoder was unsuccesful      <-- still fails
VCPDec (1280x720, HEVC): Use default SW decoder
VCPDec (1280x720, HEVC): Created SW video decoder instead of HW video decoder
VCPDec (1280x720, HEVC): Created SW video decoder, usage = 1
```

`VTIsHardwareDecodeSupported('hvc1')` is still `False` after the spoof, and `-12906` is still emitted. The hardware failure is identical. The only thing that changed is the mode: under `HW or fallback SW decoder` the failure gets caught and software decode takes over. At 640x480 / 1280x720 that is free on any machine old enough to have this problem.

**Suggested fix:** map the `unknown system` classification to `HW or fallback SW decoder` rather than `HW decoder only`. A machine the classifier cannot identify is precisely the machine most likely to lack a hardware decoder, so it is the one that most needs the fallback. Both the fallback mode and the software HEVC decoder already exist. A narrower option would be to check `VTIsHardwareDecodeSupported()` for the negotiated codec before committing to HW-only.

**Caveats, stated plainly:** the branch and mode strings were recovered with `strings` over `dyld_shared_cache_x86_64.01`; I did no disassembly, so I cannot say which input drives the branch — an OCLP SMBIOS spoof rewrites board-id and IOKit-visible data, not just `hw.model`. What the experiment does establish is that the selected *mode* determines success, independent of which input selects it. I also have no H.264 session in any capture, so whether the mode is codec-conditioned is untested.

Given the 14.2, 14.2.1 and now 15.x reports, this looks worth reopening.
