### ISSUE TITLE
[Request] Add "Auto" Setting for InstanceIdentifier Key

### ISSUE THREAD

**Issue by dakanji** [acidanthera/bugtracker#2332]
I propose a modification that extends the current implementation by adding an option to use something like `Auto` where `InstanceIdentifier` would be set to the folder name.

That is ...
1. InstanceIdentifier = Blank : No identifier (Failsafe)
2. InstanceIdentifier = "SomeStr" : Use "SomeStr" as identifier
3. InstanceIdentifier = "Auto" : Use OC folder name as identifier

**Comment by vit9696** [comment]
I am not sure I like `Auto`, perhaps a separate flag is better, but the whole suggestion feels acceptable for some installations. I am not sure we should prohibit some generic names like OC for safety though.

cc @mhaeuser, @mikebeaton

**Comment by mikebeaton** [comment]
I'm not convinced as to why this is needed, and I thought we'd already discussed this (links below), agreeing that the OC team didn't really like this approach (of changing the OC instance's behaviour based on its directory name), and agreeing that what was [already implemented](https://github.com/acidanthera/OpenCorePkg/commit/dc182df42c519b70ff223bdbcd4d6de1455be362) here was sufficient for you to use!

I do think use-cases matter, for reasons already [mentioned](https://github.com/acidanthera/OpenCorePkg/pull/446#issuecomment-1508041583) by @mhaeuser.

If I understood correctly, @dakanji, you might have (&/or recommend to your MyBootMgr/RefindPlus users to have):

{ESP}/EFI/OCA
{ESP}/EFI/OCB
{ESP}/EFI/OCC

where OCA, OCB and OCC are (typically) set up to boot different macOS versions (in fact, here's [your own list](https://github.com/acidanthera/OpenCorePkg/pull/446#issuecomment-1508915384), with more detail).

If that's right, then, without this proposed change, you would also have to set the config.plist InstanceIdentifier for OCA, OCB, OCC (e.g. to OCA, OCB, OCC). And if you rename OCC to OCD, you'd have to remember to update the InstanceIdentifier at the same time, if you want it to behave the same as the proposed Auto setting. (But it's not clear to me why you would want it to, because it's the same instance as it was before it was renamed, so presumably it's set up for the same subset of all bootable OSes on the system as it was before.)

You [also mentioned](https://github.com/acidanthera/OpenCorePkg/pull/446#issuecomment-1508100507):

> if OC is copied to OC_BKP, everything will be enabled in OC_BKP. That was actually a specific goal.

That apparently is a case where you _don't_ want the new Auto behaviour. Not quite sure how that fits in?

So firstly, have I got the use-cases right? Then, can you clarify where the Auto feature would come in to helping make this work better?

Finally, even accepting multiple instances of OC are needed (or at least sometimes convenient, which I do accept), it's worth nothing that they don't have to be on the same partition; so on someone else's system, something similar might well be:

```
{ESP1}/EFI/OC
{ESP2}/EFI/OC
{ESP3}/EFI/OC
```

instead.

**Comment by dakanji** [comment]
The MyBootMgr angle, that is often focused on, is a bit of a red herring as it varies between users and can change for a user from one run to another.

Things seem to boil down to whether users should be allowed to have the option to base identification on the folder name if we wish or whether we should never be allowed this option.

**Comment by mikebeaton** [comment]
Yes. Please provide positive reasons for including it, as requested. OpenCore is not a maths equation, where all logical features compatible with the current implementation must be added. Thanks.

**Comment by dakanji** [comment]
Thanks for your input.
It is not that important at the end of the day and the item can be closed.
