### ISSUE TITLE
Can't achieve 4k@240hz 

### ISSUE THREAD

**Issue by oskarstr** [acidanthera/bugtracker#2429]
Although it's not necessaraly a bug,I think it's something that WEG should offer as a patch. 

Using latest Lilu & WEG on Sequoia. Issue was present on Sonoma as well. 6800XT gpu. 

It's impossible to achieve 4k@240hz resolution even though the link is at HBR3 x4 and recognizes DSC capabilities.

DSC compressed 4k240hz @ 12 BPP exceeds the bandwidth limits of HBR3 x4. When that happens the BPP should be reduced to 10, however the issue lies in the fact that for whatever reason coredisplay sets 12 bpp no matter what with no way to override it and as a result it tries all resolutions at 12bpp and defaults ultimately to 120hz. 

The DSC 12BPP value seems to be hardcoded in coredisplay. Specifically the value dscTargetBPP

Is there a possibility WEG could fix this either through providing manually the bpp value via bootargs or alternatively adjust it automatically?

**Comment by oskarstr** [comment]
nvm this is fixed, a fix will be coming soon

**Comment by joevt** [comment]
My WhateverGreen fork has @oskarstr 's new dscTargetBPP patch (for Catalina and later). I've modified it so that an arbitrary value between 6 and 63 can be used. Use a boot-arg like this `dscbpp=8`

My WhateverGreen fork also has his Sequoia update of the CheckTimingWithRange patch (for Tiger and later). Use boot-arg `-cdfon` . This patch is one method to bypass the 500kHz horizontal scan rate limit. An alternative method would be a kernel patch specific to the GPU.

Both patches should work up to at least Sequoia. The patches are independent of each other. They patch a framework used by the WindowServer process.

My WhateverGreen fork depends on my Lilu fork. All Lilu based kexts that you want to use need to be rebuilt using the Lilu.kext produced by my Lilu fork because of changes made to Lilu.

**Comment by mikebeaton** [comment]
Hi @joevt - Can you offer some of these changes as pull requests to WhateverGreen?
