### ISSUE TITLE
unable to continue the build! the password is incorrect

### ISSUE THREAD

**Issue by chris1111** [acidanthera/bugtracker#2441]
Unable to build OpenCore from commands in macOS
`Failed to clone submodule , aborting`
fatal: clone of
"https://github.com/Zeex/subhook.git' into submodule path '/Users/chris/Github/OpenCorePkg/UDK/UnitTestFrameworkPkg/Library/SubhookLib/subhook' failed

This bug appears on all versions of macOS and on all versions of Xcode
Testing by me from Monterey to Sequoia
![Screenshot 2024-11-03 at 7 25 59 PM](https://github.com/user-attachments/assets/686671e1-6f92-42f5-9742-f409eea5163c)

I have never had to put a user name and password at this step before.

**Comment by al3xtjames** [comment]
This submodule comes from upstream EDK II: https://github.com/tianocore/edk2/blob/47ba459fc1c2cda532b5d7cf16c9fdcbb200784d/.gitmodules#L28C8-L28C43

**Comment by mikebeaton** [comment]
@vit9696 - I don't think UnitTestFrameworkPkg is relevant to us, and the existing DISCARD_SUBMODULES functionality _almost_ supports removing it, already. If I update ocbuild efibuild.sh to use `git rm -r` instead of `git rm` and update `build_oc.tool` to have `DISCARD_SUBMODULES=(OpenCorePkg UnitTestFrameworkPkg)` then we can build again. Could be worth applying these small fixes for now?

**Comment by chris1111** [comment]
Thanks @mikebeaton  it work now with [this commits](https://github.com/acidanthera/audk/commit/036165f251d79c5427e569347abc3aa21f57d628)
Thanks @al3xtjames to catch the upstream issue

![Screenshot 2024-11-04 at 5 31 04 PM](https://github.com/user-attachments/assets/b722933d-2411-4ef4-b350-c4ebbf1ea178)
