### ISSUE TITLE
1080p instead of 4k on the login screen when using agdpmod=pikera

### ISSUE THREAD

**Issue by wujekbogdan** [acidanthera/bugtracker#282]
I have a 4k resolution during boot, but on the login screen the resolution changes to 1920x1080. After logging in, the resolution gets back to normal. 

It happens only when I use the `agdpmod=pikera` flag (which is required, otherwise the display does not wake up after sleep).

---
10.13.6, Asus Z87M-PLUS, i7-4790k, MSI GTX 960, Nvidia Web Driver 387.10.10.10.40.105, Dell 27 P2715Q, WhateverGreen 1.2.1, Lilu 1.2.6

**Comment by vit9696** [comment]
Hi,

This is not our bug, and you should pretty much forward it to NVIDIA team, as I expect it to be reproducible on MacPro5,1. I would recommend you to avoid `agdpmod=pikera`, since it is only for historical and compatibility reasons, and focus on getting in contact with NVIDIA, as the real fault is the sleep wake issue. I think you might be able to workaround it by providing `darkwake=X` boot-arg, where X is bit mask of the [following values from XNU kernel](https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/iokit/Kernel/IOPMrootDomain.cpp#L303-L312), but I am not fully convinced in it.
