### ISSUE TITLE
SSDT-RTC-FIX

### ISSUE THREAD

**Issue by Frank-N-Furter** [acidanthera/bugtracker#348]
Some new BIOSes example for Intel NUC 8 or Gigabyte Z390 Gaming will break boot after upgrade. According to the log, it seems to be a NvMe, SATA, or file system problem. Below is a new RTC device code that causes the problem. I couldn't find out what sets the STAS variable that turns off this device. I attach a ssdt with a hack, which completely remove and then add the correct RTC device.

If it suits you, add it to the OC.
---------------------------------
RTC device code that causes the problem:

     Device (RTC)
        {
            Name (_HID, EisaId ("PNP0B00") /* AT Real-Time Clock */)  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x08,               // Length
                    )
                IRQNoFlags ()
                    {8}
            })
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If ((STAS == One))
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }
        }

[SSDT-RTC-FIX.dsl.zip](https://github.com/acidanthera/bugtracker/files/3220141/SSDT-RTC-FIX.dsl.zip)

**Comment by vit9696** [comment]
Consider including all the original files, we might give it a look some day.

**Comment by vit9696** [comment]
I requested some information on the matter and it seems that rcent APTIO firmwares have a hidden option to enable/disable RTC device through that STAS variable.

For this reason you could do one of the following rather than disable the device and add a new one:
1. Change that variable by directly writing to NVRAM with a [modified GRUB](https://github.com/acidanthera/AptioFixPkg#verifymsre2) like with CFG 
2. Set STAS variable to One in some _INI method, potentially even in RTC device itself
3. Create ACPI binary patch for RTC _STA to always return 0xF as described in OpenCore manual

In addition to a discussible method choice the suggested SSDT creates an RTC device with just 128 bytes of CMOS memory instead of the usual 256 (due to IO range). That means it will not be useful for authenticated restart or hibernation anyway. I am afraid there is very little sense to mention such workaround even if I was ok with the approach. All the three methods above will be far cleaner.

**Comment by Frank-N-Furter** [comment]
You right.

STAS controls also the device AWAC (ACPI000E). When STAS is ONE RTC is active and AWAC is off. I attach a better solution that sets STAS to ONE with _INI of _SB for versatility.

This problem started to appear to me with the new Bioses for the Z370 Gigabyte AORUS GAMING 7-OP and Intel NUC 8.

[SSDT-SET-STAS.dsl.zip](https://github.com/acidanthera/bugtracker/files/3272131/SSDT-SET-STAS.dsl.zip)
