### ISSUE TITLE
OcSmbiosLib: Add support for custom memory configuration.

### ISSUE THREAD

**Issue by PMheart** [acidanthera/bugtracker#381]
To be discussed later.
Ref:
- https://www.dmtf.org/standards/smbios
- https://applelife.ru/threads/razrabotka-opencore.2943955/page-11#post-800610

`PlatformInfo -> Memory` would be a good place to put properties beneath.
Milestones to be set.

**Comment by hbfs** [comment]
Required for X99 C612 platforms.

**Comment by xe97** [comment]
necessary for some X99 / C612

**Comment by carlitossuper1** [comment]
On my P55 system it reports 0MHz SDRAM. 

Currently there's MemoryFormFactor, and according to the SMBIOS spec, MemoryType can be added. In my case 0x18 for DDR3. Another entry for the speed could be needed.

On Clover, I had to manually add my slots information or otherwise the same would be reported. On windows I had the correct information, so IDK what's wrong on my system.

PS: I know this is just cosmetical and of course I also wait.

**Comment by Goldfish64** [comment]
Added in https://github.com/acidanthera/OpenCorePkg/commit/bf043cae2e54e0dd316f49afba5bb08c3c3baaeb.
