### ISSUE TITLE
Custom boot drive name

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#421]
When using a drive name other than "Macintosh HD" and then using System Preferences > Startup Disk > (macOS boot disk) as the default boot disk, it will not make it the default start up disk in the OC boot picker. we MUST use "Macintosh HD" for this feature to work. but after change another name is working fine for autoboot.

even if efi-boot-device and efi-boot-device-data is correct in NVRAM.
![스크린샷 2019-07-14 오후 7 51 21](https://user-images.githubusercontent.com/50421769/61182623-fea0a680-a670-11e9-9ba6-ea37e8633d4e.jpg)

**Comment by vit9696** [comment]
`efi-boot-device` and `efi-boot-device-data` are not used by OpenCore. There is not enough data to provide any reasonable reply to you (boot log, config). For example, you could have `RequestBootVarRouting` disabled or some driver outdated.

Closing as a configuration issue.

**Comment by hbfs** [comment]
sounds like booting without having to manually select a menu option in OC. like how clover can auto boot if no selection is made after X seconds. 

It works if the name of the boot drive is "Macintosh HD" yet fails otherwise.

 theres a comment about this in the code as well https://github.com/acidanthera/OcSupportPkg/blob/ee180ad318f1fcbe6c5df8e73b3c9645cfbcfbc1/Library/OcBootManagementLib/OcBootManagementLib.c#L97

Haven't dug too deep into where the boot drive is sourced from, if its "spontaneous" then it sounds like a race condition or an update event not being triggered.

**Comment by vit9696** [comment]
It works just fine here and on many other systems. I do not have Macintosh HD, for example. The comment has nothing to do to default matching, it only says that OpenCore sometimes displays partition names wrongly due to macOS not updating their metadata in special files.
