### ISSUE TITLE
Continuous builds results (binaries) for downloads?

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#436]
Does it make sense to expose it?

**Comment by vit9696** [comment]
Hi, yes, it makes very good sense. However, it needs some good thought on how to do it (i.e. where to upload), and manpower to actually implement the uploading

It makes little sense to bloat releases page with release uploads, so it probably makes sense to have a dedicated repository for this, but I am not sure how it is supposed to look. Feel free to suggest the design.

**Comment by nms42** [comment]
Two tools for possible usage

https://github.com/d1vanov/ciuploadtool (written in go, Travis & other)

https://github.com/probonopd/uploadtool (written in bash, Travis only)

**Comment by Pavo-IM** [comment]
https://www.bitrise.io/ is a pretty good and it already includes uploading to Github Releases automatically.

**Comment by vit9696** [comment]
GitHub Actions support uploading artifacts on commit basis. Here is an [example](https://github.com/osy86/HaC-Mini/blob/master/.github/workflows/build.yml) on how to do it. If you click on some action in [the list](https://github.com/osy86/HaC-Mini/actions), you seem to get a [view with Artifacts](https://github.com/osy86/HaC-Mini/commit/517b2f03a44b19288b7e8aa25b2783082522fd6f/checks?check_suite_id=369552006) available for downloading.

This looks somewhat ugly, as the access path is somewhat convoluted, but I believe it can solve the task. We will still want to use Travis for our main releases, however, as GitHub actions do not offer enough flexibility with macOS images. Only [latest](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) macOS version is available with some [10.15 only configuration](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015). This will create an unnecessary risk if something is broken with this compiler, like it already happened with Travis many times, where we just chose an older Xcode version until the issue was resolved.

Pull requests enabling this at least for OpenCore are welcome.

**Comment by nms42** [comment]
Shall we try VisualStudio (2019?) builds?

**Comment by vit9696** [comment]
For now I would say no, their compiler is garbage. But we can consider them as a part of https://github.com/acidanthera/bugtracker/issues/636, i.e. build only, and then see how it goes.

**Comment by vit9696** [comment]
This was resolved as a part of a standalone service on Dortania:
https://dortania.github.io/builds
