### ISSUE TITLE
Better documentation/support for Clover users going forward.

### ISSUE THREAD

**Issue by MysticalOS** [acidanthera/bugtracker#455]
Not really sure where else to put this, but I believe you should still maintain a "Clover Support Package"

The more you migrate into opencore, the less your stuff is usable in a clover configuration.

If you don't do a clover support package though, at very least there should be new notes added to each project that say "if using with clover, don't install FwRuntimeServices.efi since it's useless by itself, switch to clovers memory fix driver"

At moment, most are going to stay on clover until opencore is more user friendly and mature so you need to make sure as you transition your own projects to OC, they don't begin causing problems in short term for clover.

**Comment by Download-Fritz** [comment]
Thank you for your comment.

There is no documentation for FwRuntimeServices.efi indicating it is useful for Clover, it has been introduced as an OpenCore-specific since the beginning, hence I do not believe a separate note is required. I also don't see a need for a note on which drivers to use with Clover instead, as this is up to the user's judgement and preference.

We are aware of the fact that features migrated to OpenCore are not available to Clover users anymore, this is the nature of such a migration. We believe that this improves the OpenCore user experience as well as our maintaining capabilities. Clover functionality verification gets tougher as everyone involved has switched to OpenCore and is simply no longer feasible at this point.

As the decision is final, this ticket is closed. Thank you for understanding.

**Comment by vit9696** [comment]
As a side note, I should alert that almost all code potentially relevant to other projects and/or bootloaders resides in [OcSupportPkg](https://github.com/acidanthera/OcSupportPkg), not in [OpenCorePkg](https://github.com/acidanthera/OpenCorePkg). In case anybody wants to create something like "CloverSupportPkg", he could currently add OcSupportPkg as a dependency, and use all the modules that OpenCore is comprised of.

However, just as @Download-Fritz mentioned, we have no plans to initiate such project ourselves, and we will not guarantee any API compatibility for third-party projects relying on OcSupportPkg as well.

From our point, OpenCore, while still in alpha stage, is fairly stable and provides decent user experience in the scope of our concern.
