### ISSUE TITLE
MacInfoPkg: is there a reson to have git diffs for autogenerated Products.json?

### ISSUE THREAD

**Issue by nms42** [acidanthera/bugtracker#466]
Looks like git diffs are greater then the file itself. May be the package needs

`Products.json -diff`

in .gitattributes?

**Comment by vit9696** [comment]
Hmm, could you please remind me whether it disables diffs during commits as well? If so, this could probably reduce commit speed. If not, and it only affects the display part, it sounds like a good idea to disable it. Please commit it then.

**Comment by vit9696** [comment]
I checked the documentation, and it reads as follows:

```
Marking files as binary
Git usually guesses correctly whether a blob contains text or binary data by examining the beginning of the contents. However, sometimes you may want to override its decision, either because a blob contains binary data later in the file, or because the content, while technically composed of text characters, is opaque to a human reader. For example, many postscript files contain only ASCII characters, but produce noisy and meaningless diffs.

The simplest way to mark a file as binary is to unset the diff attribute in the .gitattributes file:

*.ps -diff
This will cause Git to generate Binary files differ (or a binary patch, if binary patches are enabled) instead of a regular diff.
```

Basically it means that human-readable diffing will be entirely disabled for this file, but binary file differ still exists, so it should not make any problems to our workflow.

Since the file is not meant to be human readable in the first place, I agree with the change. Feel free to handle it as I am currently away from the keyboard.
