### ISSUE TITLE
Documentation Enhancement About Hardware NVRAM

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#537]
As we know there is a simple method to tell if a motherboard has Hardware NVRAM or not by running **`nvram x=y`** and reboot and then run **`nvram x`** to check. If **`x`** exists, then there is Hardware NVRAM. But what is Hardware NVRAM? I can't find any detailed documents on the internet. I'd appreciate if you guys could document it based on your knowledge. 

Some questions:
1. why is it possible for macOS to save nvram settings across reboots on 7,8,9 series motherboard while not on 300 series motherboard? 
2. what is Hardware NVRAM? is it a misleading name? should we call it Writable NVRAM?
3. do 300 series have nvram chip on the motherboard?
4. some motherboards can get Hardware NVRAM by installing certain version of BIOS firmware, e.g. some z170 boards. is it possible to enable Hardware NVRAM by BIOS modding? I tried once to diff the extracted DSDT and SSDTs, but since the offsets are all different, it is really hard to find the differences. 

i have other questions but i don't know how to ask, because i do not have a picture, forgive me if above questions sound foolish. Feel free to close it if you think it is not necessary to have these documented or it is unrelated to your project. 

thanks.

**Comment by MysticalOS** [comment]
Hardware nvram means it's supported....by the hardware.

when it's not present. the .efi extention that fakes nvram is required which basicallly makes it look like there is hardware nvram but really it reads/writes settings to an nvram file cache. the difference is variables are stored in the boards physical nvram instead of a fake nvram scratch file. So on user end the big difference is whether or not you need one extra .efi driver for clover (and maybe opencore? not sure if they just build that check in).

**Comment by Andrey1970AppleLife** [comment]
Use forums for support.

**Comment by vit9696** [comment]
For that I would say use UEFI spec and ACDT0117PEN. See:
https://github.com/acidanthera/bugtracker/blob/master/DOCUMENTS.md

There is really out of the scope of OC manual.

**Comment by cattyhouse** [comment]
@vit9696 great researches, that’s what i was looking for, thank you!
