### ISSUE TITLE
CX8050 doesn't work with AppleALC 1.4.3 but works with 1.4.2 (Catalina 10.15.1)

### ISSUE THREAD

**Issue by hieplpvip** [acidanthera/bugtracker#570]
Hello,

My laptop is Asus Zenbook UX410, which uses CX8050. On Catalina 10.15.0, AppleALC 1.4.3 works beautifully, but after upgrading to 10.15.1, it doesn't work anymore (no device in System Preferences/Sound/In-Output). I downgrade to version 1.4.2 and it works again.

Another person on InsanelyMac faces this problem too. He/She also uses CX8050.

I found several changes regarding CX8050 in 1.4.3 changelog. Could that be the problem?

If you need any logs, please tell me.

P/s: Thank you for making Hackintosh great.

**Comment by vit9696** [comment]
This looks like garbage to me. 1.4.3 *added* new layout-id, 13, for CX8050. It did not change any other layouts, thus the changes you mentioned for CX8050 could not have possibly broken your setup. Look for the issue elsewhere.

In my opinion, the problem is unrelated to AppleALC, but if you think it is please use `git bisect` to find the exact commit that caused the problem. Once you find the commit, we can try to help.

**Comment by hieplpvip** [comment]
After some testing, it seems like a race-condition introduced in 10.15.1. With latest release version, audio sometimes works, sometimes doesn't. I'll test more and report later.

**Comment by Andrey1970AppleLife** [comment]
@hieplpvip 
Please fix README.md https://github.com/hieplpvip/AppleBacklightFixup
AppleBacklightFixup now part WhateverGreen.

**Comment by tctien342** [comment]
> After some testing, it seems like a race-condition introduced in 10.15.1. With latest release version, audio sometimes works, sometimes doesn't. I'll test more and report later.

Comfirmed same the same with my ALC295 and mojave 10.15.1

**Comment by vit9696** [comment]
All in all this sounds like a similar issue to https://github.com/acidanthera/bugtracker/issues/422. Better to move there.
