### ISSUE TITLE
WhateverGreen 1.3.5 kernel panic

### ISSUE THREAD

**Issue by cattyhouse** [acidanthera/bugtracker#572]
Just tried 1.3.5, got kernel panic. revert to 1.3.4, problem solved. 
hwinfo: B360M/i5-8400/RX 470. iGPU enabled. 

![D20B6200-1571-4C05-BAFE-0266C32BEE7C](https://user-images.githubusercontent.com/3365320/68835180-6edc3900-06f2-11ea-8be6-48807d4b2673.jpeg)

**Comment by vit9696** [comment]
This does not look like a bug to me, you should see the panic description above. It says you used cfgmap (perhaps injected via device properties), which is not supported.

**Comment by cattyhouse** [comment]
> This does not look like a bug to me, you should see the panic description above. It says you used cfgmap (perhaps injected via device properties), which is not supported.

Since i knew WEG inject iGPU properties automatically, i did not inject any properties under `PciRoot(0x0)/Pci(0x2,0x0)`, i removed this item from config.plist since a long time ago, should i add `AAPL,ig-platform-id` back? Also as you see, i did not add agdpmode boot-args either.

**Comment by vit9696** [comment]
agdpmod is notnecessarily a boot argument, it is read from a property too. That's why I believe some of your devices happened to have it, and its reading was fixed in 1.3.5. Could be a bug in my code of course, but so far you are the only with the issue.

As for ig-platform-id, it is entirely a separate thing, but injecting some fallback id is merely a way to boot, you should not rely on this value (either to exist, or to remain the same), and always inject the preferred id yourself.

**Comment by cattyhouse** [comment]
Added agdpmod=vit9696, same panic, same panic description. I will try agdpmod=ignore

**Comment by cattyhouse** [comment]
agdpmod=ignore does not panic, but got blackscreen. 

This is weird. I don’t know what adgpmod to use now. I have RX 470, and i did not specify any properties to this dGPU, everything remains default with it

**Comment by vit9696** [comment]
Fixed in master.

**Comment by cattyhouse** [comment]
> Fixed in master.

confirm fixed. thank you Vit.
