### ISSUE TITLE
BrcmPatchRAM dependency solving fails with OpenCore injection

### ISSUE THREAD

**Issue by lioliy** [acidanthera/bugtracker#604]
Hello Developers
When I trying load BrcmPatchRAM2/3.kext in OpenCore will throw a panic
My OpenCore version is 0.5.3
My device is dell 1560
I try boot in 10.15 installer but also panic and change any version of this kext but still panic.
When booted in clover with this kext no panic, and try loading in /Library/Extensions  works fine too
Here is the panic info
![panic](https://user-images.githubusercontent.com/13769444/70335094-9b165000-1881-11ea-99c0-edec77bbf6b1.png)

**Comment by vit9696** [comment]
This looks like injection order is wrong. BrcmFirmwareData.kext should be injected before BrcmPatchRamX.kext. Please fix that and report what exactly you had in your config.plist for further investigation, as we may want to produce a more user friendly error message in the future.

@Download-Fritz the good question is why does not this report injection failure early though, the kernel panic happens because `__ZN17BrcmFirmwareStore9metaClassE` contains invalid value (0xa200000). Could you please investigate? The binaries can be found here https://github.com/acidanthera/BrcmPatchRAM/releases/tag/2.5.0, it is release.

**Comment by lioliy** [comment]
vit9696 thank you.
I just change the order no panic anymore. It works fine.

> BrcmFirmwareData.kext should be injected before BrcmPatchRamX.kext.

Here is my bad config
[config.plist.zip](https://github.com/acidanthera/bugtracker/files/3940133/config.plist.zip)

**Comment by Download-Fritz** [comment]
Because we link KEXTs (mostly) in-place fine, we do not bookkeep what has already been patched (in terms of Mach-O symbols). Doing so would be more costy (both in time spent and in resource consumption) than is reasonable in this situation. In the future, create a log file with a DEBUG variant. For these KEXT pairs, I did get this message:
"Dependency as.acidanthera.BrcmFirmwareStore was not found for kext as.acidanthera.BrcmPatchRAM3"

Dependencies are considered "optional" because basically they are, e.g. this Apple KEXT pair:
"Dependency com.apple.driver.usb.AppleUSBHostPlatformProperties was not found for kext com.apple.iokit.IOUSBHostFamily" (I think this is because latter is a PLIST-only KEXT). Only actual bookkeeping would help here, but we don't believe it is worth it.

**Comment by startergo** [comment]
> Dependencies are considered "optional" because basically they are, e.g. this Apple KEXT pair:
> "Dependency com.apple.driver.usb.AppleUSBHostPlatformProperties was not found for kext com.apple.iokit.IOUSBHostFamily" (I think this is because latter is a PLIST-only KEXT). Only actual bookkeeping would help here, but we don't believe it is worth it.

So is there any way to force ```com.apple.driver.usb.AppleUSBHostPlatformProperties``` to load at the correct time? 
I see this message, but also after booting I checked:

```
 kextstat | grep com.apple.iokit.IOUSBHostFamily                  
   27   16 0xffffff7f8149a000 0xfa000    0xfa000    com.apple.iokit.IOUSBHostFamily (1.2) A6789428-66A5-3562-8D05-3693FFED5069 <26 25 24 8 7 6 5 3 1>
```
which is loaded. Is it safe to disregard this message in the log file? My ```BrcmPatchRAM``` is in a correct order with respect to ```BrcmFirmwareData.kext```.
