### ISSUE TITLE
OC The system clock is slow opencore 0.5.3

### ISSUE THREAD

**Issue by Across32** [acidanthera/bugtracker#618]
I use Catalina 10.15.1 OS on AMD system with opencore bootloader and the clock is very slow. The ARTFrequency, FSBFrequency, InitialTSC not responding to any number i tried different numbers and default setups. It can be solved?

**Comment by Download-Fritz** [comment]
AMD is not officially supported - if you figure the issue out, we will merge the solution, but we will not perform any investigations ourselves.

**Comment by startergo** [comment]
It look like OCCPU does not load properly the frequency and the microcode version. I have dual Westmere x5690's
`g5@G5s-Mac-Pro ~ % sysctl -a | grep cpu
hw.ncpu: 24
hw.activecpu: 24
hw.physicalcpu: 12
hw.physicalcpu_max: 12
hw.logicalcpu: 24
hw.logicalcpu_max: 24
hw.cputype: 7
hw.cpusubtype: 4
hw.cpu64bit_capable: 1
hw.cpufamily: 1463508716
hw.cpufrequency: 3500000000
hw.cpufrequency_min: 3500000000
hw.cpufrequency_max: 3500000000
hw.cputhreadtype: 1
machdep.cpu.max_basic: 11
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
machdep.cpu.family: 6
machdep.cpu.model: 44
machdep.cpu.extmodel: 2
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 2
machdep.cpu.feature_bits: 188838921972218879
machdep.cpu.extfeature_bits: 5034215680
machdep.cpu.signature: 132802
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT AES PCID
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF RDTSCP TSCI
machdep.cpu.logical_per_package: 32
machdep.cpu.cores_per_package: 16
machdep.cpu.microcode_version: 0
machdep.cpu.processor_flag: 0
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 4384
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 1
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.core_power_limits: 0
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 0
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.arch_perf.version: 3
machdep.cpu.arch_perf.number: 4
machdep.cpu.arch_perf.width: 48
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.events: 4
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.fixed_width: 48
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 8
machdep.cpu.cache.size: 256
machdep.cpu.tlb.inst.small: 64
machdep.cpu.tlb.inst.large: 7
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.data.large: 32
machdep.cpu.tlb.shared: 512
machdep.cpu.address_bits.physical: 40
machdep.cpu.address_bits.virtual: 48
machdep.cpu.core_count: 6
machdep.cpu.thread_count: 12
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.tsc_ccc.denominator: 0
machdep.xcpm.cpu_thermal_level: 0`
 
Plus it only detects 1 package instead of 2. Boot log:
`00:000 00:000 OC: OpenCore is now loading (Vault: 0/0, Sign 0/0)...
00:074 00:074 OC: Boot timestamp - 2019.12.24 03:29:49
00:151 00:076 OCCPU: Hypervisor: 0
00:226 00:075 OCCPU: Found Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
00:313 00:086 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0
00:390 00:076 OCCPU: Detected Apple Processor Type: 05 -> 0501
00:465 00:074 OCCPU: Ratio Min 12 Max 26 Current 0 Turbo 28 28 27 27
00:542 00:077 OCCPU: Timer address is 408 from LPC
00:717 00:175 OCCPU: CPUFrequencyFromTSC  3458000769Hz  3458MHz
00:792 00:075 OCCPU: CPUFrequency  3458000769Hz  3458MHz
00:868 00:075 OCCPU: FSBFrequency   133000029Hz   133MHz
00:943 00:074 OCCPU: Pkg 1 Cores 6 Threads 12`
According to the code:
`if (Cpu->Vendor[0] == CPUID_VENDOR_INTEL) {
      Cpu->MicrocodeRevision = AsmReadMsr32 (MSR_IA32_BIOS_SIGN_ID);
    }

    Cpu->Signature = Cpu->CpuidVerEax.Uint32;
    Cpu->Stepping  = (UINT8) Cpu->CpuidVerEax.Bits.SteppingId;
    Cpu->ExtModel  = (UINT8) Cpu->CpuidVerEax.Bits.ExtendedModelId;
    Cpu->Model     = (UINT8) Cpu->CpuidVerEax.Bits.Model | (UINT8) (Cpu->CpuidVerEax.Bits.ExtendedModelId << 4U);
    Cpu->Family    = (UINT8) Cpu->CpuidVerEax.Bits.FamilyId;
    Cpu->Type      = (UINT8) Cpu->CpuidVerEax.Bits.ProcessorType;
    Cpu->ExtFamily = (UINT8) Cpu->CpuidVerEax.Bits.ExtendedFamilyId;
    Cpu->Brand     = (UINT8) Cpu->CpuidVerEbx.Bits.BrandIndex;
    Cpu->Features  = (((UINT64) Cpu->CpuidVerEcx.Uint32) << 32ULL) | Cpu->CpuidVerEdx.Uint32;
    if (Cpu->Features & CPUID_FEATURE_HTT) {
      Cpu->ThreadCount = (UINT16) Cpu->CpuidVerEbx.Bits.MaximumAddressableIdsForLogicalProcessors;`
But microcode revision says 0 
machdep.cpu.microcode_version: 0 (in sysctl)
hw.cpufrequency: 3500000000
hw.cpufrequency_min: 3500000000
hw.cpufrequency_max: 3500000000 (instead of CPUFrequency  3458000769Hz)
This bug affects all cMP line.

**Comment by startergo** [comment]
I ran dmidecode when booted through OC and without it. Here are the results with OC for the processor read:
`Processor Information
	Socket Designation:  CPU-A (00)
	Type: Central Processor
	Family: Pentium 4
	Manufacturer: Intel(R) Corporation
	ID: C2 06 02 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 44, Stepping 2
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
	Voltage: 1.2 V
	External Clock: 25 MHz
	Max Speed: 3500 MHz
	Current Speed: 3500 MHz
	Status: Populated, Enabled
	Upgrade: ZIF Socket
	L1 Cache Handle: 0x0008
	L2 Cache Handle: 0x0009
	L3 Cache Handle: 0x000A
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 6
	Core Enabled: 6
	Thread Count: 12
	Characteristics: None
`
And here are the results without OC:
`Processor Information
	Socket Designation:  CPU-A (01)
	Type: Central Processor
	Family: Pentium 4
	Manufacturer: Intel(R) Corporation
	ID: C2 06 02 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 44, Stepping 2
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
	Voltage: 1.2 V
	External Clock: 133 MHz
	Max Speed: 3460 MHz
	Current Speed: 3460 MHz
	Status: Populated, Enabled
	Upgrade: ZIF Socket
	L1 Cache Handle: 0x0022
	L2 Cache Handle: 0x0023
	L3 Cache Handle: 0x0024
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
`
The biggest difference is that the external clock is read differently:
External Clock: 25 MHz
External Clock: 133 MHz
From there the processor speed is improperly calculated. 3460 VS 3500
Also without OC CPU-A reads (00), (01), (02), (03), (04), (05), (16), (17), (18), (19), (20), (21)
CPU-B reads (32), (33), (34), (35), (36), (37), (48), (49), (50), (51), (52), (53)
and with OC there is only CPU-A (00)

**Comment by vit9696** [comment]
I do not believe we will work on this and it is unclear what exactly is broken anyway. One can submit patches if he spots issues.
