### ISSUE TITLE
Apple BootPicker support

### ISSUE THREAD

**Issue by vit9696** [acidanthera/bugtracker#692]
I believe we should implement the support of running Apple BootPicker in firmwares where it is available as an alternative to our current UI. This will require the following changes:

- [ ] Add ExternalPicker option in Misc → Boot, which would try to boot the UI through OpenCore UI protocol, fallback to Apple BootPicker, and fail (or choose builtin picker?) otherwise.
- [ ] Add boot entry for Apple BootPicker in OpenCore builtin picker when it is available. I think we can determine this by checking for Apple firmware vendor in EFI System Table.
- [ ] Add a separate BootKicker tool to launch Apple Boot Picker after applying ProvideConsoleGop quirk. I am not positive whether it will 100% work, but it should hopefully get us Apple BootPicker on MacPro5,1 without OpenCore, which is useful to e.g. make OpenCore the default boot option through Ctrl+Enter.

To get Apple BootPicker to load we need to fetch it from the firmware volume via gAppleBootPickerFileGuid (see Guid/AppleFile.h in EfiPkg).

**Comment by vit9696** [comment]
After some thought we agreed that an entry is not well justified, but the rest is implemented as a part of `PickerMode` and `BootKicker` utility.

**Comment by vit9696** [comment]
Note, while it works on my MBP, on MacPro this may not launch BootPicker and fail at StartImage. Either with a freeze inside StartImage or StartImage failure. Further investigation may be needed if anybody wants.

**Comment by jacklukem** [comment]
Hello on MBP6,2 dual GPUs IntelHDGraphics and Nvidia GT 330 M ( default resolution 1680x1050 but also 1440x900 is rendered ) , enabling in OpenCore Tools Auxiliary BootKicker.efi and selecting it, apple startup manager is correctly shown but while picking any macOS drive get a green screen, after 10 seconds automatically returns to opencore menu .

Would it possible to make working BootKicker from OC menu on MBP6,2 ?

**Comment by vit9696** [comment]
Hello, that would need further reversing of macOS BootPicker, which we cannot afford at the moment. We believe OpenCanopy provides equal or better experience in this regard, so this issue has very low priority. However, any external contributions to resolve the problem will always be welcome.

**Comment by mikebeaton** [comment]
As already reported by pm, Apple Picker on earlier mac firmware does not start what it selects, rather it sets BootNext and then returns.

Also, Apple Picker when started by BootKicker from OC displays the long pause on a green screen before returning to OC, but when started by PickerMode=Apple it returns immediately.

Fixing the above will be somewhat academic unless there is further progress on the issue of why the Apple Picker cannot start on natively unsupported cards, even when OC has set up all required protocols. (Some recent further investigation of this, by trapping and logging LocateProtocol and LocateHandleBuffer, appears to indicate that the issue is not a missing protocol.)
