### ISSUE TITLE
Request for using OpenCore Logo in my OpenCore related project

### ISSUE THREAD

**Issue by SukkaW** [acidanthera/bugtracker#708]
Hello.

Recently I want to maintain an **unofficial** Simplified Chinese Version of OpenCore document, and I want to have a OpenCore Logo in that document. I am here to open the issue since under `OpenCorePkg/Docs/Logos/` I could see the terms of the usage for OpenCore Logo:

> The use of this logo in your own projects which are related to OpenCore is also permitted free of charge, yet requires OpenCore maintainer approval.

There is another question, is the original OpenCore documents released under BSD-3 License as well as OpenCore itself? I am not sure which Open Source License should I choose for my **unofficial** Simplified Chinese Version of the documents.

**Comment by btwise** [comment]
@SukkaW 
As a Chinese developer, you should develop a standard external GUI module for OC！

**Comment by Download-Fritz** [comment]
I'll leave a comment now because I'm a bit in a hurry and will probably just forget otherwise... please excuse any mistakes / harshly short expressions.

I'll heavily advise against literally translating the docs as they are supposed to be a *technical* manual that needs to be up to date (maintainance cost) at all time and is to be understood by technically versed people, who undoubtably need to know English. I'd advice more towards either a tutorial or wiki format, especially if you want to target more casual people. Please remember the docs are updated monthly and it's a responsibility to not mislead people (i.e. with deprecated or incorrect information).

As for the logo, I am personally fine with it being used in any context that 1) obviously relates to OpenCore and 2) makes obvious the material is not official (i.e. by Acidanthera or one of us personally). This needs approval from @vit9696 too though, this is just my 2 cents!

Thank you for your effort and good luck!

**Comment by vit9696** [comment]
Hello,

Several people had already asked us for a documentation translation in the past. The short answer is "do not do it". The longer answer is written [here](https://applelife.ru/posts/802866), and I include the translation below:

> Documentation in Russian, as well as in any other language, will create additional difficulties for the project, and therefore is highly undesirable. Of course, as a native Russian speaker, I get significant pleasure from reading fiction in my native language. I suppose, Download-Fritz, who made no less for OpenCore than me, also likes to read in German. However, the situation with technical literature is fundamentally different. Technical literature should be relevant, contain unambiguous terminology and semantics, be as close as possible to all participants, and not just to some of them. 
> 
> English is a de facto standard (see the ISO and IEC standards) language of international technical literature that most people can read. The state of the OpenCore documentation, even after the release, is highly likely to be updated and updated, which means that any translation will be automatically outdated and incorrect. Of course, it will be practically impossible for us to legally prosecute translating a document because of the peculiarities of applying international law, but I kindly ask everyone not to. 
> 
> In addition to the above, there are two more aspects: 
> - OpenCore documentation is designed for a programmer or engineer who understands macOS and UEFI. 
> - OpenCore is not required for the use by the masses or as a rival to other bootloaders. 
> 
> The first aspect means that for everyone else it will be much more useful to have a guide or an algorithm. For example, open config.plist, enter A, B, C, reboot, if you have black screen, enter D ... This is not a task for the documentation, and such things are best to have on the forums in any language. This kind of guide is much shorter, and it does not care about the internal details that the documentation needs to describe and clarify.
> 
> The second aspect means that if you are comfortable with BareBoot / Chameleon / Chimera / Clover / Ozmozis / etc, then you have no reason to switch to OpenCore because it has no documentation in your language. Including situations when you are missing a "tiny bit" in OpenCore. We have our advantages, other bootloaders have their own. The project and its architecture are created as we see it, in the most convenient way for us. It is extremely unlikely that such a solution will suit all the masses, and therefore I did not initially set the task of satisfying the needs of all people. Just pass by and we will not create unnecessary difficulties for each other. 

Taking all this into consideration, I would strongly recommend creating a guide or a translation of a guide (if their authors permit) instead of making a translation of the specification (which OpenCore documentation really is). An example of a guide is [OpenCore Vanilla Guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide).

As for the license, currently OpenCore specification is not licensed as a standalone product, only as a part of OpenCore, but like I said it is more about ethics rather than practical use. Other than that, the logo is fine to use as you explicitly and visibly mark that the use is unofficial.
