### ISSUE TITLE
OC: Background image support (png or jpg)

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#810]
do you have any plans to add features that will enable to use the background image if using the External picker in an opencore?

actually, externel picker UI is very useful even if preview version (not audio delay).
i'm not asking you to add more functions as quickly, but hope you can add background image function after 0.5.8 at the end of stabilization.

ty, CC @vit9696

**Comment by vit9696** [comment]
Added to the wishlist in https://github.com/acidanthera/bugtracker/issues/759.

**Comment by ZISQO** [comment]
> Added to the wishlist in #759.

ty @vit9696  take care of your healthy!

**Comment by LeeBinder** [comment]
chiming in on .jpg background image support 👍

**Comment by vit9696** [comment]
We will not implement one for security reasons (by reducing the amount of formats supported).

**Comment by LeeBinder** [comment]
Really? What harm could a Jpeg cause, even in a running fully booted OS compared with other possible threads, but let alone on bootloader level? It would need to contain malicious code specifically created to be executed by the OC bootloader. I'd say the chance for that is less than a trillionth of a percent. Instead we have these blown up Retina res files based on the .icns format which is totally not made for that purpose. As per Apple specs, .icns files should only house graphics up to 512 x 512 px. To have each of them contain images of 3840 x 2160 px is a total rape of this format (esp. when one let's say only has a 1920 x 1080 monitor).

Also from what I know, the graphics format inside .icns is PNG-24 which is why these files tend to blow up as they do.

I kindly advice you devs to think this over by putting all items onto the scale and look at this from a broader perspective.

The naming convention could be something like this:
background-3840x2160.jpg
background-1920x1080.jpg
etc.

That way we only have what we need in small nicely compressed and - yes - secure files ;)

**Comment by vit9696** [comment]
I would not explain in a better detail what our primary concerns of having a JPEG decoder inside OpenCore are, instead I would rather explain the situation with the PNG decoder:

- OpenCore does not decode the unused slice, so there is no issue having it.
- Whether or not the file ondisk is more compressed (i.e. jpeg vs png) it still has to be decoded to RAW 32-bit image inside OpenCore.
- PNG images can be quite well compressed with ImageOptim (it even has lossy compression).

So from OpenCore point of view it does not matter much whether it is PNG or JPEG, and the I/O is not really a problem. If you think it is, we may update the code to not even read the second slice, but that would get low priority.

**Comment by LeeBinder** [comment]
Thanks @vit9696 for your thorough reply

> OpenCore does not decode the unused slice, so there is no issue having it

true, but bummer that chris1111's OpenCanopy Generator at this point has no option to exclude the retina 3840x2160 png @ 144 dpi

> Whether or not the file ondisk is more compressed (i.e. jpeg vs png) it still has to be decoded to RAW 32-bit image inside OpenCore.

true, too - it's just about the file size. In my EFI release, background.icns is by far the biggest file, and of its size 3/4 would be bloatware if I hadn't adapted OpenCanopy Generator's script that it's only 50% bloated anymore.

> PNG images can be quite well compressed with ImageOptim (it even has lossy compression)

in the script I just mentioned, I had modified `pngquant --quality=90` into `pngquant --quality=45`. Seems to be [equivalent to `ImageOptim`](https://www.google.com/search?sclient=psy-ab&site=&source=hp&btnG=Search&q=pngquant+--quality%3D+ImageOptim&oq=&gs_l=&pbx=1) and indeed did make a difference.

> So from OpenCore point of view it does not matter much whether it is PNG or JPEG, and the I/O is not really a problem

again true, only from upload/ download point of view.

> If you think it is, we may update the code to not even read the second slice

I appreciate your offer, but that would be tackling this at an inefficient side because it would not change the file size.

When I have some time again for hackintosh I'll contact chris1111 if he would include an option in OpenCanopy Generator to have one of the slices inside background.icns be empty so we can package dedicated Resource folders for higher and lower res = more size efficient.

**Comment by Andrey1970AppleLife** [comment]
OpenCanopy Generator - It not ours. 
Use icnspack from OpenCore utilities.

**Comment by LeeBinder** [comment]
@Andrey1970AppleLife gosh, man, how easy can life sometimes be, LOL

why is everybody raving about OpenCanopy Generator??

made a little script:

<details>
  <summary>click to expand</summary> 

  ```javascript
#!/bin/bash
clear

cd "$(dirname "$0")"

# Usage:
# icnspack image.icns 1x.png 2x.png

./icnspack background.icns background_1920x1080.png background_3840x2160.png
echo
  ```
</details>

then, in Photoshop,
 1. created a PNG-8 background_1920x1080.png @72 dpi @256 colors + dither
 2. only for preview in Finder, created a PNG-8 background_3840x2160.png but 89x50 px @144 dpi

result: [background.icns.zip](https://github.com/acidanthera/bugtracker/files/6057850/background.icns.zip) (916kb) :) I'm sure you like the motive..

Could've minimized the size even more by choosing fewer colors, but I'm more than happy with that size @ 1920

THANKS DEVS for your efforts & perseverance 👍 💯 🥇  !!

**Comment by Andrey1970AppleLife** [comment]
Forget about dpi, it makes no difference, it doesn't influence on anything.

**Comment by LeeBinder** [comment]
it does make a diff for the high res one, because when I save it @144, it still looks the same in Finder when expanded to double the viewable size, but the file size stays the same. I've done both, the math + the file size measuring + comparison when I was messing with OpenCanopy Generator, and both (calc & empiric) matched/ added up :) Here now for this small thumbnail it's only a couple kb diff, however (like the ski-jumpers right now winning by mm and ms LOL)

**Comment by Andrey1970AppleLife** [comment]
OpenCanopy doesn't use dpi, the picture size in pixels is important only.

**Comment by LeeBinder** [comment]
.. but both, icnspack and OpenCanopy, do - they blow up slice 1 to retina 144 dpi even if the source png is less dpi. You can see when you open image.icns in Preview, click onto the thumbnail of slice 1 so It's active,  CMD + I - in the pop-up you'll see 144dpi

**Comment by Andrey1970AppleLife** [comment]
> .. but both, icnspack and OpenCanopy, do 

OpenCanopy it boot picker, he isn't able to create an icon.
I think it is time to finish talk because you don't stop. Do that you want, to me bothered you to explain.
