### ISSUE TITLE
New APFS Jumpstart

### ISSUE THREAD

**Issue by n-d-k** [acidanthera/bugtracker#842]
I just tested this new APFS Jumpstart. There are couple things I noticed and like to let you know.

1.  APFS Jumpstart was called before all other drivers was loaded, which meant any drives connect through NvmExpressDxe driver will be left out unless the JumpstartHotplug is enabled.

2. If there are two Nvme drives, the APFS was loaded twice, the second times it loaded will have a verbose on the screen regardless the verbose suppression was on. I used efi shell to check the loaded drivers, there was indeed 2 instances of APFS.

**Comment by vit9696** [comment]
1. Currently this is expected. I am not sure whether we need to change this. Will discuss internally and make a decision.

2. This is expected that two APFS drivers are loaded. Exactly the same behaviour applies to ApfsImageLoader (or at least should apply). Different disks may need different APFS drivers to mount.

3. This is unexpected that verbose output is shown when verbose is suppressed. Are you sure you do not have apfs.efi or anything alike? Is `If there are two Nvme drives` important to reproduce the issue?

**Comment by n-d-k** [comment]
You can disregard the verbose not suppressed. I just double checked again and tried to capture the verbose message.  It wasn't from APFS driver.  It was from OC failed to parse the mindate field, which I entered as 20200201 in Number type(not sure which format would be correct).

By the way, IMO the APFS connection should happen after all other drivers was loaded in order to avoid JumpstartHotplug need to be on, which is currently default to be off.

**Comment by asava** [comment]
Actually, this message appears even with HideVerbose=true:
`00:000 00:000 OCJS: APFS driver 748077010000000/20190424 found for F8A2B562-1EB3-CC47-828A-6B3FB2E1076B, required >= 748077012000000/20200101, prohibited`

**Comment by vit9696** [comment]
> By the way, IMO the APFS connection should happen after all other drivers was loaded in order to avoid JumpstartHotplug need to be on, which is currently default to be off.

We agreed to change the connection order. So OpenCore firstly loads the drivers, and then tries to load & connect APFS drivers. This resolves the first report.

> Actually, this message appears even with HideVerbose=true, I have a few macOS systems, one is out of date

This is expected, because not loaded driver can actually fail your booting. Why do you want to hide it?

> It was from OC failed to parse the mindate field, which I entered as 20200201 in Number type(not sure which format would be correct).

I was unable to reproduce this. MinDate parses just fine for me, and this is the expected value. On the other side `-1` did not parse. This is resolved in master.

**Comment by asava** [comment]
> This is expected, because not loaded driver can actually fail your booting. Why do you want to hide it?
Driver was loaded from other partitions, but I also have an old OS that I use only in rare situations (which is intentionally out of date). Don't you think that HideVerbose for APFS should disable that message as well?

**Comment by vit9696** [comment]
I do not think the driver will load from other partitions as of master version, and it is not guaranteed. To be honest, I can hide that message, but that will not make your old OS bootable. In my opinion, you should rather change the version in MinDate.

**Comment by asava** [comment]
True, with that driver not loaded, the old macOS doesn't even show in OpenCore boot menu. 
But that's fine, as it's a legacy system, that shouldn't really be bootable in normal conditions (for example, it also needs other SMBIOS info to be able to boot).
But if you think that message should not be suppressed, I'm fine with it. It's only that I expected that it should be hidden with HideVerbose, that's why I reported it.

**Comment by vit9696** [comment]
HideVerbose hides APFS logs, this is part of OC log. Well, I guess it will not do harm to only log it in debug builds. Changed in master.
