### ISSUE TITLE
NVRAM value "efi-boot-device"&"efi-boot-device-data" no effect

### ISSUE THREAD

**Issue by laozhiang** [acidanthera/bugtracker#862]
I install two macos with oc 0.5.7, one is my work OS,another is test beta macOS version
I make bootmenu with grub. I want when boot form oc it's always boot my work OS. I set "efi-boot-device"&"efi-boot-device-data" in my config.plist, but it's no use. I still must change boot disk in "boot disk pane". Is there a way set default boot option.
My config.plist  is like follow:
`<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<dict>
				<key>DefaultBackgroundColor</key>
				<data>AAAAAA==</data>
				<key>UIScale</key>
				<data>Ag==</data>
			</dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>efi-boot-device</key>
		<data>PGFycmF5PjxkaWN0PjxrZXk+SU9NYXRjaDwva2V5PjxkaWN0PjxrZXk+SU9Qcm92aWRlckNsYXNzPC9rZXk+PHN0cmluZz5JT01lZGlhPC9zdHJpbmc+PGtleT5JT1Byb3BlcnR5TWF0Y2g8L2tleT48ZGljdD48a2V5PlVVSUQ8L2tleT48c3RyaW5nPjZGRUE5RDgxLTcyMzgtNEQ1Ni04MjFGLTJGRDFENzVCNUU1NDwvc3RyaW5nPjwvZGljdD48L2RpY3Q+PGtleT5CTExhc3RCU0ROYW1lPC9rZXk+PHN0cmluZz5kaXNrMXMyPC9zdHJpbmc+PC9kaWN0PjxkaWN0PjxrZXk+SU9FRklEZXZpY2VQYXRoVHlwZTwva2V5PjxzdHJpbmc+TWVkaWFGaWxlUGF0aDwvc3RyaW5nPjxrZXk+UGF0aDwva2V5PjxzdHJpbmc+XDUwMjU3OTFCLTZENUQtNEZBNy05QkZFLTE3ODQxRjIzQUM5OVxTeXN0ZW1cTGlicmFyeVxDb3JlU2VydmljZXNcYm9vdC5lZmk8L3N0cmluZz48L2RpY3Q+PC9hcnJheT4A</data>
				<key>efi-boot-device-data</key>
				<data>AgEMANBBAwoAAAAAAQEGAAAdAQEGAAAAAxYQAAEAAAAAAAAAAAAAAAQBKgAGAAAAABAQcAAAAAAAAAAEAAAAAIgbuN1AhJNCprG5w5yp5YECAgQDJAD3/HS+fAvzSZFHAfQELmhCgZ3qbzhyVk2CHy/R11teVAQEmgBcADUAMAAyADUANwA5ADEAQgAtADYARAA1AEQALQA0AEYAQQA3AC0AOQBCAEYARQAtADEANwA4ADQAMQBGADIAMwBBAEMAOQA5AFwAUwB5AHMAdABlAG0AXABMAGkAYgByAGEAcgB5AFwAQwBvAHIAZQBTAGUAcgB2AGkAYwBlAHMAXABiAG8AbwB0AC4AZQBmAGkAAAB//wQA</data>
				<key>boot-args</key>
				<string>-cdfon -igfxmlr</string>
				<key>csr-active-config</key>
				<data>AAAAAA==</data>
				<key>prev-lang:kbd</key>
				<data>cnUtUlU6MjUy</data>
			</dict>
		</dict>
		<key>Block</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<array>
				<string>UIScale</string>
				<string>DefaultBackgroundColor</string>
			</array>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<array>
				<string>efi-boot-device</string>
				<string>efi-boot-device-data</string>
				<string>boot-args</string>
			</array>
		</dict>
`

**Comment by vit9696** [comment]
OpenCore uses `BootOrder` and `Boot####` variables to determine boot priority. You will need to set them instead. This actually follows AppleBds implementation.

The documentation about the format of these variables can be found in [UEFI Specification](https://uefi.org) or [EDK II](https://github.com/tianocore/edk2/blob/c18708d/MdePkg/Include/Uefi/UefiSpec.h#L2056).

In case you use `RequestBootVarRouting` (and I guess you very likely do), make sure to use `4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102` (`OC_VENDOR_VARIABLE_GUID`) instead of `8BE4DF61-93CA-11D2-AA0D-00E098032B8C` (`EFI_GLOBAL_VARIABLE_GUID`) to store the options. Also do not forget about `Block` section to make sure the operating does not override your preference.
