### ISSUE TITLE
USB mouse doesn't work in OpenCanopy

### ISSUE THREAD

**Issue by usr-sse2** [acidanthera/bugtracker#866]
@crushers said:
Can u add support for mouse?

**Comment by usr-sse2** [comment]
> Can u add support for mouse?

Mouse is already supported. It works.

**Comment by usr-sse2** [comment]
@crushers
> Mouse is already supported. It works.

Sorry but for me does not work.

**Comment by usr-sse2** [comment]
@telepati
@crushers what kind of mouse are you using? Because mouses (Apple Magic Mouses) always worked since @Download-Fritz merge the OpenCanopy to OpenCore. Response time little slow but it always worked.

**Comment by usr-sse2** [comment]
@crushers
> @crushers what kind of mouse are you using? Because mouses (Apple Magic Mouses) always worked since @Download-Fritz merge the OpenCanopy to OpenCore. Response time little slow but it always worked.

I use classic USB mouse.

**Comment by usr-sse2** [comment]
@crushers Do you have USB mouse UEFI driver installed or built-in in the firmware? Does the mouse work in FileVault password screen or in Clover?

**Comment by usr-sse2** [comment]
@telepati Wow, Bluetooth mouse can work in UEFI?! What Bluetooth dongle are you using?

**Comment by telepati** [comment]
> @telepati Wow, Bluetooth mouse can work in UEFI?! What Bluetooth dongle are you using?

I have BCM4360CD Combo Wi-Fi card and using Magic Mouse 1. Combo card working natively.

**Comment by Andrey1970AppleLife** [comment]
My devices: Magic Mouse 1, Simple USB mouse, Elan PS2 trackpad - no problem.

**Comment by telepati** [comment]
But on real iMac 9,1 mouse doesnt work with v0.5.8.

**Comment by vit9696** [comment]
* On a real Mac you need AppleEvent = TRUE and also some other protocols. This is because old Macs have old AppleEvent and we only support new one, so you will need to upgrade it to OpenCore's versions
* I fixed the issue with the mouse in 0.5.8 by switching to AppleEvent, the reason was the preferred mouse on ConIn handle was doing nothing. Unlike manual simple pointer polling AppleEvent works with all handles.
* BT mice may or may not work, this is out of the scope. Check FV2 GUI or BIOS GUI for a test.
