### ISSUE TITLE
Support loading custom GuC firmware

### ISSUE THREAD

**Issue by adriandumitru** [acidanthera/bugtracker#867]
Currently loading Apple GuC firmware using igfxfw=2 causes issues on SKL at least.
Would it be possible to load another GuC, for example the ones from the linux kernel?

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915

We can see the GuC firmware signature (also HuC) present in AppleIntelSKLGraphics
06 00 00 00 A1 00 00 00 00 00 01 00 00 00 00 00 86 80

**Comment by vit9696** [comment]
This is implemented via `igfxfw=1`. The flag is not documented, because a lot of functions in the driver are not implemented to support Linux GuC, and using it causes freezes and glitches.

**Comment by vit9696** [comment]
Forgot to mention that at some point (before 10.15) there was support for loading Linux GuC on KBL as well. The difficulty with that one was Apple IGPU drivers having SKL GuC instead of KBL, and it needed to be upgraded via hacks and patches (`loadIGScheduler4Patches`), this did not go smoothly on 10.15.

Since the issues with freezes and glitches were all the same the support for Linux GuC for KBL was entirely discontinued in 10.15 and for SKL it was left half-working as is.

Code contributions are welcome in this direction if you want of course.
